import { CustomDayPlan, CustomMealSlot, CustomMealItem } from '../data/customStudio7DayPlans';
import { GeneralInfo, Calculations } from '../types';

export interface GeneratePlanParams {
  conditionName: string;
  domainGroup?: 'diseases' | 'disorders' | 'performance' | 'fitness' | 'diet_domains' | string;
  generalInfo?: Partial<GeneralInfo>;
  calculations?: Partial<Calculations>;
  targetCalories?: number;
  dietaryPreference?: 'vegetarian' | 'non_vegetarian' | 'ovo_vegetarian' | 'vegan';
  allergies?: string[];
}

interface DishTemplate {
  dishName: string;
  portionHousehold: string;
  weightGrams: number;
  calories: number;
  protein: number;
  fat: number;
  carbs: number;
  fiber: number;
  glycemicStatus: 'Low GI (<55)' | 'Medium GI (56-69)' | 'High GI (>70)';
  therapeuticNote: string;
  isVegetarian: boolean;
  isEgg: boolean;
  isVegan: boolean;
  allergens?: string[]; // e.g. ['dairy', 'gluten', 'nuts']
}

// ============================================================================
// DISTINCT MEAL CATEGORY SPECIALIZED POOLS
// Rule: Dishes in Breakfast NEVER appear in Lunch, Snacks, Dinner, or Bedtime!
// ============================================================================

/**
 * 1. BREAKFAST SPECIALIZED POOL (Morning Metabolism, Low GI, High Fiber, Bioactive Grains)
 */
const BREAKFAST_MASTER_BANK: Record<string, DishTemplate[]> = {
  diabetes: [
    {
      dishName: 'Sprouted Green Moong Dal Chilla (2 pcs) with Fresh Mint Chutney',
      portionHousehold: '2 medium chillas (140g) + 2 tbsp chutney',
      weightGrams: 170,
      calories: 230,
      protein: 15.0,
      fat: 4.5,
      carbs: 27.0,
      fiber: 7.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Sprouted pulses deliver resistant starch and low glycemic load to prevent morning dawn phenomenon.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Steamed Thinai (Foxtail Millet) Idli (3 nos) with Drumstick Keerai Sambar',
      portionHousehold: '3 idlis (150g) + 1 small katori sambar (80g)',
      weightGrams: 230,
      calories: 250,
      protein: 8.5,
      fat: 3.0,
      carbs: 45.0,
      fiber: 6.8,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Foxtail millet beta-glucan and drumstick leaves provide chlorogenic acid to blunt postprandial glucose.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Broken Wheat (Dalia) & French Bean Upma with Crushed Roasted Mustard',
      portionHousehold: '1 bowl (180g cooked)',
      weightGrams: 180,
      calories: 215,
      protein: 7.0,
      fat: 3.5,
      carbs: 38.0,
      fiber: 8.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Wheat bran arabinoxylans slow carbohydrate enzymatic cleavage in the duodenum.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['gluten'],
    },
    {
      dishName: 'Crisp Oats & Soaked Methi Seed Dosa with Tomato Onion Chutney',
      portionHousehold: '2 medium dosas (130g) + 2 tbsp chutney',
      weightGrams: 160,
      calories: 240,
      protein: 9.0,
      fat: 5.0,
      carbs: 38.0,
      fiber: 7.2,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: '4-hydroxyisoleucine in fenugreek stimulates glucose-dependent insulin secretion.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Multigrain Methi Keerai Thepla (2 pcs) with A2 Cow Curd',
      portionHousehold: '2 soft theplas (120g) + 1/2 katori curd (60g)',
      weightGrams: 180,
      calories: 260,
      protein: 11.0,
      fat: 6.0,
      carbs: 38.0,
      fiber: 6.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Jowar, besan, and fenugreek greens blend provides balanced amino acids and gut-healthy lactic acid bacteria.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Protein Egg White Scramble (3 whites) with Sautéed Baby Spinach & 1 Multigrain Phulka',
      portionHousehold: '3 egg whites bhurji + 1 phulka (40g)',
      weightGrams: 190,
      calories: 220,
      protein: 19.5,
      fat: 4.0,
      carbs: 22.0,
      fiber: 4.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High-biological-value albumin with zero glycemic impact anchors basal muscle protein synthesis.',
      isVegetarian: false,
      isEgg: true,
      isVegan: false,
    },
    {
      dishName: 'Sprouted Black Chana (Kala Chana) Sundal with Grated Coconut & Ginger',
      portionHousehold: '1 large bowl (160g cooked)',
      weightGrams: 160,
      calories: 245,
      protein: 14.5,
      fat: 4.5,
      carbs: 34.0,
      fiber: 10.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Dense amylose content provides sustained 4-hour satiety with minimal insulin excursion.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],

  hypertension: [
    {
      dishName: 'Moringa Leaves & Foxtail Millet Pongal (Low Sodium with Rock Salt)',
      portionHousehold: '1 bowl (180g cooked)',
      weightGrams: 180,
      calories: 225,
      protein: 7.8,
      fat: 3.5,
      carbs: 39.0,
      fiber: 7.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Abundant potassium (420mg) and magnesium promote endothelial nitric oxide vasodilation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Steamed Ragi & Coriander Dosa with Garlic Tomato Kootu Chutney',
      portionHousehold: '2 dosas (130g) + 2 tbsp chutney',
      weightGrams: 160,
      calories: 235,
      protein: 6.5,
      fat: 4.0,
      carbs: 42.0,
      fiber: 7.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Allicin in fresh garlic and polyphenol flavonoids in finger millet relax vascular smooth muscle.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Rolled Oats Porridge with Flaxseed Powder, Cinnamon & Walnuts',
      portionHousehold: '1 bowl (200ml)',
      weightGrams: 200,
      calories: 240,
      protein: 8.5,
      fat: 6.5,
      carbs: 36.0,
      fiber: 6.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Omega-3 ALA and oat beta-glucan reduce arterial stiffness and systemic vascular resistance.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
    {
      dishName: 'Red Rice Vegetable Poha with Sprouted Moong & Fresh Curry Leaves',
      portionHousehold: '1 medium plate (170g)',
      weightGrams: 170,
      calories: 230,
      protein: 8.0,
      fat: 4.0,
      carbs: 39.0,
      fiber: 5.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Anthocyanins in unpolished red rice protect endothelial cell membranes from oxidative stress.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Sprouted Horsegram (Kollu) & Ash Gourd Chilla with Mint Chutney',
      portionHousehold: '2 medium chillas (140g)',
      weightGrams: 140,
      calories: 220,
      protein: 13.0,
      fat: 3.5,
      carbs: 32.0,
      fiber: 8.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Naturally diuretic polyphenols assist natriuresis without causing potassium wasting.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Steamed Samai (Little Millet) Idli (3 nos) with Palak Keerai Dal',
      portionHousehold: '3 idlis (150g) + 1/2 katori dal (70g)',
      weightGrams: 220,
      calories: 240,
      protein: 9.0,
      fat: 3.0,
      carbs: 43.0,
      fiber: 6.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'DASH compliant: natural dietary nitrates from spinach convert to vasoprotective nitric oxide.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Chia & Low-Fat Greek Yogurt Bowl with Papaya Cubes & Pumpkin Seeds',
      portionHousehold: '1 bowl (180g)',
      weightGrams: 180,
      calories: 220,
      protein: 14.0,
      fat: 5.5,
      carbs: 27.0,
      fiber: 6.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High calcium and magnesium balance cellular pump activity and blunt morning BP spikes.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
  ],

  performance: [
    {
      dishName: 'Power Oats & Whey / Pea Protein Bowl with Banana Slices, Chia & Almond Butter',
      portionHousehold: '1 large bowl (250g)',
      weightGrams: 250,
      calories: 360,
      protein: 26.0,
      fat: 8.0,
      carbs: 46.0,
      fiber: 7.5,
      glycemicStatus: 'Medium GI (56-69)',
      therapeuticNote: '26g rapid leucine combined with complex starches primes muscle glycogen and mTOR signaling.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
    {
      dishName: 'Whole Egg & White Omelette (1 whole + 3 whites) with Sweet Potato Hash & Sourdough',
      portionHousehold: '4 egg scramble + 80g sweet potato',
      weightGrams: 260,
      calories: 380,
      protein: 28.0,
      fat: 9.0,
      carbs: 44.0,
      fiber: 5.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Choline, essential micronutrients, and clean complex carbohydrates fuel high-intensity endurance output.',
      isVegetarian: false,
      isEgg: true,
      isVegan: false,
    },
    {
      dishName: 'Quinoa & Sprouted Green Moong Breakfast Pulao with Cashew Crunch',
      portionHousehold: '1 large plate (220g)',
      weightGrams: 220,
      calories: 350,
      protein: 18.0,
      fat: 8.5,
      carbs: 49.0,
      fiber: 8.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Complete amino acid profile (all 9 EAAs) prevents muscular catabolism during aerobic training.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
    {
      dishName: 'Millet & Soya Paneer (Tofu) Bhurji Roll in 2 Whole Wheat Phulkas',
      portionHousehold: '2 rolls (200g)',
      weightGrams: 200,
      calories: 370,
      protein: 24.0,
      fat: 8.0,
      carbs: 48.0,
      fiber: 7.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Plant isoflavones and high-density protein sustain nitrogen retention for athletes.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['gluten'],
    },
    {
      dishName: 'Sprouted Ragi & Cocoa Protein Malt with Crushed Walnuts & Dates',
      portionHousehold: '1 tall glass (280ml)',
      weightGrams: 280,
      calories: 330,
      protein: 20.0,
      fat: 6.5,
      carbs: 47.0,
      fiber: 7.0,
      glycemicStatus: 'Medium GI (56-69)',
      therapeuticNote: 'Natural flavanols increase cerebral and muscular blood flow for enhanced VO2 peak capacity.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
    {
      dishName: 'Paneer & Sprouted Chana High-Protein Cheela (2 pcs) with Mint Dip',
      portionHousehold: '2 cheelas (180g) + 2 tbsp dip',
      weightGrams: 210,
      calories: 380,
      protein: 25.0,
      fat: 11.0,
      carbs: 42.0,
      fiber: 8.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Sustained amino acid release across 4 hours to minimize delayed onset muscle soreness (DOMS).',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Steamed Kuthiraivali Idlis (4 nos) with High-Protein Sambar & Boiled Egg Whites (2 nos)',
      portionHousehold: '4 idlis (180g) + sambar (100g) + 2 whites',
      weightGrams: 340,
      calories: 390,
      protein: 24.5,
      fat: 4.5,
      carbs: 61.0,
      fiber: 7.8,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Fast gastric transit carbohydrates paired with clean albumin accelerate pre-training absorption.',
      isVegetarian: false,
      isEgg: true,
      isVegan: false,
    },
  ],

  pcos: [
    {
      dishName: 'Organic Spearmint Infused Methi Chilla (2 pcs) with Flaxseed Chutney',
      portionHousehold: '2 chillas (140g) + 2 tbsp chutney',
      weightGrams: 165,
      calories: 230,
      protein: 14.0,
      fat: 5.5,
      carbs: 28.0,
      fiber: 8.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Spearmint suppresses free testosterone; lignans in flaxseed bind circulating excess androgens.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Steamed Samai (Little Millet) & Sprouted Moong Idli with Drumstick Leaf Sambar',
      portionHousehold: '3 idlis (150g) + 1 katori sambar',
      weightGrams: 230,
      calories: 240,
      protein: 9.5,
      fat: 3.0,
      carbs: 42.0,
      fiber: 7.2,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Myo-inositol precursors in unpolished millets promote ovarian follicle maturation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Chia & Pumpkin Seed Overnight Oats with Ceylon Cinnamon & Crushed Berries',
      portionHousehold: '1 bowl (180g)',
      weightGrams: 180,
      calories: 235,
      protein: 8.5,
      fat: 6.0,
      carbs: 35.0,
      fiber: 7.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Zinc in pumpkin seeds supports follicular phase hormone synthesis and blunts acne flares.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Sprouted Green Moong & Grated Bottle Gourd Cheela with Mint Chutney',
      portionHousehold: '2 cheelas (150g)',
      weightGrams: 150,
      calories: 220,
      protein: 13.5,
      fat: 4.0,
      carbs: 29.0,
      fiber: 8.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High fiber with zero insulin spiking protects pancreatic beta-cells from hyperinsulinemic stress.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Avocado & Boiled Sprouts Salad on 1 Multigrain Phulka with Roasted Sunflower Seeds',
      portionHousehold: '1 open wrap (170g)',
      weightGrams: 170,
      calories: 250,
      protein: 9.0,
      fat: 8.5,
      carbs: 32.0,
      fiber: 7.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Monounsaturated oleic acid and selenium restore ovulatory regularity.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Ragi Malt (Sprouted Finger Millet) with Toasted Sesame Seeds & Cardamom',
      portionHousehold: '1 glass (220ml)',
      weightGrams: 220,
      calories: 210,
      protein: 6.5,
      fat: 4.5,
      carbs: 34.0,
      fiber: 6.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High calcium (340mg) and plant iron address anovulatory metabolic fatigue.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Tofu & Baby Spinach Scramble with Turmeric & 1 Sprouted Grain Toast',
      portionHousehold: '1 plate (180g)',
      weightGrams: 180,
      calories: 240,
      protein: 17.0,
      fat: 6.5,
      carbs: 26.0,
      fiber: 5.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Isoflavones act as natural selective estrogen receptor modulators (SERMs).',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],
};

/**
 * 2. LUNCH SPECIALIZED POOL (Main Midday Metabolic Plate: Grains + Dals + Vegetable Sabzi/Poriyal + Digestive Probiotics)
 */
const LUNCH_MASTER_BANK: Record<string, DishTemplate[]> = {
  diabetes: [
    {
      dishName: 'Hand-pounded Mappillai Samba Red Rice + Palak Moong Dal + Cabbage Poriyal + A2 Probiotic Curd',
      portionHousehold: '80g cooked rice + 1 cup dal + 1 cup poriyal + 1/2 cup curd',
      weightGrams: 380,
      calories: 420,
      protein: 19.5,
      fat: 7.0,
      carbs: 64.0,
      fiber: 12.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Polyphenols in red rice slow carbohydrate digestion; cabbage sulforaphane clears hepatic triglycerides.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: '2 Jowar (Sorghum) Bhakri Rotis + Spiced Yellow Toor Dal Tadka + Bhindi (Okra) Stir-Fry + Cucumber Slices',
      portionHousehold: '2 jowar rotis (100g) + 1 bowl dal (150g) + 1 cup bhindi + salad',
      weightGrams: 390,
      calories: 435,
      protein: 17.0,
      fat: 7.5,
      carbs: 68.0,
      fiber: 13.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Okra mucilage fiber binds luminal glucose molecules, mitigating post-lunch somnolence.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Kuthiraivali (Barnyard Millet) Khichdi with Split Green Moong + Bitter Gourd (Pavakkai) Crisps + Buttermilk',
      portionHousehold: '1 plate khichdi (220g) + 50g baked pavakkai + 150ml neer mor',
      weightGrams: 420,
      calories: 410,
      protein: 18.0,
      fat: 6.0,
      carbs: 65.0,
      fiber: 14.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Charantin and vicine in bitter gourd exhibit natural insulinomimetic activity.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Steamed Brown Rice + Horsegram (Kollu) Rasam + Ridge Gourd (Peerkangai) Kootu + Steamed Beans',
      portionHousehold: '70g rice + 1 cup rasam + 1 cup kootu + beans',
      weightGrams: 370,
      calories: 390,
      protein: 16.5,
      fat: 5.5,
      carbs: 63.0,
      fiber: 12.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Kollu contains concentrated alpha-amylase inhibitors for precision postprandial glucose blunting.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: '2 Multigrain Phulkas + Soya Chunks & Green Peas Curry + Radish Poriyal + Fresh Spiced Neer Mor',
      portionHousehold: '2 phulkas (70g) + 1 cup soya curry + 1 cup poriyal + buttermilk',
      weightGrams: 410,
      calories: 430,
      protein: 26.0,
      fat: 6.5,
      carbs: 60.0,
      fiber: 11.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High plant protein suppresses postprandial ghrelin and improves insulin sensitivity index.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy', 'gluten'],
    },
    {
      dishName: 'Varagu (Kodo Millet) Vegetable Pulao + Sprouted Kala Chana Curry + Tomato Cucumber Raita',
      portionHousehold: '1 bowl pulao (180g) + 1 cup chana curry + 1/2 cup raita',
      weightGrams: 400,
      calories: 440,
      protein: 20.0,
      fat: 8.0,
      carbs: 67.0,
      fiber: 13.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High dietary fiber in Kodo millet delays gastric emptying and nourishes beneficial gut microbiota.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Grilled Tofu / Steamed Fish Fillet + Hand-pounded Rice (50g) + Drumstick Keerai Poriyal + Lemon Dal',
      portionHousehold: '100g protein + rice + greens + dal',
      weightGrams: 390,
      calories: 420,
      protein: 28.0,
      fat: 8.5,
      carbs: 52.0,
      fiber: 10.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Rich in omega-3 and essential amino acids to modulate cellular insulin signaling pathways.',
      isVegetarian: false,
      isEgg: false,
      isVegan: false,
    },
  ],

  hypertension: [
    {
      dishName: 'Samai (Little Millet) Rice + High-Potassium Drumstick Sambar + Ash Gourd Kootu + Garlic Neer Mor',
      portionHousehold: '80g cooked millet + 1 cup sambar + 1 cup kootu + 150ml neer mor',
      weightGrams: 400,
      calories: 395,
      protein: 15.5,
      fat: 5.0,
      carbs: 67.0,
      fiber: 12.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'DASH synergy: 680mg potassium and 95mg magnesium counteract sodium retention.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: '2 Ragi (Finger Millet) Phulkas + Sprouted Moong & Bottle Gourd Dal + Sautéed Kovakkai (Ivy Gourd)',
      portionHousehold: '2 rotis (80g) + 1 bowl dal (160g) + 1 cup kovakkai',
      weightGrams: 390,
      calories: 410,
      protein: 18.0,
      fat: 6.0,
      carbs: 65.0,
      fiber: 14.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Finger millet calcium (320mg) normalizes vascular muscular tone and arterial compliance.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Hand-pounded Rice + Beetroot Poriyal + Masoor Dal with Cumin & Curry Leaves + Low-Salt Cucumber Salad',
      portionHousehold: '70g rice + 1 cup beetroot + 1 cup dal + salad',
      weightGrams: 380,
      calories: 390,
      protein: 16.0,
      fat: 4.5,
      carbs: 68.0,
      fiber: 11.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Beetroot dietary nitrates convert systematically to nitric oxide to decrease peripheral resistance.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: '2 Jowar Roti + Steamed Palak Dal + Sautéed Raw Banana Poriyal + Spiced Buttermilk',
      portionHousehold: '2 rotis + 1 cup palak dal + 1 cup raw banana + buttermilk',
      weightGrams: 410,
      calories: 420,
      protein: 17.5,
      fat: 6.0,
      carbs: 69.0,
      fiber: 13.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Raw banana resistant starch generates short-chain fatty acids that lower blood pressure centrally.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Thinai (Foxtail Millet) Lemon Pulao + Black Eyed Pea (Karamani) Sundal Curry + Mint Raita',
      portionHousehold: '1 plate pulao (180g) + 1 cup karamani + 1/2 cup raita',
      weightGrams: 390,
      calories: 425,
      protein: 19.0,
      fat: 7.0,
      carbs: 66.0,
      fiber: 12.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Lemon citric acid enhances mineral bio-availability while potassium clears intracellular sodium.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Steamed Red Rice + Turmeric Garlic Rasam + Steamed Chow Chow Kootu + Yellow Moong Dal',
      portionHousehold: '75g rice + 1 cup rasam + 1 cup kootu + 1/2 cup dal',
      weightGrams: 380,
      calories: 385,
      protein: 14.5,
      fat: 4.5,
      carbs: 66.0,
      fiber: 11.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Garlic allicin acts as a gentle natural ACE inhibitor to sustain midday normotension.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Grilled Salmon / Steamed Mackerel (Ayala) + 1 Jowar Roti + Sautéed French Beans + Spiced Neer Mor',
      portionHousehold: '100g fish + 1 roti + 1 cup beans + buttermilk',
      weightGrams: 390,
      calories: 430,
      protein: 29.0,
      fat: 10.5,
      carbs: 48.0,
      fiber: 9.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: '1200mg EPA/DHA marine omega-3 fatty acids lower blood pressure and systemic inflammation.',
      isVegetarian: false,
      isEgg: false,
      isVegan: false,
    },
  ],

  performance: [
    {
      dishName: 'High-Protein Quinoa Rice Bowl + Grilled Chicken Breast / Paneer Tikka (140g) + Steamed Broccoli & Dal',
      portionHousehold: '100g cooked quinoa + 140g protein + 1 cup veggies + dal',
      weightGrams: 460,
      calories: 580,
      protein: 44.0,
      fat: 12.0,
      carbs: 68.0,
      fiber: 11.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Complete amino acid profile (leucine >3.2g) maximally triggers skeletal muscle protein synthesis.',
      isVegetarian: false,
      isEgg: false,
      isVegan: false,
    },
    {
      dishName: '3 Multigrain Phulkas + Soya Chunks & Chickpea Masala + Cucumber Tomato Salad + A2 Curd',
      portionHousehold: '3 phulkas (110g) + 1.5 cup curry + salad + 1 cup curd',
      weightGrams: 480,
      calories: 590,
      protein: 36.0,
      fat: 11.0,
      carbs: 82.0,
      fiber: 15.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Dual-source plant protein and sustained glycogen replenishment for high-workload athletic demands.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy', 'gluten'],
    },
    {
      dishName: 'Steamed Basmati / Samba Rice (100g) + Double Moong Dal Tadka + 3 Boiled Egg Whites + Sautéed Spinach',
      portionHousehold: '1 plate rice + 1.5 cup dal + 3 egg whites + 1 cup spinach',
      weightGrams: 470,
      calories: 540,
      protein: 34.0,
      fat: 8.5,
      carbs: 76.0,
      fiber: 10.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Optimal 2:1 carbohydrate-to-protein ratio accelerates intra-myocellular glycogen restock.',
      isVegetarian: false,
      isEgg: true,
      isVegan: false,
    },
    {
      dishName: 'Foxtail Millet & Sprouted Horsegram Pulao + Grilled Tofu Steaks (120g) + Spiced Buttermilk',
      portionHousehold: '1 large bowl pulao + 120g tofu + 200ml buttermilk',
      weightGrams: 480,
      calories: 560,
      protein: 35.0,
      fat: 14.0,
      carbs: 70.0,
      fiber: 14.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Sustained endurance fuel: horsegram phenolics reduce exercise-induced cellular lipid peroxidation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: '2 Large Jowar Rotis + Rajma (Red Kidney Bean) Masala + Beetroot Carrot Salad + Curd',
      portionHousehold: '2 rotis (120g) + 1.5 cup rajma + salad + 1 cup curd',
      weightGrams: 490,
      calories: 570,
      protein: 28.0,
      fat: 10.0,
      carbs: 86.0,
      fiber: 16.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High dietary potassium, magnesium, and slow starch prevent mid-training neuromuscular cramping.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Brown Rice Pulao with Mixed Sprouts & Paneer Cubes (100g) + Drumstick Keerai Sambar',
      portionHousehold: '1 large plate pulao + 1 bowl sambar',
      weightGrams: 470,
      calories: 560,
      protein: 32.0,
      fat: 15.0,
      carbs: 72.0,
      fiber: 12.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Casein-whey complex supports continuous plasma amino acid circulation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Steamed Ayala (Mackerel) / Tuna in Turmeric Pepper Curry + 2 Phulkas + Sautéed Zucchini',
      portionHousehold: '140g fish + 2 phulkas + 1 cup zucchini',
      weightGrams: 450,
      calories: 550,
      protein: 42.0,
      fat: 13.0,
      carbs: 60.0,
      fiber: 8.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High natural creatine and omega-3 EPA speeds eccentric muscle recovery post-load.',
      isVegetarian: false,
      isEgg: false,
      isVegan: false,
      allergens: ['gluten'],
    },
  ],

  pcos: [
    {
      dishName: 'Mappillai Samba Red Rice + Methi Moong Dal + Sautéed Cabbage & Green Peas + Spearmint Neer Mor',
      portionHousehold: '70g rice + 1 cup dal + 1 cup veggies + 150ml buttermilk',
      weightGrams: 390,
      calories: 410,
      protein: 18.5,
      fat: 6.5,
      carbs: 64.0,
      fiber: 13.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Cruciferous indoles (DIM) metabolize excess estrogen; fenugreek improves insulin sensitivity.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: '2 Jowar Bhakris + Soya Chunks & Mushroom Masala + Kovakkai Stir-Fry + Cucumber Slices',
      portionHousehold: '2 rotis (90g) + 1 cup soya curry + 1 cup kovakkai + salad',
      weightGrams: 410,
      calories: 425,
      protein: 24.0,
      fat: 7.0,
      carbs: 62.0,
      fiber: 14.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Rich in zinc and inositol; zero glycemic spikes suppress ovarian theca cell androgen synthesis.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Samai (Little Millet) Khichdi with Split Yellow Moong + Bitter Gourd Poriyal + Spiced Curd',
      portionHousehold: '1 plate khichdi (200g) + 1 cup pavakkai + 1/2 cup curd',
      weightGrams: 380,
      calories: 400,
      protein: 17.0,
      fat: 6.5,
      carbs: 63.0,
      fiber: 12.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Charantin blunts hyperinsulinemia, helping prevent anovulatory cystic follicular arrest.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: '2 Multigrain Phulkas + Sprouted Kala Chana Sundal Curry + Steamed Ridge Gourd Kootu',
      portionHousehold: '2 phulkas (70g) + 1 cup chana + 1 cup kootu',
      weightGrams: 380,
      calories: 415,
      protein: 18.0,
      fat: 5.5,
      carbs: 68.0,
      fiber: 14.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Inositol-rich pulses enhance luteinizing hormone (LH) / FSH ratio balance.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['gluten'],
    },
    {
      dishName: 'Varagu (Kodo Millet) Vegetable Upma Pulao + Palak Dal Tadka + Grated Radish Salad',
      portionHousehold: '1 bowl pulao (180g) + 1 cup dal + salad',
      weightGrams: 390,
      calories: 395,
      protein: 17.5,
      fat: 6.0,
      carbs: 63.0,
      fiber: 13.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Folate and magnesium enhance hepatic phase-2 detoxification of circulating hormones.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: '2 Ragi Rotis + Paneer & Methi Bhurji (80g) + Steamed French Beans + Mint Raita',
      portionHousehold: '2 rotis + 80g paneer + 1 cup beans + 1/2 cup raita',
      weightGrams: 400,
      calories: 430,
      protein: 21.0,
      fat: 10.0,
      carbs: 58.0,
      fiber: 11.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High calcium and bioavailable protein prevent metabolic resistance.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Steamed Fish Fillet / Tofu Tikka + 50g Hand-pounded Rice + Drumstick Sambar + Cucumber Salad',
      portionHousehold: '100g protein + rice + sambar + salad',
      weightGrams: 390,
      calories: 410,
      protein: 27.0,
      fat: 7.5,
      carbs: 54.0,
      fiber: 10.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Essential anti-inflammatory omega-3 and selenium reduce hirsutism markers.',
      isVegetarian: false,
      isEgg: false,
      isVegan: false,
    },
  ],
};

/**
 * 3. SNACKS SPECIALIZED POOL (Mid-Morning & Evening Metabolic Boosters, Low GI, Portion-Controlled)
 * Rule: Snacks are never main grains/dals; they are functional seeds, nuts, roasted pulses, teas, broths.
 */
const SNACKS_MASTER_BANK: Record<string, DishTemplate[]> = {
  diabetes: [
    {
      dishName: 'Dry Roasted Makhana (Foxnuts) with Turmeric & Himalayan Pink Salt',
      portionHousehold: '1 medium katori (25g raw)',
      weightGrams: 25,
      calories: 90,
      protein: 2.8,
      fat: 0.5,
      carbs: 18.0,
      fiber: 3.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Kaempferol flavonoids in foxnuts suppress vascular inflammation and oxidative stress.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Spiced Neer Mor (Buttermilk) with Crushed Curry Leaves, Ginger & Hing',
      portionHousehold: '1 tall glass (200ml)',
      weightGrams: 200,
      calories: 60,
      protein: 3.5,
      fat: 1.5,
      carbs: 5.0,
      fiber: 0.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Lactic acid bacteria promote gut integrity and generate acetate to blunt glucose cravings.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Roasted Chana (Bengal Gram with Skin) + 4 Soaked Almonds',
      portionHousehold: '30g chana + 4 almonds',
      weightGrams: 35,
      calories: 125,
      protein: 6.5,
      fat: 3.5,
      carbs: 15.0,
      fiber: 4.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Intact legume skin contains concentrated beta-glucan and insoluble fibers.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
    {
      dishName: 'Fresh Guava Slices sprinkled with Rock Salt & Roasted Cumin Powder',
      portionHousehold: '1 medium fruit (120g)',
      weightGrams: 120,
      calories: 70,
      protein: 2.5,
      fat: 0.8,
      carbs: 14.0,
      fiber: 6.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High pectin soluble fiber and vitamin C without spiking postprandial glucose.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Sprouted Green Moong & Grated Carrot Chaat with Fresh Lemon Squeeze',
      portionHousehold: '1 small katori (80g)',
      weightGrams: 80,
      calories: 95,
      protein: 6.0,
      fat: 0.8,
      carbs: 15.0,
      fiber: 4.2,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Ascorbic acid from lemon juice enhances bio-availability of non-heme pulse iron.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Moringa Leaf & Vegetable Clear Broth with Crushed Black Pepper',
      portionHousehold: '1 cup (180ml)',
      weightGrams: 180,
      calories: 45,
      protein: 2.5,
      fat: 0.5,
      carbs: 6.5,
      fiber: 2.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Quercetin in moringa clears cellular oxidative markers and calms afternoon cortisol.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Pumpkin Seeds (1 tbsp) & Roasted Flaxseeds (1 tsp) Snack Mix',
      portionHousehold: '20g seeds',
      weightGrams: 20,
      calories: 110,
      protein: 5.5,
      fat: 8.5,
      carbs: 3.5,
      fiber: 3.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Plant zinc and magnesium support peripheral insulin receptor phosphorylation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],

  hypertension: [
    {
      dishName: 'Tender Coconut Water (Low Glycemic) with 1 tsp Soaked Sabja (Basil) Seeds',
      portionHousehold: '200ml + 1 tsp seeds',
      weightGrams: 205,
      calories: 55,
      protein: 1.2,
      fat: 0.5,
      carbs: 11.0,
      fiber: 3.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: '480mg bioavailable potassium and basil mucilage cool sympathetic tone.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Roasted Lotus Seeds (Makhana) with Ground Black Pepper & Mint Powder',
      portionHousehold: '1 cup (25g)',
      weightGrams: 25,
      calories: 90,
      protein: 2.8,
      fat: 0.5,
      carbs: 18.0,
      fiber: 3.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Zero sodium, high magnesium snack protects against afternoon blood pressure spikes.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Fresh Papaya Cubes with Lime Juice & Soaked Chia Seeds',
      portionHousehold: '1 bowl (120g)',
      weightGrams: 120,
      calories: 65,
      protein: 1.5,
      fat: 1.2,
      carbs: 14.0,
      fiber: 3.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Papain enzyme and beta-carotene promote endothelial micro-vascular flow.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Hibiscus & Cinnamon Herbal Tea + 3 Soaked Walnuts',
      portionHousehold: '1 cup tea (180ml) + 3 walnut halves (15g)',
      weightGrams: 195,
      calories: 100,
      protein: 2.5,
      fat: 9.0,
      carbs: 3.0,
      fiber: 1.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Clinical trials show hibiscus anthocyanins reduce systolic BP comparable to mild diuretics.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
    {
      dishName: 'Cucumber, Pomegranate & Coriander Crisp Salad with Lemon Dressing',
      portionHousehold: '1 small bowl (100g)',
      weightGrams: 100,
      calories: 50,
      protein: 1.2,
      fat: 0.3,
      carbs: 11.0,
      fiber: 2.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Punicalagin polyphenols enhance arterial endothelial relaxation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Spiced Neer Mor with Crushed Ginger, Asafoetida & Fresh Mint',
      portionHousehold: '1 glass (200ml)',
      weightGrams: 200,
      calories: 55,
      protein: 3.2,
      fat: 1.2,
      carbs: 5.0,
      fiber: 0.4,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Hydrating electrolyte carrier that clears excess intracellular sodium.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Steamed Ash Gourd & Tomato Clear Broth with Crushed Black Pepper',
      portionHousehold: '1 cup (180ml)',
      weightGrams: 180,
      calories: 35,
      protein: 1.5,
      fat: 0.2,
      carbs: 6.0,
      fiber: 2.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Naturally alkalizing diuretic broth reduces vascular fluid retention.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],

  performance: [
    {
      dishName: 'Natural Electrolyte Tender Coconut Water with Himalayan Pink Salt & Chia',
      portionHousehold: '1 tall glass (250ml)',
      weightGrams: 255,
      calories: 70,
      protein: 2.0,
      fat: 1.5,
      carbs: 13.0,
      fiber: 4.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Restores potassium-sodium plasma osmolarity during mid-afternoon training blocks.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Banana & Peanut Butter Rice Cakes (2 nos) with Hemp Seeds',
      portionHousehold: '2 cakes (90g)',
      weightGrams: 90,
      calories: 180,
      protein: 7.0,
      fat: 6.5,
      carbs: 24.0,
      fiber: 3.0,
      glycemicStatus: 'Medium GI (56-69)',
      therapeuticNote: 'Rapid hepatic glycogen delivery combined with healthy fats for sustained ATP regeneration.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
    {
      dishName: 'Boiled Egg Whites (3 nos) seasoned with Black Pepper & Cumin + 4 Soaked Almonds',
      portionHousehold: '3 egg whites + 4 almonds',
      weightGrams: 110,
      calories: 115,
      protein: 14.5,
      fat: 3.5,
      carbs: 2.5,
      fiber: 1.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Clean BCAAs with minimal digestive load during intermediate training intervals.',
      isVegetarian: false,
      isEgg: true,
      isVegan: false,
      allergens: ['nuts'],
    },
    {
      dishName: 'Roasted Kala Chana & Pumpkin Seed Energy Trail Mix',
      portionHousehold: '40g mix',
      weightGrams: 40,
      calories: 160,
      protein: 8.5,
      fat: 5.5,
      carbs: 18.0,
      fiber: 5.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Sustained nitrogen release and zinc for anabolic endocrine priming.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Greek Yogurt Bowl (120g) with Blueberries, Cinnamon & Crushed Walnuts',
      portionHousehold: '1 cup (150g)',
      weightGrams: 150,
      calories: 165,
      protein: 13.0,
      fat: 5.0,
      carbs: 16.0,
      fiber: 2.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Dense micellar casein prevents skeletal muscle breakdown between meals.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy', 'nuts'],
    },
    {
      dishName: 'Beetroot, Ginger & Orange Pre-Training Nitric Oxide Elixir',
      portionHousehold: '200ml cold-pressed juice',
      weightGrams: 200,
      calories: 85,
      protein: 2.2,
      fat: 0.3,
      carbs: 19.0,
      fiber: 3.0,
      glycemicStatus: 'Medium GI (56-69)',
      therapeuticNote: 'Increases plasma nitrite levels, significantly delaying time-to-exhaustion.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Steamed Sprouted Horsegram Sundal with Coconut & Mustard Tempered Seeds',
      portionHousehold: '1 small katori (80g)',
      weightGrams: 80,
      calories: 120,
      protein: 7.5,
      fat: 2.5,
      carbs: 17.0,
      fiber: 5.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High polyphenol and iron content boost oxygen-carrying red cell resilience.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],

  pcos: [
    {
      dishName: 'Organic Spearmint Tea (Hot Infusion) + 1 tbsp Pumpkin Seeds (Follicular Support)',
      portionHousehold: '1 cup tea (180ml) + 15g seeds',
      weightGrams: 195,
      calories: 85,
      protein: 4.5,
      fat: 6.5,
      carbs: 2.5,
      fiber: 1.8,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Dual action: spearmint down-regulates 5-alpha reductase; pumpkin seed zinc balances testosterone.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Roasted Makhana with Turmeric, Black Pepper & Chia Seeds',
      portionHousehold: '1 bowl (25g)',
      weightGrams: 25,
      calories: 95,
      protein: 3.0,
      fat: 1.2,
      carbs: 17.0,
      fiber: 3.8,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Zero sugar crunch prevents insulin hypersecretion and downstream ovarian stimulation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Fresh Guava or Green Apple with Ceylon Cinnamon Powder',
      portionHousehold: '1 fruit (100g)',
      weightGrams: 100,
      calories: 60,
      protein: 1.5,
      fat: 0.5,
      carbs: 13.0,
      fiber: 4.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Cinnamaldehyde acts as an insulin mimetic and enhances cellular glucose disposal.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Spiced Neer Mor with Fresh Curry Leaves & Pinch of Fenugreek Powder',
      portionHousehold: '1 glass (200ml)',
      weightGrams: 200,
      calories: 55,
      protein: 3.2,
      fat: 1.2,
      carbs: 5.0,
      fiber: 0.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Fenugreek soluble saponins improve glucose tolerance and modulate gonadotropin levels.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Sprouted Moong & Pomegranate Chaat with Fresh Lime',
      portionHousehold: '1 small katori (75g)',
      weightGrams: 75,
      calories: 85,
      protein: 5.5,
      fat: 0.6,
      carbs: 14.0,
      fiber: 3.8,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Punicalagins and bioflavonoids reduce ovarian oxidative stress and inflammation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Roasted Flaxseeds (1 tbsp) & Roasted Sesame Seeds (1 tsp) Mix',
      portionHousehold: '18g seed mix',
      weightGrams: 18,
      calories: 95,
      protein: 3.8,
      fat: 7.5,
      carbs: 3.0,
      fiber: 3.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Seed cycling: sesame seed lignans inhibit excess estrogen while providing calcium.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Tomato & Moringa Clear Herbal Soup with Cumin',
      portionHousehold: '1 cup (180ml)',
      weightGrams: 180,
      calories: 40,
      protein: 2.2,
      fat: 0.4,
      carbs: 6.5,
      fiber: 2.2,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Micronutrient dense, anti-inflammatory, calming cortisol without caloric excess.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],
};

/**
 * 4. DINNER SPECIALIZED POOL (Evening Digestion, Low GI, Gut-Soothing, Non-Bloating, Overnight Autophagy)
 * Rule: Dinner items are lighter than lunch, featuring therapeutic soups, light khichdis, soft phulkas, gourds.
 */
const DINNER_MASTER_BANK: Record<string, DishTemplate[]> = {
  diabetes: [
    {
      dishName: 'Sprouted Green Moong Dal Chilla (2 pcs) with Steamed Bottle Gourd (Surakkai) Kootu',
      portionHousehold: '2 chillas (130g) + 1 cup kootu (150g)',
      weightGrams: 280,
      calories: 310,
      protein: 17.5,
      fat: 5.0,
      carbs: 45.0,
      fiber: 11.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High fiber with easy digestibility prevents nocturnal hypoglycemic dips and dawn spikes.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: '2 Multigrain Phulkas (Jowar + Besan) + Palak Methi Paneer (Zero Cream) + Clear Tomato Soup',
      portionHousehold: '2 phulkas (70g) + 100g paneer subji + 1 cup soup',
      weightGrams: 320,
      calories: 340,
      protein: 20.0,
      fat: 9.0,
      carbs: 42.0,
      fiber: 9.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Fenugreek leaves activate GLUT-4 glucose transporters overnight.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Barnyard Millet (Kuthiraivali) & Split Moong Vegetable Khichdi + Mint Raita',
      portionHousehold: '1 bowl khichdi (180g) + 1/2 cup raita (80g)',
      weightGrams: 260,
      calories: 290,
      protein: 12.5,
      fat: 4.5,
      carbs: 48.0,
      fiber: 9.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Barnyard millet has the lowest glycemic index among millets (GI ~45).',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Steamed Fish Fillet / Grilled Tofu Tikka (120g) + Warm Vegetable Clear Soup + 1 Phulka',
      portionHousehold: '120g protein + 1 cup soup + 1 phulka (35g)',
      weightGrams: 310,
      calories: 320,
      protein: 26.0,
      fat: 6.5,
      carbs: 34.0,
      fiber: 7.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Pure amino acids with minimal carbohydrate load prevent insulin elevation before bed.',
      isVegetarian: false,
      isEgg: false,
      isVegan: false,
    },
    {
      dishName: '2 Ragi Phulkas + Ridge Gourd (Peerkangai) & Moong Dal Gravy + Steamed French Beans',
      portionHousehold: '2 rotis (70g) + 1 bowl kootu (150g) + beans',
      weightGrams: 290,
      calories: 300,
      protein: 14.0,
      fat: 4.0,
      carbs: 48.0,
      fiber: 10.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Gourd water content promotes smooth digestive peristalsis during sleep.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Oats & Sprouted Horsegram Dosa (2 pcs) with Drumstick Keerai Sambar',
      portionHousehold: '2 dosas (130g) + 1 katori sambar (90g)',
      weightGrams: 220,
      calories: 315,
      protein: 14.5,
      fat: 5.5,
      carbs: 49.0,
      fiber: 10.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High resistant starch and beta-glucan soluble fibers sustain 12-hour fasting euglycemia.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Paneer / Soya Bhurji (100g) with Sautéed Baby Spinach & 1 Jowar Roti',
      portionHousehold: '100g bhurji + 1 jowar roti (45g)',
      weightGrams: 220,
      calories: 325,
      protein: 21.0,
      fat: 8.5,
      carbs: 37.0,
      fiber: 7.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Low carbohydrate density promotes nocturnal growth hormone secretion.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
  ],

  hypertension: [
    {
      dishName: 'Ash Gourd & Moong Dal Clear Soup + 2 Steamed Ragi Phulkas with Sautéed Kovakkai',
      portionHousehold: '1 cup soup + 2 rotis (70g) + 1 cup veggies',
      weightGrams: 300,
      calories: 290,
      protein: 13.0,
      fat: 4.0,
      carbs: 47.0,
      fiber: 10.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Alkalizing potassium-rich gourd eases renal filtration overnight.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Samai (Little Millet) & Yellow Moong Khichdi + Steamed Bottle Gourd with Hing & Jeera',
      portionHousehold: '1 bowl khichdi (180g) + 1 cup lauki',
      weightGrams: 280,
      calories: 285,
      protein: 12.0,
      fat: 3.5,
      carbs: 49.0,
      fiber: 9.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Zero added sodium load; cumin and asafoetida calm evening vascular tone.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: '2 Jowar Rotis + Palak & Fresh Garlic Dal + Low-Salt Cucumber Salad',
      portionHousehold: '2 rotis (70g) + 1 bowl dal + salad',
      weightGrams: 310,
      calories: 310,
      protein: 15.0,
      fat: 4.5,
      carbs: 50.0,
      fiber: 10.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Garlic allicin maintains arterial elasticity and prevents nocturnal hypertension.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Steamed Ayala (Mackerel) / Tofu in Coriander Tomato Broth + 1 Phulka',
      portionHousehold: '110g protein + broth + 1 phulka (35g)',
      weightGrams: 280,
      calories: 315,
      protein: 25.0,
      fat: 7.5,
      carbs: 32.0,
      fiber: 6.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'EPA/DHA omega-3 reduces blood viscosity and supports restorative deep sleep.',
      isVegetarian: false,
      isEgg: false,
      isVegan: false,
    },
    {
      dishName: 'Steamed Kuthiraivali Idlis (3 nos) with Drumstick Leaves & Lentil Kootu',
      portionHousehold: '3 idlis (150g) + 1 cup kootu (120g)',
      weightGrams: 270,
      calories: 280,
      protein: 11.5,
      fat: 3.0,
      carbs: 49.0,
      fiber: 8.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Moringa bio-actives protect glomerular vascular endothelium.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: '2 Multigrain Phulkas + Steamed Snake Gourd (Pudalangai) Poriyal + Yellow Moong Dal',
      portionHousehold: '2 rotis + 1 cup gourd + 1/2 cup dal',
      weightGrams: 290,
      calories: 295,
      protein: 13.5,
      fat: 3.8,
      carbs: 49.0,
      fiber: 9.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High water and magnesium content prevent night-time vascular constriction.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['gluten'],
    },
    {
      dishName: 'Paneer & Sautéed Methi Stir-Fry (80g paneer) + 1 Whole Wheat Roti + Tomato Soup',
      portionHousehold: '80g paneer + 1 roti + 1 cup soup',
      weightGrams: 270,
      calories: 320,
      protein: 18.5,
      fat: 9.0,
      carbs: 37.0,
      fiber: 7.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Calcium and potassium synergy sustains smooth vascular relaxation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy', 'gluten'],
    },
  ],

  performance: [
    {
      dishName: 'Grilled Herb Chicken / Salmon / Paneer (140g) + Sweet Potato Mash (100g) & Steamed Asparagus',
      portionHousehold: '1 plate (340g)',
      weightGrams: 340,
      calories: 460,
      protein: 38.0,
      fat: 10.0,
      carbs: 50.0,
      fiber: 7.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Glutamine, zinc, and slow carbs nourish nighttime myofibrillar protein remodeling.',
      isVegetarian: false,
      isEgg: false,
      isVegan: false,
    },
    {
      dishName: '3 Phulkas + Soya Chunks & Dal Makhani (No Cream) + Steamed Greens',
      portionHousehold: '3 phulkas (100g) + 1.5 cup dal curry',
      weightGrams: 380,
      calories: 480,
      protein: 28.0,
      fat: 9.0,
      carbs: 68.0,
      fiber: 12.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Sustained amino acid release across the 8-hour recovery sleep cycle.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['gluten'],
    },
    {
      dishName: 'Quinoa & Moong Dal Protein Khichdi with Gir Cow Ghee (1 tsp) + Grilled Tofu Steaks',
      portionHousehold: '1 bowl khichdi (220g) + 80g tofu',
      weightGrams: 300,
      calories: 440,
      protein: 26.0,
      fat: 9.5,
      carbs: 58.0,
      fiber: 9.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Butyric acid from ghee repairs exercise-induced gut micro-permeability.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: '2 Jowar Rotis + Double Egg Bhurji (2 whole + 2 whites) + Sautéed Mushrooms & Spinach',
      portionHousehold: '2 rotis + 4 egg scramble + veggies',
      weightGrams: 350,
      calories: 470,
      protein: 32.0,
      fat: 12.0,
      carbs: 54.0,
      fiber: 8.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Choline and bioavailable albumin optimize nocturnal muscle rebuilding.',
      isVegetarian: false,
      isEgg: true,
      isVegan: false,
    },
    {
      dishName: 'Foxtail Millet Pulao with Sprouted Black Chana (120g) + Steamed Palak Dal',
      portionHousehold: '1 plate pulao + 1 bowl dal',
      weightGrams: 360,
      calories: 450,
      protein: 24.0,
      fat: 7.5,
      carbs: 68.0,
      fiber: 13.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High iron and magnesium support cellular ATP regeneration during deep sleep.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: '3 Steamed Samai Idlis + High-Protein Lentil Sambar + 2 Boiled Egg Whites',
      portionHousehold: '3 idlis (150g) + sambar + 2 whites',
      weightGrams: 320,
      calories: 430,
      protein: 25.0,
      fat: 5.0,
      carbs: 67.0,
      fiber: 8.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Fast-digesting recovery meal without evening gastrointestinal heaviness.',
      isVegetarian: false,
      isEgg: true,
      isVegan: false,
    },
    {
      dishName: 'Steamed Ayala (Mackerel) / Tuna Steak (140g) + 1 Multigrain Phulka + Sautéed Zucchini & Carrot',
      portionHousehold: '140g fish + 1 phulka + 1 cup veggies',
      weightGrams: 330,
      calories: 450,
      protein: 36.0,
      fat: 11.0,
      carbs: 46.0,
      fiber: 7.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High natural anti-inflammatory fatty acids reduce exercise-induced soreness (DOMS).',
      isVegetarian: false,
      isEgg: false,
      isVegan: false,
      allergens: ['gluten'],
    },
  ],

  pcos: [
    {
      dishName: 'Sprouted Moong & Bottle Gourd Chilla (2 pcs) with Mint Chutney & Ash Gourd Soup',
      portionHousehold: '2 chillas (130g) + 1 cup soup',
      weightGrams: 280,
      calories: 295,
      protein: 16.5,
      fat: 4.5,
      carbs: 44.0,
      fiber: 11.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Zero glycemic spike prevents nocturnal cortisol and androgen surges.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: '2 Jowar Phulkas + Soya Chunks & Palak Curry + Steamed Cucumber Salad',
      portionHousehold: '2 rotis (70g) + 1 cup soya curry + salad',
      weightGrams: 310,
      calories: 320,
      protein: 21.0,
      fat: 5.5,
      carbs: 45.0,
      fiber: 11.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Phytoestrogens and inositols support follicular hormone equilibrium.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Kuthiraivali (Barnyard Millet) Khichdi with Split Yellow Moong + Ridge Gourd Kootu',
      portionHousehold: '1 bowl khichdi (180g) + 1/2 cup kootu',
      weightGrams: 260,
      calories: 285,
      protein: 13.0,
      fat: 4.0,
      carbs: 47.0,
      fiber: 10.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Barnyard millet resistant starch feeds Bifidobacteria, reducing systemic endotoxemia.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: '2 Ragi Phulkas + Steamed French Beans & Sprouted Chana Kootu',
      portionHousehold: '2 rotis (70g) + 1 bowl kootu (150g)',
      weightGrams: 290,
      calories: 305,
      protein: 14.5,
      fat: 4.5,
      carbs: 49.0,
      fiber: 11.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High plant calcium and zinc support progesterone synthesis.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Grilled Tofu Steaks (110g) with Sautéed Broccoli & Baby Spinach + 1 Multigrain Phulka',
      portionHousehold: '110g tofu + 1 cup veggies + 1 phulka (35g)',
      weightGrams: 290,
      calories: 310,
      protein: 22.0,
      fat: 8.0,
      carbs: 34.0,
      fiber: 8.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Indole-3-carbinol in broccoli helps clear 16-hydroxyestrone metabolites.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['gluten'],
    },
    {
      dishName: 'Samai (Little Millet) Upma with Finely Chopped Carrots, Beans & Methi Leaves',
      portionHousehold: '1 bowl (180g)',
      weightGrams: 180,
      calories: 280,
      protein: 9.5,
      fat: 4.5,
      carbs: 48.0,
      fiber: 8.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High soluble fiber and magnesium promote insulin sensitivity during fasting.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Steamed Fish Fillet (110g) / Egg White Scramble (3 whites) + Lauki Soup + 1 Jowar Roti',
      portionHousehold: '110g protein + 1 cup soup + 1 roti (40g)',
      weightGrams: 290,
      calories: 315,
      protein: 26.0,
      fat: 6.0,
      carbs: 36.0,
      fiber: 6.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Lean anti-inflammatory protein supports restorative overnight hepatic detox.',
      isVegetarian: false,
      isEgg: true,
      isVegan: false,
    },
  ],
};

/**
 * 5. BEDTIME SPECIALIZED POOL (Therapeutic Herbal Infusions, Restorative Decoctions, Sleep Primers)
 * Rule: Bedtime is exclusively restorative beverages, tonics, and medicinal infusions; NEVER solid meal dishes!
 */
const BEDTIME_MASTER_BANK: Record<string, DishTemplate[]> = {
  diabetes: [
    {
      dishName: 'Warm Golden Turmeric Skimmed Milk with Crushed Black Pepper & Cinnamon',
      portionHousehold: '1 cup (150ml)',
      weightGrams: 150,
      calories: 70,
      protein: 4.5,
      fat: 1.5,
      carbs: 7.0,
      fiber: 0.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Curcumin combined with piperine reduces systemic insulin resistance and suppresses liver gluconeogenesis.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Organic Chamomile & Spearmint Herbal Infusion',
      portionHousehold: '1 warm cup (180ml)',
      weightGrams: 180,
      calories: 10,
      protein: 0.2,
      fat: 0.0,
      carbs: 2.0,
      fiber: 0.2,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Apigenin binds GABA-A receptors to quiet sympathetic nerve firing and prevent 3 AM cortisol spikes.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Warm Ceylon Cinnamon & Methi Seed Soaked Water',
      portionHousehold: '1 warm glass (180ml)',
      weightGrams: 180,
      calories: 15,
      protein: 0.5,
      fat: 0.1,
      carbs: 3.0,
      fiber: 1.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Cinnamaldehyde inhibits intestinal alpha-glucosidase and blunts early-morning liver glucose output.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Warm Skimmed Milk with a Pinch of Grated Nutmeg (Jaiphal)',
      portionHousehold: '1 cup (140ml)',
      weightGrams: 140,
      calories: 65,
      protein: 4.2,
      fat: 1.2,
      carbs: 6.5,
      fiber: 0.2,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Myristicin in nutmeg promotes restorative non-REM slow-wave deep sleep.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Warm Cumin (Jeera) & Ajwain Infusion with Rock Salt',
      portionHousehold: '1 cup (180ml)',
      weightGrams: 180,
      calories: 12,
      protein: 0.3,
      fat: 0.1,
      carbs: 2.2,
      fiber: 0.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Thymol stimulates gastric enzymatic ease and prevents midnight reflux or gas fermentation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Ashwagandha Root & Cardamom Decoction in Lukewarm Almond Milk',
      portionHousehold: '1 cup (150ml)',
      weightGrams: 150,
      calories: 55,
      protein: 2.0,
      fat: 3.0,
      carbs: 4.5,
      fiber: 1.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Withanolides lower evening circulating cortisol, normalizing dawn fasting glycemia.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
    {
      dishName: 'Fennel Seed (Saunf) & Cardamom Water (Lukewarm)',
      portionHousehold: '1 warm glass (180ml)',
      weightGrams: 180,
      calories: 10,
      protein: 0.2,
      fat: 0.1,
      carbs: 2.0,
      fiber: 0.4,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Anethole relaxes intestinal smooth muscles, preparing digestive tract for morning evacuation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],

  hypertension: [
    {
      dishName: 'Warm Cardamom Skimmed Milk with Ground Nutmeg',
      portionHousehold: '1 cup (150ml)',
      weightGrams: 150,
      calories: 68,
      protein: 4.5,
      fat: 1.2,
      carbs: 6.8,
      fiber: 0.3,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Cardamom essential oils act as mild calcium channel blockers, gently relaxing peripheral arteries.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Hibiscus & Chamomile Relaxing Night Tisane',
      portionHousehold: '1 warm cup (180ml)',
      weightGrams: 180,
      calories: 8,
      protein: 0.1,
      fat: 0.0,
      carbs: 1.8,
      fiber: 0.2,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Flavonoid-mediated vasorelaxation prevents nocturnal surges in blood pressure.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Warm Water with 1 tsp Overnight Soaked Sabja (Sweet Basil) Seeds',
      portionHousehold: '1 glass (200ml)',
      weightGrams: 205,
      calories: 20,
      protein: 0.8,
      fat: 0.5,
      carbs: 2.5,
      fiber: 2.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'High mucilage content cools Pitta heat and reduces night-time blood pressure oscillations.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Brahmi (Bacopa monnieri) Herbal Infusion with Touch of Honey',
      portionHousehold: '1 warm cup (160ml)',
      weightGrams: 160,
      calories: 18,
      protein: 0.2,
      fat: 0.0,
      carbs: 4.0,
      fiber: 0.2,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Bacosides down-regulate central nervous system sympathetic hyperactivity.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Warm Turmeric & Garlic Infusion (Gentle Decoction)',
      portionHousehold: '1 cup (150ml)',
      weightGrams: 150,
      calories: 15,
      protein: 0.4,
      fat: 0.1,
      carbs: 2.8,
      fiber: 0.4,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Allicin and curcumin synergy sustains endothelial nitric oxide synthesis during sleep.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Fennel (Saunf) & Coriander Seed Night Water',
      portionHousehold: '1 warm glass (180ml)',
      weightGrams: 180,
      calories: 12,
      protein: 0.3,
      fat: 0.1,
      carbs: 2.2,
      fiber: 0.6,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Natural diuretic action reduces midnight cardiac preload safely.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Warm Cinnamon & Almond Milk Tisane',
      portionHousehold: '1 cup (150ml)',
      weightGrams: 150,
      calories: 50,
      protein: 1.8,
      fat: 2.8,
      carbs: 4.0,
      fiber: 0.8,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Plant magnesium provides smooth muscular arterial relaxation.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
  ],

  performance: [
    {
      dishName: 'Warm Tart Cherry Juice Infusion with Turmeric (Melatonin & Recovery Prime)',
      portionHousehold: '1 cup (180ml)',
      weightGrams: 180,
      calories: 60,
      protein: 1.0,
      fat: 0.2,
      carbs: 13.5,
      fiber: 0.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Natural phytomelatonin and anthocyanins speed eccentric myofibrillar recovery and sleep depth.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Warm A2 Cow Milk with Ashwagandha & Cardamom (Deep Sleep & Anabolic Prime)',
      portionHousehold: '1 cup (180ml)',
      weightGrams: 180,
      calories: 95,
      protein: 6.0,
      fat: 2.5,
      carbs: 8.5,
      fiber: 0.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Micellar casein delivers a sustained 7-hour amino acid stream while ashwagandha elevates testosterone.',
      isVegetarian: true,
      isEgg: false,
      isVegan: false,
      allergens: ['dairy'],
    },
    {
      dishName: 'Chamomile & Magnesium-Enriched Herbal Tisane',
      portionHousehold: '1 warm cup (200ml)',
      weightGrams: 200,
      calories: 8,
      protein: 0.2,
      fat: 0.0,
      carbs: 1.5,
      fiber: 0.1,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Optimizes central nervous system parasympathetic tone for faster HRV recovery.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Warm Spiced Almond Milk with Ground Nutmeg & Saffron Strands',
      portionHousehold: '1 cup (160ml)',
      weightGrams: 160,
      calories: 65,
      protein: 2.5,
      fat: 3.5,
      carbs: 5.0,
      fiber: 1.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Saffron crocetin improves tissue oxygen diffusion and calms post-training central fatigue.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
    {
      dishName: 'Warm Golden Turmeric Recovery Broth with Ginger & Black Pepper',
      portionHousehold: '1 cup (180ml)',
      weightGrams: 180,
      calories: 35,
      protein: 1.5,
      fat: 0.8,
      carbs: 5.0,
      fiber: 1.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Suppresses NF-kB inflammatory cascade following heavy eccentric loading.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Fennel & Ajwain Warm Night Water',
      portionHousehold: '1 glass (200ml)',
      weightGrams: 200,
      calories: 10,
      protein: 0.3,
      fat: 0.1,
      carbs: 2.0,
      fiber: 0.4,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Prevents intra-abdominal gastric distension from high daily caloric intake.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Warm Ceylon Cinnamon & Raw Honey Night Sip',
      portionHousehold: '1 cup (150ml)',
      weightGrams: 150,
      calories: 45,
      protein: 0.3,
      fat: 0.1,
      carbs: 10.5,
      fiber: 0.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Small dose of liver fructose replenishes nocturnal cerebral glycogen stores without insulin spikes.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],

  pcos: [
    {
      dishName: 'Organic Spearmint Infusion with Cinnamon (Anti-Androgen Prime)',
      portionHousehold: '1 warm cup (180ml)',
      weightGrams: 180,
      calories: 12,
      protein: 0.3,
      fat: 0.0,
      carbs: 2.5,
      fiber: 0.4,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Proven in clinical trials to lower free testosterone and elevate luteinizing hormone (LH) pulsatility.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Warm Golden Turmeric Almond Milk with Black Pepper & Cardamom',
      portionHousehold: '1 cup (160ml)',
      weightGrams: 160,
      calories: 60,
      protein: 2.2,
      fat: 3.0,
      carbs: 5.0,
      fiber: 1.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Dairy-free formulation avoids IGF-1 stimulation while suppressing ovarian inflammatory cytokines.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
    {
      dishName: 'Chamomile & Lemon Balm Restorative Tisane',
      portionHousehold: '1 warm cup (180ml)',
      weightGrams: 180,
      calories: 8,
      protein: 0.1,
      fat: 0.0,
      carbs: 1.5,
      fiber: 0.1,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Promotes deep restorative sleep, normalizing nocturnal leptin-ghrelin sensitivity.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Warm Ceylon Cinnamon & Soaked Methi Water',
      portionHousehold: '1 warm glass (180ml)',
      weightGrams: 180,
      calories: 15,
      protein: 0.5,
      fat: 0.1,
      carbs: 3.0,
      fiber: 1.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Binds cellular insulin receptors overnight to minimize hyperinsulinemia-driven ovarian steroidogenesis.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Ashwagandha & Cardamom Infused Water',
      portionHousehold: '1 warm cup (150ml)',
      weightGrams: 150,
      calories: 15,
      protein: 0.4,
      fat: 0.1,
      carbs: 2.8,
      fiber: 0.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Balances HPA (Hypothalamic-Pituitary-Adrenal) axis, preventing stress-induced cycle irregularities.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Fennel (Saunf) & Jeera Water (Lukewarm)',
      portionHousehold: '1 warm glass (180ml)',
      weightGrams: 180,
      calories: 10,
      protein: 0.2,
      fat: 0.1,
      carbs: 2.0,
      fiber: 0.4,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Relieves premenstrual water retention and balances intestinal transit.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Warm Nutmeg & Saffron Herbal Tisane',
      portionHousehold: '1 warm cup (150ml)',
      weightGrams: 150,
      calories: 10,
      protein: 0.2,
      fat: 0.1,
      carbs: 2.0,
      fiber: 0.2,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Promotes mood stability and suppresses late-night sugar cravings.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],
};

/**
 * Early Morning Mucosal Priming Drink (6:00 - 6:30 AM)
 */
const EARLY_MORNING_MASTER_BANK: Record<string, DishTemplate[]> = {
  diabetes: [
    {
      dishName: 'Warm Water (250ml) with Soaked Methi (Fenugreek) Seeds & Cinnamon',
      portionHousehold: '1 glass (250ml) + 1 tsp soaked seeds',
      weightGrams: 260,
      calories: 35,
      protein: 1.5,
      fat: 0.3,
      carbs: 5.5,
      fiber: 2.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Galactomannan mucilage primes enterocytes and slows gastric glucose uptake for the day.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Fresh Amla (Indian Gooseberry) Juice with Bitter Gourd Drops in Warm Water',
      portionHousehold: '30ml juice in 150ml water',
      weightGrams: 180,
      calories: 30,
      protein: 0.8,
      fat: 0.2,
      carbs: 6.0,
      fiber: 2.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Massive bioavailable vitamin C protects pancreatic beta-cells from oxidative damage.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],
  hypertension: [
    {
      dishName: 'Lukewarm Water with Fresh Crushed Garlic & Tender Coriander Leaves',
      portionHousehold: '1 glass (250ml) with 1 clove garlic',
      weightGrams: 255,
      calories: 20,
      protein: 0.8,
      fat: 0.1,
      carbs: 3.5,
      fiber: 1.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Allicin stimulates endothelial nitric oxide synthase right upon waking.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Lemon & Tender Basil (Tulsi) Infused Warm Water',
      portionHousehold: '1 warm glass (250ml)',
      weightGrams: 250,
      calories: 22,
      protein: 0.5,
      fat: 0.1,
      carbs: 4.5,
      fiber: 1.2,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Eugenol in holy basil exerts vasorelaxant and cardioprotective effects.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],
  performance: [
    {
      dishName: 'Tender Coconut Water (200ml) + 4 Soaked Almonds + 1 Medjool Date',
      portionHousehold: '200ml + 4 almonds + 1 date',
      weightGrams: 230,
      calories: 120,
      protein: 3.5,
      fat: 4.0,
      carbs: 18.0,
      fiber: 3.0,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Electrolytes and low-glycemic fructose hydrate muscular tissue and prime glycogen stores.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
      allergens: ['nuts'],
    },
    {
      dishName: 'Warm Water with Black Salt, Lime & Soaked Chia Seeds (Hydration Primer)',
      portionHousehold: '1 tall glass (280ml)',
      weightGrams: 285,
      calories: 45,
      protein: 1.5,
      fat: 1.5,
      carbs: 5.5,
      fiber: 3.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Hydrates systemic vascular beds and stabilizes blood volume before training.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],
  pcos: [
    {
      dishName: 'Spearmint & Ceylon Cinnamon Warm Water with 1 tsp Soaked Flaxseeds',
      portionHousehold: '1 glass (220ml)',
      weightGrams: 225,
      calories: 40,
      protein: 1.5,
      fat: 2.0,
      carbs: 3.5,
      fiber: 2.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Blunts early morning androgen pulse and stimulates basal bowel peristalsis.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
    {
      dishName: 'Lukewarm Water with 1 tsp Apple Cider Vinegar (with the Mother) & Ginger',
      portionHousehold: '1 glass (220ml)',
      weightGrams: 220,
      calories: 15,
      protein: 0.2,
      fat: 0.0,
      carbs: 2.5,
      fiber: 0.5,
      glycemicStatus: 'Low GI (<55)',
      therapeuticNote: 'Acetic acid improves insulin receptor sensitivity before the morning meal.',
      isVegetarian: true,
      isEgg: false,
      isVegan: true,
    },
  ],
};

const DAY_NAMES = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

const DAY_FOCUS_LIST = [
  'Insulin Sensitivity & Mucosal Priming',
  'Mitochondrial Density & Nitric Oxide Boost',
  'Glycogen Sparing & Endothelial Restoration',
  'Gut Microbiome Diversity & Polyphenol Load',
  'Hepatic Phase-2 Detoxification & Bile Flow',
  'Myofibrillar Anabolic Remodeling & Repair',
  'Circadian Reset & Autophagy Cleanse',
];

/**
 * Normalizes input condition name to one of the clinical domain keys
 */
export function normalizeConditionKey(condition: string): string {
  const c = condition.toLowerCase();
  if (c.includes('hyperten') || c.includes('cardio') || c.includes('heart') || c.includes('bp') || c.includes('dash')) {
    return 'hypertension';
  }
  if (c.includes('perform') || c.includes('sport') || c.includes('endurance') || c.includes('strength') || c.includes('muscle') || c.includes('fitness')) {
    return 'performance';
  }
  if (c.includes('pcos') || c.includes('pcod') || c.includes('hormon') || c.includes('thyroid')) {
    return 'pcos';
  }
  return 'diabetes'; // Comprehensive metabolic default
}

/**
 * Core clinical generator: Generates 7 completely distinct days.
 * Ensures Breakfast, Lunch, Snacks, Dinner, and Bedtime NEVER share recipes.
 */
export function generateDynamic7DayPlan(params: GeneratePlanParams): CustomDayPlan[] {
  const {
    conditionName = 'Diabetes Mellitus',
    generalInfo = {},
    calculations = {},
    targetCalories: explicitKcal,
  } = params;

  const condKey = normalizeConditionKey(conditionName);

  // Determine target calories (ICMR-NIN grounded)
  const targetKcal =
    explicitKcal ||
    calculations.tdee ||
    (generalInfo.weight ? Math.round(Number(generalInfo.weight) * 25) : 1500);

  // Calibrate calorie distribution across the day (ICMR Standard: 5% Early, 25% BF, 10% MM, 30% Lunch, 5% Eve, 20% Dinner, 5% Bedtime)
  const earlyMorningKcal = Math.round(targetKcal * 0.05);
  const breakfastKcal = Math.round(targetKcal * 0.25);
  const midMorningKcal = Math.round(targetKcal * 0.08);
  const lunchKcal = Math.round(targetKcal * 0.32);
  const eveningKcal = Math.round(targetKcal * 0.07);
  const dinnerKcal = Math.round(targetKcal * 0.19);
  const bedtimeKcal = Math.round(targetKcal * 0.04);

  const bfPool = BREAKFAST_MASTER_BANK[condKey] || BREAKFAST_MASTER_BANK.diabetes;
  const luPool = LUNCH_MASTER_BANK[condKey] || LUNCH_MASTER_BANK.diabetes;
  const snPool = SNACKS_MASTER_BANK[condKey] || SNACKS_MASTER_BANK.diabetes;
  const dnPool = DINNER_MASTER_BANK[condKey] || DINNER_MASTER_BANK.diabetes;
  const btPool = BEDTIME_MASTER_BANK[condKey] || BEDTIME_MASTER_BANK.diabetes;
  const emPool = EARLY_MORNING_MASTER_BANK[condKey] || EARLY_MORNING_MASTER_BANK.diabetes;

  // Filter for dietary preferences if specified
  const dietPref = (generalInfo as any)?.dietaryPreference;
  const isVegOnly = dietPref === 'vegetarian' || dietPref === 'vegan';
  const filterVeg = (d: DishTemplate) => (isVegOnly ? d.isVegetarian : true);

  const safeBf = bfPool.filter(filterVeg).length >= 7 ? bfPool.filter(filterVeg) : bfPool;
  const safeLu = luPool.filter(filterVeg).length >= 7 ? luPool.filter(filterVeg) : luPool;
  const safeSn = snPool.filter(filterVeg).length >= 7 ? snPool.filter(filterVeg) : snPool;
  const safeDn = dnPool.filter(filterVeg).length >= 7 ? dnPool.filter(filterVeg) : dnPool;
  const safeBt = btPool.filter(filterVeg).length >= 7 ? btPool.filter(filterVeg) : btPool;
  const safeEm = emPool.filter(filterVeg).length >= 2 ? emPool.filter(filterVeg) : emPool;

  const resultDays: CustomDayPlan[] = [];

  for (let dayIdx = 0; dayIdx < 7; dayIdx++) {
    const dayNumber = dayIdx + 1;
    const dayName = DAY_NAMES[dayIdx];
    const focus = DAY_FOCUS_LIST[dayIdx];

    // Pick DISTINCT items for each meal slot (guarantees NO reuse across meals and NO repeats on same days)
    const emItem = safeEm[dayIdx % safeEm.length];
    const bfItem = safeBf[dayIdx % safeBf.length];
    const mmItem = safeSn[dayIdx % safeSn.length];
    const luItem = safeLu[dayIdx % safeLu.length];
    const evItem = safeSn[(dayIdx + 3) % safeSn.length]; // offset so Mid-Morning & Evening snacks are different!
    const dnItem = safeDn[dayIdx % safeDn.length];
    const btItem = safeBt[dayIdx % safeBt.length];

    // Scale dish portions to match target calories proportionally
    const scaleDish = (template: DishTemplate, slotTargetKcal: number): CustomMealItem => {
      const scale = template.calories > 0 ? slotTargetKcal / template.calories : 1;
      const cals = Math.round(template.calories * scale);
      const prot = Math.round(template.protein * scale * 10) / 10;
      const fat = Math.round(template.fat * scale * 10) / 10;
      const carbs = Math.round(template.carbs * scale * 10) / 10;
      const fib = Math.round(template.fiber * scale * 10) / 10;
      const weight = Math.round(template.weightGrams * scale);

      return {
        id: `it-d${dayNumber}-${Math.random().toString(36).substring(2, 7)}`,
        dishName: template.dishName,
        portionHousehold: template.portionHousehold,
        weightGrams: weight,
        calories: cals,
        protein: prot,
        fat,
        carbs,
        fiber: fib,
        glycemicStatus: template.glycemicStatus,
        therapeuticNote: template.therapeuticNote,
      };
    };

    const slots: CustomMealSlot[] = [
      {
        slotId: `d${dayNumber}-s1`,
        slotName: 'Early Morning (Mucosal Priming)',
        time: '6:00 AM',
        frequency: 'Daily',
        targetKcal: earlyMorningKcal,
        items: [scaleDish(emItem, earlyMorningKcal)],
      },
      {
        slotId: `d${dayNumber}-s2`,
        slotName: 'Breakfast (Morning Energy & Satiety)',
        time: '8:30 AM',
        frequency: 'Daily',
        targetKcal: breakfastKcal,
        items: [scaleDish(bfItem, breakfastKcal)],
      },
      {
        slotId: `d${dayNumber}-s3`,
        slotName: 'Mid-Morning (Functional Hydration)',
        time: '11:00 AM',
        frequency: 'Daily',
        targetKcal: midMorningKcal,
        items: [scaleDish(mmItem, midMorningKcal)],
      },
      {
        slotId: `d${dayNumber}-s4`,
        slotName: 'Lunch (Midday Metabolic Plate)',
        time: '1:30 PM',
        frequency: 'Daily',
        targetKcal: lunchKcal,
        items: [scaleDish(luItem, lunchKcal)],
      },
      {
        slotId: `d${dayNumber}-s5`,
        slotName: 'Evening Snack (Cortisol Stabilizer)',
        time: '5:00 PM',
        frequency: 'Daily',
        targetKcal: eveningKcal,
        items: [scaleDish(evItem, eveningKcal)],
      },
      {
        slotId: `d${dayNumber}-s6`,
        slotName: 'Dinner (Light Restorative Meal)',
        time: '7:30 PM',
        frequency: 'Daily',
        targetKcal: dinnerKcal,
        items: [scaleDish(dnItem, dinnerKcal)],
      },
      {
        slotId: `d${dayNumber}-s7`,
        slotName: 'Bedtime (Night Tissue Recovery)',
        time: '9:30 PM',
        frequency: 'Daily',
        targetKcal: bedtimeKcal,
        items: [scaleDish(btItem, bedtimeKcal)],
      },
    ];

    resultDays.push({
      dayNumber,
      dayName,
      focus,
      targetCalories: targetKcal,
      slots,
    });
  }

  return resultDays;
}

/**
 * AI Personalized 7-Day Plan with Gemini API (calls /api/generate-dynamic-diet-plan with fallback)
 */
export async function generateAIPlanWithGemini(params: GeneratePlanParams): Promise<{
  plans: CustomDayPlan[];
  isAiGenerated: boolean;
  modelUsed?: string;
  rationale?: string;
}> {
  try {
    const response = await fetch('/api/generate-dynamic-diet-plan', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(params),
    });

    if (response.ok) {
      const data = await response.json();
      if (Array.isArray(data.plans) && data.plans.length === 7) {
        return {
          plans: data.plans,
          isAiGenerated: true,
          modelUsed: data.modelUsed || 'gemini-3.8-flash',
          rationale: data.rationale,
        };
      }
    }
  } catch (err) {
    console.warn('[AI Plan] Server endpoint unavailable, using deterministic clinical engine:', err);
  }

  // Resilient instantaneous clinical engine fallback
  const plans = generateDynamic7DayPlan(params);
  return {
    plans,
    isAiGenerated: false,
    rationale: `Dynamically calibrated via ICMR-NIN 2024 Clinical Engine for ${params.conditionName} with distinct meal categories.`,
  };
}
