/**
 * Official ICMR-NIN Indian Food Composition Tables (IFCT 2017)
 * Table 1: Proximate Principles and Dietary Fibre
 * 
 * Formula:
 * Nutrient for required quantity = (Value per 100 g × Required quantity in g) ÷ 100
 * Conversion: kcal = kJ ÷ 4.184
 * 
 * Example: Raw, milled rice (A015) — 30 g:
 * - Energy: 1491 kJ -> (1491 × 30) ÷ 100 = 447.3 kJ -> 447.3 ÷ 4.184 ≈ 107 kcal
 * - Protein: 7.94 g -> (7.94 × 30) ÷ 100 = 2.38 g
 * - Fat: 0.52 g -> (0.52 × 30) ÷ 100 = 0.16 g
 * - Dietary fibre: 2.81 g -> (2.81 × 30) ÷ 100 = 0.84 g
 * - Carbohydrate: 78.24 g -> (78.24 × 30) ÷ 100 = 23.47 g
 */

export interface IfctTable1Food {
  code: string;
  name: string;
  scientificName?: string;
  category: string;
  waterG: number;
  proteinG: number;
  ashG: number;
  fatG: number;
  fibreTotalG: number;
  fibreInsolubleG?: number;
  fibreSolubleG?: number;
  carbsG: number;
  energyKj: number;
  energyKcal: number; // Converted using kJ / 4.184
  commonAliases: string[];
}

export const IFCT_TABLE1_DATABASE: IfctTable1Food[] = [
  // ==========================================
  // A. CEREALS AND MILLETS (Pages 1 & 2)
  // ==========================================
  {
    code: 'A001',
    name: 'Amaranth seed, black (Amaranthus cruentus)',
    scientificName: 'Amaranthus cruentus',
    category: 'Cereals and Millets',
    waterG: 9.89,
    proteinG: 14.59,
    ashG: 2.78,
    fatG: 5.74,
    fibreTotalG: 7.02,
    fibreInsolubleG: 5.76,
    fibreSolubleG: 1.26,
    carbsG: 59.98,
    energyKj: 1490,
    energyKcal: Math.round(1490 / 4.184),
    commonAliases: ['amaranth black', 'rajgira black', 'ramdana']
  },
  {
    code: 'A002',
    name: 'Amaranth seed, pale brown (Amaranthus cruentus)',
    scientificName: 'Amaranthus cruentus',
    category: 'Cereals and Millets',
    waterG: 9.20,
    proteinG: 13.27,
    ashG: 3.05,
    fatG: 5.56,
    fibreTotalG: 7.47,
    fibreInsolubleG: 5.80,
    fibreSolubleG: 1.67,
    carbsG: 61.46,
    energyKj: 1489,
    energyKcal: Math.round(1489 / 4.184),
    commonAliases: ['amaranth pale brown', 'rajgira']
  },
  {
    code: 'A003',
    name: 'Bajra (Pennisetum typhoideum)',
    scientificName: 'Pennisetum typhoideum',
    category: 'Cereals and Millets',
    waterG: 8.97,
    proteinG: 10.96,
    ashG: 1.37,
    fatG: 5.43,
    fibreTotalG: 11.49,
    fibreInsolubleG: 9.14,
    fibreSolubleG: 2.34,
    carbsG: 61.78,
    energyKj: 1456,
    energyKcal: Math.round(1456 / 4.184),
    commonAliases: ['pearl millet', 'kambu', 'sajje']
  },
  {
    code: 'A004',
    name: 'Barley (Hordeum vulgare)',
    scientificName: 'Hordeum vulgare',
    category: 'Cereals and Millets',
    waterG: 9.77,
    proteinG: 10.94,
    ashG: 1.06,
    fatG: 1.30,
    fibreTotalG: 15.64,
    fibreInsolubleG: 9.98,
    fibreSolubleG: 5.66,
    carbsG: 61.29,
    energyKj: 1321,
    energyKcal: Math.round(1321 / 4.184),
    commonAliases: ['barley', 'jau']
  },
  {
    code: 'A005',
    name: 'Jowar (Sorghum vulgare)',
    scientificName: 'Sorghum vulgare',
    category: 'Cereals and Millets',
    waterG: 9.01,
    proteinG: 9.97,
    ashG: 1.39,
    fatG: 1.73,
    fibreTotalG: 10.22,
    fibreInsolubleG: 8.49,
    fibreSolubleG: 1.73,
    carbsG: 67.68,
    energyKj: 1398,
    energyKcal: Math.round(1398 / 4.184),
    commonAliases: ['sorghum', 'cholam', 'jonna']
  },
  {
    code: 'A006',
    name: 'Maize, dry (Zea mays)',
    scientificName: 'Zea mays',
    category: 'Cereals and Millets',
    waterG: 9.26,
    proteinG: 8.80,
    ashG: 1.17,
    fatG: 3.77,
    fibreTotalG: 12.24,
    fibreInsolubleG: 11.29,
    fibreSolubleG: 0.94,
    carbsG: 64.77,
    energyKj: 1398,
    energyKcal: Math.round(1398 / 4.184),
    commonAliases: ['dry corn', 'makka cholam dry']
  },
  {
    code: 'A007',
    name: 'Maize, tender, local (Zea mays)',
    scientificName: 'Zea mays',
    category: 'Cereals and Millets',
    waterG: 68.29,
    proteinG: 3.57,
    ashG: 0.38,
    fatG: 1.40,
    fibreTotalG: 3.67,
    fibreInsolubleG: 3.23,
    fibreSolubleG: 0.43,
    carbsG: 22.69,
    energyKj: 502,
    energyKcal: Math.round(502 / 4.184),
    commonAliases: ['corn tender', 'fresh corn']
  },
  {
    code: 'A008',
    name: 'Maize, tender, sweet (Zea mays)',
    scientificName: 'Zea mays',
    category: 'Cereals and Millets',
    waterG: 74.40,
    proteinG: 4.16,
    ashG: 0.36,
    fatG: 1.35,
    fibreTotalG: 3.30,
    fibreInsolubleG: 2.71,
    fibreSolubleG: 0.59,
    carbsG: 16.42,
    energyKj: 405,
    energyKcal: Math.round(405 / 4.184),
    commonAliases: ['sweet corn']
  },
  {
    code: 'A009',
    name: 'Quinoa (Chenopodium quinoa)',
    scientificName: 'Chenopodium quinoa',
    category: 'Cereals and Millets',
    waterG: 10.43,
    proteinG: 13.11,
    ashG: 2.65,
    fatG: 5.50,
    fibreTotalG: 14.66,
    fibreInsolubleG: 10.21,
    fibreSolubleG: 4.46,
    carbsG: 53.65,
    energyKj: 1374,
    energyKcal: Math.round(1374 / 4.184),
    commonAliases: ['quinoa']
  },
  {
    code: 'A010',
    name: 'Ragi (Eleusine coracana)',
    scientificName: 'Eleusine coracana',
    category: 'Cereals and Millets',
    waterG: 10.89,
    proteinG: 7.16,
    ashG: 2.04,
    fatG: 1.92,
    fibreTotalG: 11.18,
    fibreInsolubleG: 9.51,
    fibreSolubleG: 1.67,
    carbsG: 66.82,
    energyKj: 1342,
    energyKcal: Math.round(1342 / 4.184),
    commonAliases: ['finger millet', 'nachni', 'kezhvaragu']
  },
  {
    code: 'A011',
    name: 'Rice flakes (Oryza sativa)',
    scientificName: 'Oryza sativa',
    category: 'Cereals and Millets',
    waterG: 10.36,
    proteinG: 7.44,
    ashG: 0.85,
    fatG: 1.14,
    fibreTotalG: 3.46,
    fibreInsolubleG: 2.65,
    fibreSolubleG: 0.81,
    carbsG: 76.75,
    energyKj: 1480,
    energyKcal: Math.round(1480 / 4.184),
    commonAliases: ['poha', 'aval', 'flattened rice']
  },
  {
    code: 'A012',
    name: 'Rice puffed (Oryza sativa)',
    scientificName: 'Oryza sativa',
    category: 'Cereals and Millets',
    waterG: 9.40,
    proteinG: 7.47,
    ashG: 1.28,
    fatG: 1.62,
    fibreTotalG: 2.56,
    fibreInsolubleG: 1.76,
    fibreSolubleG: 0.80,
    carbsG: 77.68,
    energyKj: 1514,
    energyKcal: Math.round(1514 / 4.184),
    commonAliases: ['murmura', 'pori', 'puffed rice']
  },
  {
    code: 'A013',
    name: 'Rice, raw, brown (Oryza sativa)',
    scientificName: 'Oryza sativa',
    category: 'Cereals and Millets',
    waterG: 9.33,
    proteinG: 9.16,
    ashG: 1.04,
    fatG: 1.24,
    fibreTotalG: 4.43,
    fibreInsolubleG: 3.60,
    fibreSolubleG: 0.82,
    carbsG: 74.80,
    energyKj: 1480,
    energyKcal: Math.round(1480 / 4.184),
    commonAliases: ['brown rice', 'kai kuthal arisi']
  },
  {
    code: 'A014',
    name: 'Rice, parboiled, milled (Oryza sativa)',
    scientificName: 'Oryza sativa',
    category: 'Cereals and Millets',
    waterG: 10.09,
    proteinG: 7.81,
    ashG: 0.65,
    fatG: 0.55,
    fibreTotalG: 3.74,
    fibreInsolubleG: 2.98,
    fibreSolubleG: 0.76,
    carbsG: 77.16,
    energyKj: 1471,
    energyKcal: Math.round(1471 / 4.184),
    commonAliases: ['parboiled rice', 'puzhungal arisi']
  },
  {
    code: 'A015',
    name: 'Rice, raw, milled (Oryza sativa)',
    scientificName: 'Oryza sativa',
    category: 'Cereals and Millets',
    waterG: 9.93,
    proteinG: 7.94,
    ashG: 0.56,
    fatG: 0.52,
    fibreTotalG: 2.81,
    fibreInsolubleG: 1.99,
    fibreSolubleG: 0.82,
    carbsG: 78.24,
    energyKj: 1491,
    energyKcal: Math.round(1491 / 4.184), // 356.36 kcal / 100g, for 30g = 106.9 ≈ 107 kcal
    commonAliases: ['raw rice', 'pacharisi', 'white rice', 'milled rice', 'chawal']
  },
  {
    code: 'A016',
    name: 'Samai (Panicum miliare)',
    scientificName: 'Panicum miliare',
    category: 'Cereals and Millets',
    waterG: 11.36,
    proteinG: 10.13,
    ashG: 1.34,
    fatG: 3.89,
    fibreTotalG: 7.72,
    fibreInsolubleG: 5.45,
    fibreSolubleG: 2.27,
    carbsG: 65.55,
    energyKj: 1449,
    energyKcal: Math.round(1449 / 4.184),
    commonAliases: ['little millet', 'samai', 'sama']
  },
  {
    code: 'A017',
    name: 'Varagu (Paspalum scrobiculatum)',
    scientificName: 'Paspalum scrobiculatum',
    category: 'Cereals and Millets',
    waterG: 14.23,
    proteinG: 8.92,
    ashG: 1.72,
    fatG: 2.55,
    fibreTotalG: 6.39,
    fibreInsolubleG: 4.29,
    fibreSolubleG: 2.11,
    carbsG: 66.19,
    energyKj: 1388,
    energyKcal: Math.round(1388 / 4.184),
    commonAliases: ['kodo millet', 'varagu', 'kodra']
  },
  {
    code: 'A018',
    name: 'Wheat flour, refined (Triticum aestivum)',
    scientificName: 'Triticum aestivum',
    category: 'Cereals and Millets',
    waterG: 11.34,
    proteinG: 10.36,
    ashG: 0.51,
    fatG: 0.76,
    fibreTotalG: 2.76,
    fibreInsolubleG: 2.14,
    fibreSolubleG: 0.62,
    carbsG: 74.27,
    energyKj: 1472,
    energyKcal: Math.round(1472 / 4.184),
    commonAliases: ['maida', 'refined wheat flour']
  },
  {
    code: 'A019',
    name: 'Wheat flour, atta (Triticum aestivum)',
    scientificName: 'Triticum aestivum',
    category: 'Cereals and Millets',
    waterG: 11.10,
    proteinG: 10.57,
    ashG: 1.28,
    fatG: 1.53,
    fibreTotalG: 11.36,
    fibreInsolubleG: 9.73,
    fibreSolubleG: 1.63,
    carbsG: 64.17,
    energyKj: 1340,
    energyKcal: Math.round(1340 / 4.184),
    commonAliases: ['atta', 'wheat flour', 'gehun atta', 'godhumai']
  },
  {
    code: 'A020',
    name: 'Wheat, whole (Triticum aestivum)',
    scientificName: 'Triticum aestivum',
    category: 'Cereals and Millets',
    waterG: 10.58,
    proteinG: 10.59,
    ashG: 1.42,
    fatG: 1.47,
    fibreTotalG: 11.23,
    fibreInsolubleG: 9.63,
    fibreSolubleG: 1.60,
    carbsG: 64.72,
    energyKj: 1347,
    energyKcal: Math.round(1347 / 4.184),
    commonAliases: ['whole wheat', 'gehun whole']
  },
  {
    code: 'A021',
    name: 'Wheat, bulgur (Triticum aestivum)',
    scientificName: 'Triticum aestivum',
    category: 'Cereals and Millets',
    waterG: 8.61,
    proteinG: 10.84,
    ashG: 1.23,
    fatG: 1.45,
    fibreTotalG: 8.81,
    fibreInsolubleG: 6.56,
    fibreSolubleG: 2.25,
    carbsG: 69.06,
    energyKj: 1430,
    energyKcal: Math.round(1430 / 4.184),
    commonAliases: ['dalia', 'broken wheat', 'bulgur']
  },
  {
    code: 'A022',
    name: 'Wheat, semolina (Triticum aestivum)',
    scientificName: 'Triticum aestivum',
    category: 'Cereals and Millets',
    waterG: 8.94,
    proteinG: 11.38,
    ashG: 0.80,
    fatG: 0.74,
    fibreTotalG: 9.72,
    fibreInsolubleG: 8.16,
    fibreSolubleG: 1.55,
    carbsG: 68.43,
    energyKj: 1396,
    energyKcal: Math.round(1396 / 4.184),
    commonAliases: ['rava', 'sooji', 'semolina']
  },
  {
    code: 'A023',
    name: 'Wheat, vermicelli (Triticum aestivum)',
    scientificName: 'Triticum aestivum',
    category: 'Cereals and Millets',
    waterG: 9.59,
    proteinG: 9.70,
    ashG: 0.60,
    fatG: 0.45,
    fibreTotalG: 9.28,
    fibreInsolubleG: 7.53,
    fibreSolubleG: 1.75,
    carbsG: 70.39,
    energyKj: 1392,
    energyKcal: Math.round(1392 / 4.184),
    commonAliases: ['semiya', 'vermicelli']
  },
  {
    code: 'A024',
    name: 'Wheat, vermicelli, roasted (Triticum aestivum)',
    scientificName: 'Triticum aestivum',
    category: 'Cereals and Millets',
    waterG: 7.61,
    proteinG: 10.37,
    ashG: 0.56,
    fatG: 0.49,
    fibreTotalG: 9.55,
    fibreInsolubleG: 7.79,
    fibreSolubleG: 1.76,
    carbsG: 71.42,
    energyKj: 1423,
    energyKcal: Math.round(1423 / 4.184),
    commonAliases: ['roasted semiya', 'roasted vermicelli']
  },

  // ==========================================
  // B. GRAIN LEGUMES & PULSES (Pages 2 & 3)
  // ==========================================
  {
    code: 'B001',
    name: 'Bengal gram, dal (Cicer arietinum)',
    scientificName: 'Cicer arietinum',
    category: 'Grain Legumes',
    waterG: 9.18,
    proteinG: 21.55,
    ashG: 2.10,
    fatG: 5.31,
    fibreTotalG: 15.15,
    fibreInsolubleG: 12.67,
    fibreSolubleG: 2.48,
    carbsG: 46.72,
    energyKj: 1377,
    energyKcal: Math.round(1377 / 4.184),
    commonAliases: ['chana dal', 'kadalai paruppu', 'bengal gram split']
  },
  {
    code: 'B002',
    name: 'Bengal gram, whole (Cicer arietinum)',
    scientificName: 'Cicer arietinum',
    category: 'Grain Legumes',
    waterG: 8.56,
    proteinG: 18.77,
    ashG: 2.78,
    fatG: 5.11,
    fibreTotalG: 25.22,
    fibreInsolubleG: 22.70,
    fibreSolubleG: 2.52,
    carbsG: 39.56,
    energyKj: 1201,
    energyKcal: Math.round(1201 / 4.184),
    commonAliases: ['kala chana', 'black chickpea', 'whole chickpea']
  },
  {
    code: 'B003',
    name: 'Black gram, dal (Phaseolus mungo)',
    scientificName: 'Phaseolus mungo',
    category: 'Grain Legumes',
    waterG: 9.16,
    proteinG: 23.06,
    ashG: 3.17,
    fatG: 1.69,
    fibreTotalG: 11.93,
    fibreInsolubleG: 7.58,
    fibreSolubleG: 4.35,
    carbsG: 51.00,
    energyKj: 1356,
    energyKcal: Math.round(1356 / 4.184),
    commonAliases: ['urad dal', 'ulutham paruppu', 'split black gram']
  },
  {
    code: 'B004',
    name: 'Black gram, whole (Phaseolus mungo)',
    scientificName: 'Phaseolus mungo',
    category: 'Grain Legumes',
    waterG: 8.70,
    proteinG: 21.97,
    ashG: 3.35,
    fatG: 1.58,
    fibreTotalG: 20.41,
    fibreInsolubleG: 15.47,
    fibreSolubleG: 4.94,
    carbsG: 43.99,
    energyKj: 1219,
    energyKcal: Math.round(1219 / 4.184),
    commonAliases: ['whole urad', 'karuppu ulundhu', 'whole black gram']
  },
  {
    code: 'B005',
    name: 'Cowpea, brown (Vigna catjang)',
    scientificName: 'Vigna catjang',
    category: 'Grain Legumes',
    waterG: 9.42,
    proteinG: 20.36,
    ashG: 2.90,
    fatG: 1.15,
    fibreTotalG: 11.54,
    fibreInsolubleG: 8.75,
    fibreSolubleG: 2.80,
    carbsG: 54.62,
    energyKj: 1340,
    energyKcal: Math.round(1340 / 4.184),
    commonAliases: ['karamani brown', 'lobia brown']
  },
  {
    code: 'B006',
    name: 'Cowpea, white (Vigna catjang)',
    scientificName: 'Vigna catjang',
    category: 'Grain Legumes',
    waterG: 9.32,
    proteinG: 21.25,
    ashG: 2.83,
    fatG: 1.14,
    fibreTotalG: 11.70,
    fibreInsolubleG: 8.91,
    fibreSolubleG: 2.79,
    carbsG: 53.77,
    energyKj: 1340,
    energyKcal: Math.round(1340 / 4.184),
    commonAliases: ['karamani white', 'lobia white']
  },
  {
    code: 'B010',
    name: 'Green gram, dal (Vigna radiata)',
    scientificName: 'Vigna radiata',
    category: 'Grain Legumes',
    waterG: 9.77,
    proteinG: 23.88,
    ashG: 3.04,
    fatG: 1.35,
    fibreTotalG: 9.37,
    fibreInsolubleG: 7.75,
    fibreSolubleG: 1.62,
    carbsG: 52.59,
    energyKj: 1363,
    energyKcal: Math.round(1363 / 4.184),
    commonAliases: ['moong dal', 'pasi paruppu', 'split green gram']
  },
  {
    code: 'B011',
    name: 'Green gram, whole (Vigna radiata)',
    scientificName: 'Vigna radiata',
    category: 'Grain Legumes',
    waterG: 9.95,
    proteinG: 22.53,
    ashG: 3.22,
    fatG: 1.14,
    fibreTotalG: 17.04,
    fibreInsolubleG: 14.59,
    fibreSolubleG: 2.44,
    carbsG: 46.13,
    energyKj: 1229,
    energyKcal: Math.round(1229 / 4.184),
    commonAliases: ['whole moong', 'pacha payaru', 'green gram whole']
  },
  {
    code: 'B014',
    name: 'Lentil whole, brown (Lens culinaris)',
    scientificName: 'Lens culinaris',
    category: 'Grain Legumes',
    waterG: 9.20,
    proteinG: 22.49,
    ashG: 2.39,
    fatG: 0.64,
    fibreTotalG: 16.82,
    fibreInsolubleG: 14.16,
    fibreSolubleG: 2.66,
    carbsG: 48.47,
    energyKj: 1251,
    energyKcal: Math.round(1251 / 4.184),
    commonAliases: ['masoor whole', 'brown lentil']
  },
  {
    code: 'B017',
    name: 'Peas, dry (Pisum sativum)',
    scientificName: 'Pisum sativum',
    category: 'Grain Legumes',
    waterG: 9.33,
    proteinG: 20.43,
    ashG: 2.41,
    fatG: 1.89,
    fibreTotalG: 17.01,
    fibreInsolubleG: 14.55,
    fibreSolubleG: 2.47,
    carbsG: 48.93,
    energyKj: 1269,
    energyKcal: Math.round(1269 / 4.184),
    commonAliases: ['pattani dry', 'dry peas', 'matar dry']
  },
  {
    code: 'B019',
    name: 'Rajmah, brown (Phaseolus vulgaris)',
    scientificName: 'Phaseolus vulgaris',
    category: 'Grain Legumes',
    waterG: 9.68,
    proteinG: 19.50,
    ashG: 3.36,
    fatG: 1.68,
    fibreTotalG: 16.95,
    fibreInsolubleG: 14.33,
    fibreSolubleG: 2.62,
    carbsG: 48.83,
    energyKj: 1245,
    energyKcal: Math.round(1245 / 4.184),
    commonAliases: ['rajma brown', 'kidney bean brown']
  },
  {
    code: 'B020',
    name: 'Rajmah, red (Phaseolus vulgaris)',
    scientificName: 'Phaseolus vulgaris',
    category: 'Grain Legumes',
    waterG: 9.87,
    proteinG: 19.91,
    ashG: 3.28,
    fatG: 1.77,
    fibreTotalG: 16.57,
    fibreInsolubleG: 13.86,
    fibreSolubleG: 2.70,
    carbsG: 48.61,
    energyKj: 1252,
    energyKcal: Math.round(1252 / 4.184),
    commonAliases: ['rajma red', 'red kidney bean']
  },
  {
    code: 'B021',
    name: 'Red gram, dal (Cajanus cajan)',
    scientificName: 'Cajanus cajan',
    category: 'Grain Legumes',
    waterG: 9.20,
    proteinG: 21.70,
    ashG: 3.26,
    fatG: 1.56,
    fibreTotalG: 9.06,
    fibreInsolubleG: 6.67,
    fibreSolubleG: 2.39,
    carbsG: 55.23,
    energyKj: 1384,
    energyKcal: Math.round(1384 / 4.184),
    commonAliases: ['toor dal', 'tuvar dal', 'thuvaram paruppu', 'pigeon pea']
  },
  {
    code: 'B024',
    name: 'Soybean, brown (Glycine max)',
    scientificName: 'Glycine max',
    category: 'Grain Legumes',
    waterG: 5.51,
    proteinG: 35.58,
    ashG: 4.74,
    fatG: 19.82,
    fibreTotalG: 21.55,
    fibreInsolubleG: 16.56,
    fibreSolubleG: 5.00,
    carbsG: 12.79,
    energyKj: 1596,
    energyKcal: Math.round(1596 / 4.184),
    commonAliases: ['soybean brown', 'soya bean']
  },
  {
    code: 'B025',
    name: 'Soybean, white (Glycine max)',
    scientificName: 'Glycine max',
    category: 'Grain Legumes',
    waterG: 5.47,
    proteinG: 37.80,
    ashG: 4.52,
    fatG: 19.42,
    fibreTotalG: 22.63,
    fibreInsolubleG: 17.04,
    fibreSolubleG: 5.59,
    carbsG: 10.16,
    energyKj: 1579,
    energyKcal: Math.round(1579 / 4.184),
    commonAliases: ['soybean white']
  },

  // ==========================================
  // C. GREEN LEAFY VEGETABLES (Pages 3, 4, 5)
  // ==========================================
  {
    code: 'C001',
    name: 'Agathi leaves (Sesbania grandiflora)',
    scientificName: 'Sesbania grandiflora',
    category: 'Green Leafy Vegetables',
    waterG: 74.43,
    proteinG: 8.01,
    ashG: 2.42,
    fatG: 1.35,
    fibreTotalG: 8.60,
    fibreInsolubleG: 6.00,
    fibreSolubleG: 2.60,
    carbsG: 5.21,
    energyKj: 295,
    energyKcal: Math.round(295 / 4.184),
    commonAliases: ['agathi keerai', 'sesbania leaves']
  },
  {
    code: 'C002',
    name: 'Amaranth leaves, green (Amaranthus gangeticus)',
    scientificName: 'Amaranthus gangeticus',
    category: 'Green Leafy Vegetables',
    waterG: 86.85,
    proteinG: 3.29,
    ashG: 2.52,
    fatG: 0.65,
    fibreTotalG: 4.41,
    fibreInsolubleG: 3.21,
    fibreSolubleG: 1.20,
    carbsG: 2.28,
    energyKj: 128,
    energyKcal: Math.round(128 / 4.184),
    commonAliases: ['thandu keerai', 'green amaranth leaves', 'chaulai green']
  },
  {
    code: 'C003',
    name: 'Amaranth leaves, red (Amaranthus gangeticus)',
    scientificName: 'Amaranthus gangeticus',
    category: 'Green Leafy Vegetables',
    waterG: 85.56,
    proteinG: 3.93,
    ashG: 2.61,
    fatG: 0.63,
    fibreTotalG: 4.91,
    fibreInsolubleG: 3.72,
    fibreSolubleG: 1.19,
    carbsG: 2.37,
    energyKj: 140,
    energyKcal: Math.round(140 / 4.184),
    commonAliases: ['red amaranth leaves', 'sivappu keerai', 'chaulai red']
  },
  {
    code: 'C015',
    name: 'Cabbage, green (Brassica oleracea var. capitata f. alba)',
    scientificName: 'Brassica oleracea',
    category: 'Green Leafy Vegetables',
    waterG: 91.85,
    proteinG: 1.36,
    ashG: 0.67,
    fatG: 0.12,
    fibreTotalG: 2.76,
    fibreInsolubleG: 1.91,
    fibreSolubleG: 0.85,
    carbsG: 3.25,
    energyKj: 90,
    energyKcal: Math.round(90 / 4.184),
    commonAliases: ['cabbage green', 'patta gobhi', 'muttakos']
  },
  {
    code: 'C019',
    name: 'Drumstick leaves (Moringa oleifera)',
    scientificName: 'Moringa oleifera',
    category: 'Green Leafy Vegetables',
    waterG: 75.65,
    proteinG: 6.41,
    ashG: 2.46,
    fatG: 1.64,
    fibreTotalG: 8.21,
    fibreInsolubleG: 6.12,
    fibreSolubleG: 2.10,
    carbsG: 5.62,
    energyKj: 282,
    energyKcal: Math.round(282 / 4.184),
    commonAliases: ['moringa leaves', 'murungai keerai', 'drumstick leaves']
  },
  {
    code: 'C020',
    name: 'Fenugreek leaves (Trigonella foenum graecum)',
    scientificName: 'Trigonella foenum graecum',
    category: 'Green Leafy Vegetables',
    waterG: 86.73,
    proteinG: 3.68,
    ashG: 1.69,
    fatG: 0.83,
    fibreTotalG: 4.90,
    fibreInsolubleG: 3.20,
    fibreSolubleG: 1.70,
    carbsG: 2.17,
    energyKj: 144,
    energyKcal: Math.round(144 / 4.184),
    commonAliases: ['methi leaves', 'vendhaya keerai']
  },
  {
    code: 'C025',
    name: 'Lettuce (Lactuca sativa)',
    scientificName: 'Lactuca sativa',
    category: 'Green Leafy Vegetables',
    waterG: 92.27,
    proteinG: 1.54,
    ashG: 1.11,
    fatG: 0.27,
    fibreTotalG: 1.79,
    fibreInsolubleG: 1.32,
    fibreSolubleG: 0.47,
    carbsG: 3.01,
    energyKj: 91,
    energyKcal: Math.round(91 / 4.184),
    commonAliases: ['lettuce', 'salad leaf']
  },
  {
    code: 'C026',
    name: 'Mustard leaves (Brassica juncea)',
    scientificName: 'Brassica juncea',
    category: 'Green Leafy Vegetables',
    waterG: 88.17,
    proteinG: 3.52,
    ashG: 1.47,
    fatG: 0.51,
    fibreTotalG: 3.92,
    fibreInsolubleG: 3.04,
    fibreSolubleG: 0.87,
    carbsG: 2.41,
    energyKj: 127,
    energyKcal: Math.round(127 / 4.184),
    commonAliases: ['sarson saag', 'mustard leaves']
  },
  {
    code: 'C029',
    name: 'Ponnaganni (Alternanthera sessilis)',
    scientificName: 'Alternanthera sessilis',
    category: 'Green Leafy Vegetables',
    waterG: 79.43,
    proteinG: 5.29,
    ashG: 2.65,
    fatG: 0.71,
    fibreTotalG: 6.74,
    fibreInsolubleG: 5.63,
    fibreSolubleG: 1.11,
    carbsG: 5.17,
    energyKj: 213,
    energyKcal: Math.round(213 / 4.184),
    commonAliases: ['ponnanganni keerai']
  },
  {
    code: 'C033',
    name: 'Spinach (Spinacia oleracea)',
    scientificName: 'Spinacia oleracea',
    category: 'Green Leafy Vegetables',
    waterG: 90.31,
    proteinG: 2.14,
    ashG: 2.47,
    fatG: 0.64,
    fibreTotalG: 2.38,
    fibreInsolubleG: 1.52,
    fibreSolubleG: 0.86,
    carbsG: 2.05,
    energyKj: 102,
    energyKcal: Math.round(102 / 4.184),
    commonAliases: ['palak', 'pasalai keerai', 'spinach']
  },

  // ==========================================
  // D. OTHER VEGETABLES (Pages 5, 6, 7)
  // ==========================================
  {
    code: 'D001',
    name: 'Ash gourd (Benincasa hispida)',
    scientificName: 'Benincasa hispida',
    category: 'Other Vegetables',
    waterG: 92.17,
    proteinG: 0.79,
    ashG: 0.70,
    fatG: 0.14,
    fibreTotalG: 3.37,
    fibreInsolubleG: 2.52,
    fibreSolubleG: 0.85,
    carbsG: 2.84,
    energyKj: 73,
    energyKcal: Math.round(73 / 4.184),
    commonAliases: ['ash gourd', 'winter melon', 'poosanikai', 'petha']
  },
  {
    code: 'D004',
    name: 'Bitter gourd (Momordica charantia)',
    scientificName: 'Momordica charantia',
    category: 'Other Vegetables',
    waterG: 90.87,
    proteinG: 1.44,
    ashG: 0.86,
    fatG: 0.24,
    fibreTotalG: 3.78,
    fibreInsolubleG: 3.10,
    fibreSolubleG: 0.68,
    carbsG: 2.82,
    energyKj: 87,
    energyKcal: Math.round(87 / 4.184),
    commonAliases: ['karela', 'pavakkai', 'bitter melon']
  },
  {
    code: 'D007',
    name: 'Bottle gourd (Lagenaria vulgaris)',
    scientificName: 'Lagenaria vulgaris',
    category: 'Other Vegetables',
    waterG: 95.17,
    proteinG: 0.53,
    ashG: 0.36,
    fatG: 0.13,
    fibreTotalG: 2.12,
    fibreInsolubleG: 1.65,
    fibreSolubleG: 0.48,
    carbsG: 1.68,
    energyKj: 46,
    energyKcal: Math.round(46 / 4.184),
    commonAliases: ['lauki', 'sorakkai', 'bottle gourd']
  },
  {
    code: 'D010',
    name: 'Brinjal (Solanum melongena)',
    scientificName: 'Solanum melongena',
    category: 'Other Vegetables',
    waterG: 89.95,
    proteinG: 1.77,
    ashG: 0.83,
    fatG: 0.39,
    fibreTotalG: 3.57,
    fibreInsolubleG: 2.37,
    fibreSolubleG: 1.20,
    carbsG: 3.49,
    energyKj: 114,
    energyKcal: Math.round(114 / 4.184),
    commonAliases: ['eggplant', 'kathirikai', 'baingan', 'aubergine']
  },
  {
    code: 'D034',
    name: 'Capsicum, red (Capsicum annuum)',
    scientificName: 'Capsicum annuum',
    category: 'Other Vegetables',
    waterG: 92.99,
    proteinG: 1.47,
    ashG: 0.76,
    fatG: 0.47,
    fibreTotalG: 2.19,
    fibreInsolubleG: 1.58,
    fibreSolubleG: 0.61,
    carbsG: 2.14,
    energyKj: 83,
    energyKcal: Math.round(83 / 4.184),
    commonAliases: ['red bell pepper', 'red capsicum', 'kudai milagai red']
  },
  {
    code: 'D036',
    name: 'Cauliflower (Brassica oleracea var. botrytis)',
    scientificName: 'Brassica oleracea',
    category: 'Other Vegetables',
    waterG: 90.76,
    proteinG: 2.15,
    ashG: 0.91,
    fatG: 0.44,
    fibreTotalG: 3.71,
    fibreInsolubleG: 2.66,
    fibreSolubleG: 1.04,
    carbsG: 2.03,
    energyKj: 96,
    energyKcal: Math.round(96 / 4.184),
    commonAliases: ['cauliflower', 'gobi flower']
  },
  {
    code: 'D039',
    name: 'Cluster beans (Cyamopsis tetragonoloba)',
    scientificName: 'Cyamopsis tetragonoloba',
    category: 'Other Vegetables',
    waterG: 84.65,
    proteinG: 3.55,
    ashG: 1.68,
    fatG: 0.37,
    fibreTotalG: 4.83,
    fibreInsolubleG: 3.55,
    fibreSolubleG: 1.28,
    carbsG: 4.91,
    energyKj: 168,
    energyKcal: Math.round(168 / 4.184),
    commonAliases: ['kothavarangai', 'guar phali', 'cluster beans']
  },
  {
    code: 'D043',
    name: 'Cucumber, green (Cucumis sativus)',
    scientificName: 'Cucumis sativus',
    category: 'Other Vegetables',
    waterG: 92.96,
    proteinG: 0.71,
    ashG: 0.54,
    fatG: 0.16,
    fibreTotalG: 2.14,
    fibreInsolubleG: 1.52,
    fibreSolubleG: 0.63,
    carbsG: 3.48,
    energyKj: 82,
    energyKcal: Math.round(82 / 4.184),
    commonAliases: ['cucumber', 'kheera', 'vellarikkai']
  },
  {
    code: 'D046',
    name: 'Drumstick (Moringa oleifera)',
    scientificName: 'Moringa oleifera',
    category: 'Other Vegetables',
    waterG: 85.39,
    proteinG: 2.62,
    ashG: 1.27,
    fatG: 0.12,
    fibreTotalG: 6.83,
    fibreInsolubleG: 5.60,
    fibreSolubleG: 1.23,
    carbsG: 3.76,
    energyKj: 123,
    energyKcal: Math.round(123 / 4.184),
    commonAliases: ['murungakkai', 'moringa pod', 'drumstick']
  },
  {
    code: 'D049',
    name: 'French beans (Phaseolus vulgaris)',
    scientificName: 'Phaseolus vulgaris',
    category: 'Other Vegetables',
    waterG: 89.14,
    proteinG: 2.49,
    ashG: 1.05,
    fatG: 0.26,
    fibreTotalG: 4.38,
    fibreInsolubleG: 3.88,
    fibreSolubleG: 0.51,
    carbsG: 2.68,
    energyKj: 102,
    energyKcal: Math.round(102 / 4.184),
    commonAliases: ['french beans', 'green beans', 'beans']
  },
  {
    code: 'D056',
    name: 'Ladies finger (Abelmoschus esculentus)',
    scientificName: 'Abelmoschus esculentus',
    category: 'Other Vegetables',
    waterG: 89.06,
    proteinG: 2.08,
    ashG: 0.94,
    fatG: 0.22,
    fibreTotalG: 4.08,
    fibreInsolubleG: 2.80,
    fibreSolubleG: 1.28,
    carbsG: 3.62,
    energyKj: 115,
    energyKcal: Math.round(115 / 4.184),
    commonAliases: ['bhindi', 'okra', 'vendakkai', 'ladies finger']
  },
  {
    code: 'D061',
    name: 'Peas, fresh (Pisum sativum)',
    scientificName: 'Pisum sativum',
    category: 'Other Vegetables',
    waterG: 73.37,
    proteinG: 7.25,
    ashG: 1.05,
    fatG: 0.13,
    fibreTotalG: 6.32,
    fibreInsolubleG: 5.04,
    fibreSolubleG: 1.28,
    carbsG: 11.88,
    energyKj: 340,
    energyKcal: Math.round(340 / 4.184),
    commonAliases: ['fresh matar', 'pachai pattani', 'green peas fresh']
  },
  {
    code: 'D068',
    name: 'Ridge gourd (Luffa acutangula)',
    scientificName: 'Luffa acutangula',
    category: 'Other Vegetables',
    waterG: 94.99,
    proteinG: 0.91,
    ashG: 0.44,
    fatG: 0.14,
    fibreTotalG: 1.81,
    fibreInsolubleG: 1.20,
    fibreSolubleG: 0.61,
    carbsG: 1.72,
    energyKj: 55,
    energyKcal: Math.round(55 / 4.184),
    commonAliases: ['turai', 'peerkangai', 'ridge gourd']
  },
  {
    code: 'D070',
    name: 'Snake gourd (Trichosanthes anguina)',
    scientificName: 'Trichosanthes anguina',
    category: 'Other Vegetables',
    waterG: 94.81,
    proteinG: 0.98,
    ashG: 0.42,
    fatG: 0.25,
    fibreTotalG: 2.27,
    fibreInsolubleG: 1.69,
    fibreSolubleG: 0.58,
    carbsG: 1.27,
    energyKj: 52,
    energyKcal: Math.round(52 / 4.184),
    commonAliases: ['chichinda', 'podalangai', 'snake gourd']
  },
  {
    code: 'D076',
    name: 'Tomato, ripe, local (Lycopersicon esculentum)',
    scientificName: 'Lycopersicon esculentum',
    category: 'Other Vegetables',
    waterG: 93.62,
    proteinG: 0.90,
    ashG: 0.52,
    fatG: 0.47,
    fibreTotalG: 1.77,
    fibreInsolubleG: 1.44,
    fibreSolubleG: 0.33,
    carbsG: 2.71,
    energyKj: 82,
    energyKcal: Math.round(82 / 4.184),
    commonAliases: ['tomato', 'thakkali', 'tamatar']
  },

  // ==========================================
  // E. FRUITS (Pages 8, 9, 10, 11)
  // ==========================================
  {
    code: 'E001',
    name: 'Apple, big (Malus domestica)',
    scientificName: 'Malus domestica',
    category: 'Fruits',
    waterG: 83.01,
    proteinG: 0.29,
    ashG: 0.36,
    fatG: 0.64,
    fibreTotalG: 2.59,
    fibreInsolubleG: 1.43,
    fibreSolubleG: 1.16,
    carbsG: 13.11,
    energyKj: 261,
    energyKcal: Math.round(261 / 4.184),
    commonAliases: ['apple', 'seb', 'red apple']
  },
  {
    code: 'E007',
    name: 'Avocado fruit (Persea sp.)',
    scientificName: 'Persea americana',
    category: 'Fruits',
    waterG: 73.56,
    proteinG: 2.95,
    ashG: 1.19,
    fatG: 13.86,
    fibreTotalG: 6.69,
    fibreInsolubleG: 5.26,
    fibreSolubleG: 1.42,
    carbsG: 1.75,
    energyKj: 604,
    energyKcal: Math.round(604 / 4.184),
    commonAliases: ['avocado', 'butter fruit']
  },
  {
    code: 'E010',
    name: 'Banana, ripe, poovam (Musa x paradisiaca)',
    scientificName: 'Musa paradisiaca',
    category: 'Fruits',
    waterG: 71.32,
    proteinG: 1.49,
    ashG: 1.09,
    fatG: 0.35,
    fibreTotalG: 2.33,
    fibreInsolubleG: 1.29,
    fibreSolubleG: 1.04,
    carbsG: 23.41,
    energyKj: 445,
    energyKcal: Math.round(445 / 4.184),
    commonAliases: ['banana poovam', 'kela', 'vazhaipazham']
  },
  {
    code: 'E012',
    name: 'Banana, ripe, robusta (Musa x paradisiaca)',
    scientificName: 'Musa paradisiaca',
    category: 'Fruits',
    waterG: 71.93,
    proteinG: 1.23,
    ashG: 0.94,
    fatG: 0.33,
    fibreTotalG: 1.94,
    fibreInsolubleG: 1.23,
    fibreSolubleG: 0.71,
    carbsG: 23.63,
    energyKj: 440,
    energyKcal: Math.round(440 / 4.184),
    commonAliases: ['robusta banana', 'green banana ripe']
  },
  {
    code: 'E017',
    name: 'Dates, dry, pale brown (Phoenix dactylifera)',
    scientificName: 'Phoenix dactylifera',
    category: 'Fruits',
    waterG: 11.14,
    proteinG: 2.45,
    ashG: 2.20,
    fatG: 0.35,
    fibreTotalG: 8.95,
    fibreInsolubleG: 7.53,
    fibreSolubleG: 1.42,
    carbsG: 74.91,
    energyKj: 1340,
    energyKcal: Math.round(1340 / 4.184),
    commonAliases: ['dry dates', 'khajoor', 'pericham pazham']
  },
  {
    code: 'E021',
    name: 'Gooseberry (Emblica officinalis)',
    scientificName: 'Emblica officinalis',
    category: 'Fruits',
    waterG: 87.02,
    proteinG: 0.34,
    ashG: 0.34,
    fatG: 0.16,
    fibreTotalG: 7.75,
    fibreInsolubleG: 6.20,
    fibreSolubleG: 1.55,
    carbsG: 4.39,
    energyKj: 99,
    energyKcal: Math.round(99 / 4.184),
    commonAliases: ['amla', 'nellikkai', 'indian gooseberry']
  },
  {
    code: 'E028',
    name: 'Guava, white flesh (Psidium guajava)',
    scientificName: 'Psidium guajava',
    category: 'Fruits',
    waterG: 83.79,
    proteinG: 1.44,
    ashG: 0.72,
    fatG: 0.32,
    fibreTotalG: 8.59,
    fibreInsolubleG: 7.14,
    fibreSolubleG: 1.45,
    carbsG: 5.13,
    energyKj: 135,
    energyKcal: Math.round(135 / 4.184),
    commonAliases: ['guava white', 'amrood', 'koyyapazham']
  },
  {
    code: 'E029',
    name: 'Guava, pink flesh (Psidium guajava)',
    scientificName: 'Psidium guajava',
    category: 'Fruits',
    waterG: 81.22,
    proteinG: 1.19,
    ashG: 0.81,
    fatG: 0.25,
    fibreTotalG: 7.39,
    fibreInsolubleG: 6.12,
    fibreSolubleG: 1.28,
    carbsG: 9.14,
    energyKj: 195,
    energyKcal: Math.round(195 / 4.184),
    commonAliases: ['pink guava', 'red guava']
  },
  {
    code: 'E033',
    name: 'Lemon, juice (Citrus limon)',
    scientificName: 'Citrus limon',
    category: 'Fruits',
    waterG: 91.59,
    proteinG: 0.41,
    ashG: 0.28,
    fatG: 0.75,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 6.97,
    energyKj: 153,
    energyKcal: Math.round(153 / 4.184),
    commonAliases: ['lemon juice', 'elamichai saaru', 'nimbu ras']
  },
  {
    code: 'E036',
    name: 'Mango, ripe, banganapalli (Mangifera indica)',
    scientificName: 'Mangifera indica',
    category: 'Fruits',
    waterG: 88.44,
    proteinG: 0.54,
    ashG: 0.42,
    fatG: 0.55,
    fibreTotalG: 1.88,
    fibreInsolubleG: 1.01,
    fibreSolubleG: 0.87,
    carbsG: 8.18,
    energyKj: 175,
    energyKcal: Math.round(175 / 4.184),
    commonAliases: ['mango banganapalli', 'aam', 'mambazham']
  },
  {
    code: 'E049',
    name: 'Papaya, ripe (Carica papaya)',
    scientificName: 'Carica papaya',
    category: 'Fruits',
    waterG: 91.47,
    proteinG: 0.42,
    ashG: 0.51,
    fatG: 0.16,
    fibreTotalG: 2.83,
    fibreInsolubleG: 1.75,
    fibreSolubleG: 1.08,
    carbsG: 7.82,
    energyKj: 168,
    energyKcal: Math.round(168 / 4.184),
    commonAliases: ['papaya', 'papita', 'pappali']
  },
  {
    code: 'E055',
    name: 'Pomegranate, maroon seeds (Punica granatum)',
    scientificName: 'Punica granatum',
    category: 'Fruits',
    waterG: 83.55,
    proteinG: 1.33,
    ashG: 0.57,
    fatG: 0.15,
    fibreTotalG: 2.83,
    fibreInsolubleG: 2.26,
    fibreSolubleG: 0.57,
    carbsG: 10.64,
    energyKj: 210,
    energyKcal: Math.round(210 / 4.184),
    commonAliases: ['anar', 'mathulai', 'pomegranate']
  },
  {
    code: 'E065',
    name: 'Water melon (Citrullus vulgaris)',
    scientificName: 'Citrullus vulgaris',
    category: 'Fruits',
    waterG: 94.54,
    proteinG: 0.60,
    ashG: 0.13,
    fatG: 0.16,
    fibreTotalG: 0.70,
    fibreInsolubleG: 0.35,
    fibreSolubleG: 0.34,
    carbsG: 3.86,
    energyKj: 85,
    energyKcal: Math.round(85 / 4.184),
    commonAliases: ['tarbooj', 'dharpoosani', 'watermelon']
  },

  // ==========================================
  // F. ROOTS AND TUBERS (Pages 11 & 12)
  // ==========================================
  {
    code: 'F001',
    name: 'Beet root (Beta vulgaris)',
    scientificName: 'Beta vulgaris',
    category: 'Roots and Tubers',
    waterG: 86.95,
    proteinG: 1.95,
    ashG: 1.46,
    fatG: 0.14,
    fibreTotalG: 3.31,
    fibreInsolubleG: 2.60,
    fibreSolubleG: 0.71,
    carbsG: 6.18,
    energyKj: 149,
    energyKcal: Math.round(149 / 4.184),
    commonAliases: ['beetroot', 'chukandar']
  },
  {
    code: 'F002',
    name: 'Carrot, orange (Daucus carota)',
    scientificName: 'Daucus carota',
    category: 'Roots and Tubers',
    waterG: 87.69,
    proteinG: 0.95,
    ashG: 1.16,
    fatG: 0.47,
    fibreTotalG: 4.18,
    fibreInsolubleG: 2.81,
    fibreSolubleG: 1.37,
    carbsG: 5.55,
    energyKj: 139,
    energyKcal: Math.round(139 / 4.184),
    commonAliases: ['carrot orange', 'gajar orange']
  },
  {
    code: 'F003',
    name: 'Carrot, red (Daucus carota)',
    scientificName: 'Daucus carota',
    category: 'Roots and Tubers',
    waterG: 86.07,
    proteinG: 1.04,
    ashG: 1.22,
    fatG: 0.47,
    fibreTotalG: 4.49,
    fibreInsolubleG: 3.09,
    fibreSolubleG: 1.40,
    carbsG: 6.71,
    energyKj: 160,
    energyKcal: Math.round(160 / 4.184),
    commonAliases: ['desi gajar', 'carrot red']
  },
  {
    code: 'F006',
    name: 'Potato, brown skin, big (Solanum tuberosum)',
    scientificName: 'Solanum tuberosum',
    category: 'Roots and Tubers',
    waterG: 80.72,
    proteinG: 1.54,
    ashG: 0.92,
    fatG: 0.23,
    fibreTotalG: 1.71,
    fibreInsolubleG: 1.13,
    fibreSolubleG: 0.58,
    carbsG: 14.89,
    energyKj: 292,
    energyKcal: Math.round(292 / 4.184),
    commonAliases: ['potato', 'aaloo', 'urulakizhangu']
  },
  {
    code: 'F013',
    name: 'Sweet potato, brown skin (Ipomoea batatas)',
    scientificName: 'Ipomoea batatas',
    category: 'Roots and Tubers',
    waterG: 69.21,
    proteinG: 1.33,
    ashG: 0.96,
    fatG: 0.26,
    fibreTotalG: 3.99,
    fibreInsolubleG: 2.57,
    fibreSolubleG: 1.43,
    carbsG: 24.25,
    energyKj: 456,
    energyKcal: Math.round(456 / 4.184),
    commonAliases: ['sweet potato', 'shakarkandi', 'sakkaravalli kizhangu']
  },

  // ==========================================
  // G. CONDIMENTS AND SPICES (Pages 12, 13, 14)
  // ==========================================
  {
    code: 'G001',
    name: 'Chillies, green (Capsicum annuum)',
    scientificName: 'Capsicum annuum',
    category: 'Condiments and Spices',
    waterG: 84.47,
    proteinG: 2.62,
    ashG: 1.01,
    fatG: 0.73,
    fibreTotalG: 4.86,
    fibreInsolubleG: 3.31,
    fibreSolubleG: 1.55,
    carbsG: 6.32,
    energyKj: 191,
    energyKcal: Math.round(191 / 4.184),
    commonAliases: ['green chilli', 'pachai milagai', 'hari mirch']
  },
  {
    code: 'G009',
    name: 'Coriander leaves (Coriandrum sativum)',
    scientificName: 'Coriandrum sativum',
    category: 'Condiments and Spices',
    waterG: 86.99,
    proteinG: 3.52,
    ashG: 2.19,
    fatG: 0.70,
    fibreTotalG: 4.66,
    fibreInsolubleG: 3.24,
    fibreSolubleG: 1.42,
    carbsG: 1.93,
    energyKj: 130,
    energyKcal: Math.round(130 / 4.184),
    commonAliases: ['dhania leaves', 'koththamalli', 'cilantro']
  },
  {
    code: 'G010',
    name: 'Curry leaves (Murraya koenigii)',
    scientificName: 'Murraya koenigii',
    category: 'Condiments and Spices',
    waterG: 65.33,
    proteinG: 7.41,
    ashG: 4.86,
    fatG: 1.06,
    fibreTotalG: 16.83,
    fibreInsolubleG: 13.81,
    fibreSolubleG: 3.02,
    carbsG: 4.51,
    energyKj: 266,
    energyKcal: Math.round(266 / 4.184),
    commonAliases: ['kariveppilai', 'kadi patta', 'curry leaves']
  },
  {
    code: 'G011',
    name: 'Garlic, big clove (Allium sativum)',
    scientificName: 'Allium sativum',
    category: 'Condiments and Spices',
    waterG: 64.38,
    proteinG: 6.92,
    ashG: 1.40,
    fatG: 0.16,
    fibreTotalG: 5.22,
    fibreInsolubleG: 2.56,
    fibreSolubleG: 2.66,
    carbsG: 21.93,
    energyKj: 518,
    energyKcal: Math.round(518 / 4.184),
    commonAliases: ['garlic', 'lahsun', 'poondu']
  },
  {
    code: 'G014',
    name: 'Ginger, fresh (Zingiber officinale)',
    scientificName: 'Zingiber officinale',
    category: 'Condiments and Spices',
    waterG: 81.27,
    proteinG: 2.22,
    ashG: 1.33,
    fatG: 0.85,
    fibreTotalG: 5.36,
    fibreInsolubleG: 4.28,
    fibreSolubleG: 1.08,
    carbsG: 8.97,
    energyKj: 230,
    energyKcal: Math.round(230 / 4.184),
    commonAliases: ['adrak', 'inji', 'fresh ginger']
  },
  {
    code: 'G017',
    name: 'Onion, big (Allium cepa)',
    scientificName: 'Allium cepa',
    category: 'Condiments and Spices',
    waterG: 85.76,
    proteinG: 1.50,
    ashG: 0.50,
    fatG: 0.24,
    fibreTotalG: 2.45,
    fibreInsolubleG: 1.92,
    fibreSolubleG: 0.53,
    carbsG: 9.56,
    energyKj: 201,
    energyKcal: Math.round(201 / 4.184),
    commonAliases: ['onion', 'pyaz', 'vengayam big']
  },
  {
    code: 'G018',
    name: 'Onion, small (Allium cepa)',
    scientificName: 'Allium cepa',
    category: 'Condiments and Spices',
    waterG: 84.67,
    proteinG: 1.82,
    ashG: 0.61,
    fatG: 0.16,
    fibreTotalG: 1.16,
    fibreInsolubleG: 0.70,
    fibreSolubleG: 0.46,
    carbsG: 11.58,
    energyKj: 237,
    energyKcal: Math.round(237 / 4.184),
    commonAliases: ['shallots', 'chinna vengayam', 'sambar onion', 'small onion']
  },
  {
    code: 'G025',
    name: 'Cumin seeds (Cuminum cyminum)',
    scientificName: 'Cuminum cyminum',
    category: 'Condiments and Spices',
    waterG: 10.59,
    proteinG: 13.91,
    ashG: 5.90,
    fatG: 16.64,
    fibreTotalG: 30.35,
    fibreInsolubleG: 25.73,
    fibreSolubleG: 4.62,
    carbsG: 22.62,
    energyKj: 1274,
    energyKcal: Math.round(1274 / 4.184),
    commonAliases: ['jeera', 'seeragam', 'cumin seeds']
  },
  {
    code: 'G026',
    name: 'Fenugreek seeds (Trigonella foenum graecum)',
    scientificName: 'Trigonella foenum graecum',
    category: 'Condiments and Spices',
    waterG: 7.82,
    proteinG: 25.41,
    ashG: 2.93,
    fatG: 5.72,
    fibreTotalG: 47.55,
    fibreInsolubleG: 27.63,
    fibreSolubleG: 19.92,
    carbsG: 10.57,
    energyKj: 983,
    energyKcal: Math.round(983 / 4.184),
    commonAliases: ['methi seeds', 'vendhayam', 'fenugreek seeds']
  },
  {
    code: 'G031',
    name: 'Pepper, black (Piper nigrum)',
    scientificName: 'Piper nigrum',
    category: 'Condiments and Spices',
    waterG: 13.18,
    proteinG: 10.12,
    ashG: 4.58,
    fatG: 2.74,
    fibreTotalG: 33.16,
    fibreInsolubleG: 30.61,
    fibreSolubleG: 2.54,
    carbsG: 36.22,
    energyKj: 910,
    energyKcal: Math.round(910 / 4.184),
    commonAliases: ['black pepper', 'kali mirch', 'milagu']
  },
  {
    code: 'G033',
    name: 'Turmeric powder (Curcuma domestica)',
    scientificName: 'Curcuma longa',
    category: 'Condiments and Spices',
    waterG: 10.58,
    proteinG: 7.66,
    ashG: 6.13,
    fatG: 5.03,
    fibreTotalG: 21.38,
    fibreInsolubleG: 18.79,
    fibreSolubleG: 2.59,
    carbsG: 49.22,
    energyKj: 1174,
    energyKcal: Math.round(1174 / 4.184),
    commonAliases: ['haldi', 'manjal', 'turmeric powder']
  },

  // ==========================================
  // H. NUTS AND OIL SEEDS (Pages 14 & 15)
  // ==========================================
  {
    code: 'H001',
    name: 'Almond (Prunus amygdalus)',
    scientificName: 'Prunus amygdalus',
    category: 'Nuts and Oilseeds',
    waterG: 4.37,
    proteinG: 18.41,
    ashG: 2.62,
    fatG: 58.49,
    fibreTotalG: 13.06,
    fibreInsolubleG: 10.55,
    fibreSolubleG: 2.52,
    carbsG: 3.04,
    energyKj: 2549,
    energyKcal: Math.round(2549 / 4.184),
    commonAliases: ['almonds', 'badam']
  },
  {
    code: 'H005',
    name: 'Cashew nut (Anacardium occidentale)',
    scientificName: 'Anacardium occidentale',
    category: 'Nuts and Oilseeds',
    waterG: 4.44,
    proteinG: 18.78,
    ashG: 2.25,
    fatG: 45.20,
    fibreTotalG: 3.86,
    fibreInsolubleG: 2.23,
    fibreSolubleG: 1.63,
    carbsG: 25.46,
    energyKj: 2438,
    energyKcal: Math.round(2438 / 4.184),
    commonAliases: ['kaju', 'mundhiri', 'cashews']
  },
  {
    code: 'H007',
    name: 'Coconut, kernel, fresh (Cocos nucifera)',
    scientificName: 'Cocos nucifera',
    category: 'Nuts and Oilseeds',
    waterG: 36.14,
    proteinG: 3.84,
    ashG: 1.93,
    fatG: 41.38,
    fibreTotalG: 10.42,
    fibreInsolubleG: 9.43,
    fibreSolubleG: 0.99,
    carbsG: 6.30,
    energyKj: 1711,
    energyKcal: Math.round(1711 / 4.184),
    commonAliases: ['fresh coconut', 'thengai', 'nariyal']
  },
  {
    code: 'H009',
    name: 'Gingelly seeds, black (Sesamum indicum)',
    scientificName: 'Sesamum indicum',
    category: 'Nuts and Oilseeds',
    waterG: 4.51,
    proteinG: 19.17,
    ashG: 5.78,
    fatG: 43.10,
    fibreTotalG: 17.16,
    fibreInsolubleG: 13.57,
    fibreSolubleG: 3.59,
    carbsG: 10.29,
    energyKj: 2124,
    energyKcal: Math.round(2124 / 4.184),
    commonAliases: ['black sesame', 'karuppu ellu', 'til black']
  },
  {
    code: 'H011',
    name: 'Gingelly seeds, white (Sesamum indicum)',
    scientificName: 'Sesamum indicum',
    category: 'Nuts and Oilseeds',
    waterG: 3.30,
    proteinG: 21.70,
    ashG: 4.13,
    fatG: 43.05,
    fibreTotalG: 16.99,
    fibreInsolubleG: 13.49,
    fibreSolubleG: 3.51,
    carbsG: 9.76,
    energyKj: 2161,
    energyKcal: Math.round(2161 / 4.184),
    commonAliases: ['white sesame', 'vellai ellu', 'til white']
  },
  {
    code: 'H012',
    name: 'Ground nut (Arachis hypogaea)',
    scientificName: 'Arachis hypogaea',
    category: 'Nuts and Oilseeds',
    waterG: 6.97,
    proteinG: 23.65,
    ashG: 2.11,
    fatG: 39.63,
    fibreTotalG: 10.38,
    fibreInsolubleG: 8.58,
    fibreSolubleG: 1.79,
    carbsG: 16.83,
    energyKj: 2174,
    energyKcal: Math.round(2174 / 4.184),
    commonAliases: ['peanuts', 'moongphali', 'verkadalai', 'groundnut']
  },
  {
    code: 'H014',
    name: 'Linseeds (Linum usitatissimum)',
    scientificName: 'Linum usitatissimum',
    category: 'Nuts and Oilseeds',
    waterG: 5.48,
    proteinG: 18.55,
    ashG: 3.15,
    fatG: 35.67,
    fibreTotalG: 26.17,
    fibreInsolubleG: 21.83,
    fibreSolubleG: 4.33,
    carbsG: 10.99,
    energyKj: 1857,
    energyKcal: Math.round(1857 / 4.184),
    commonAliases: ['flax seeds', 'alsi', 'aali vithai']
  },
  {
    code: 'H021',
    name: 'Walnut (Juglans regia)',
    scientificName: 'Juglans regia',
    category: 'Nuts and Oilseeds',
    waterG: 3.56,
    proteinG: 14.92,
    ashG: 1.72,
    fatG: 64.27,
    fibreTotalG: 5.39,
    fibreInsolubleG: 4.74,
    fibreSolubleG: 0.65,
    carbsG: 10.14,
    energyKj: 2809,
    energyKcal: Math.round(2809 / 4.184),
    commonAliases: ['akhrot', 'walnut']
  },

  // ==========================================
  // I. SUGARS (Page 15)
  // ==========================================
  {
    code: 'I001',
    name: 'Jaggery, cane (Saccharum officinarum)',
    scientificName: 'Saccharum officinarum',
    category: 'Sugars',
    waterG: 11.20,
    proteinG: 1.85,
    ashG: 1.92,
    fatG: 0.16,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 84.87,
    energyKj: 1480,
    energyKcal: Math.round(1480 / 4.184),
    commonAliases: ['gur', 'vellam', 'cane jaggery']
  },

  // ==========================================
  // J. MUSHROOMS & MISCELLANEOUS (Page 15)
  // ==========================================
  {
    code: 'J001',
    name: 'Button mushroom, fresh (Agaricus sp.)',
    scientificName: 'Agaricus bisporus',
    category: 'Mushrooms',
    waterG: 90.09,
    proteinG: 3.68,
    ashG: 0.71,
    fatG: 0.42,
    fibreTotalG: 3.11,
    fibreInsolubleG: 2.76,
    fibreSolubleG: 0.35,
    carbsG: 1.98,
    energyKj: 115,
    energyKcal: Math.round(115 / 4.184),
    commonAliases: ['button mushroom', 'kalan']
  },
  {
    code: 'K002',
    name: 'Coconut Water (Cocos nucifera)',
    scientificName: 'Cocos nucifera',
    category: 'Miscellaneous',
    waterG: 95.77,
    proteinG: 0.26,
    ashG: 0.65,
    fatG: 0.16,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 3.16,
    energyKj: 64,
    energyKcal: Math.round(64 / 4.184),
    commonAliases: ['elaneer', 'tender coconut water', 'nariyal pani']
  },

  // ==========================================
  // L. MILK AND MILK PRODUCTS (Page 16)
  // ==========================================
  {
    code: 'L001',
    name: 'Milk, whole, Buffalo',
    category: 'Milk & Milk Products',
    waterG: 80.68,
    proteinG: 3.68,
    ashG: 0.67,
    fatG: 6.58,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 8.39,
    energyKj: 449,
    energyKcal: Math.round(449 / 4.184),
    commonAliases: ['buffalo milk', 'eruma paal']
  },
  {
    code: 'L002',
    name: 'Milk, whole, Cow',
    category: 'Milk & Milk Products',
    waterG: 86.64,
    proteinG: 3.26,
    ashG: 0.68,
    fatG: 4.48,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 4.94,
    energyKj: 305,
    energyKcal: Math.round(305 / 4.184),
    commonAliases: ['cow milk', 'pasum paal']
  },
  {
    code: 'L003',
    name: 'Paneer (Cottage cheese)',
    category: 'Milk & Milk Products',
    waterG: 51.96,
    proteinG: 18.86,
    ashG: 1.98,
    fatG: 24.78,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 2.41,
    energyKj: 1278,
    energyKcal: Math.round(1278 / 4.184),
    commonAliases: ['paneer', 'indian cottage cheese']
  },

  // ==========================================
  // M. EGG AND EGG PRODUCTS (Page 17)
  // ==========================================
  {
    code: 'M001',
    name: 'Egg, poultry, whole, raw',
    category: 'Egg & Poultry',
    waterG: 76.51,
    proteinG: 13.28,
    ashG: 0.81,
    fatG: 9.15,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.23,
    energyKj: 564,
    energyKcal: Math.round(564 / 4.184),
    commonAliases: ['egg whole raw', 'muttai raw']
  },
  {
    code: 'M002',
    name: 'Egg, poultry, white, raw',
    category: 'Egg & Poultry',
    waterG: 86.68,
    proteinG: 10.84,
    ashG: 0.75,
    fatG: 0.06,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 187,
    energyKcal: Math.round(187 / 4.184),
    commonAliases: ['egg white raw']
  },
  {
    code: 'M004',
    name: 'Egg, poultry, whole, boiled',
    category: 'Egg & Poultry',
    waterG: 73.46,
    proteinG: 13.43,
    ashG: 0.86,
    fatG: 10.54,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.21,
    energyKj: 618,
    energyKcal: Math.round(618 / 4.184),
    commonAliases: ['boiled egg', 'boiled egg whole']
  },
  {
    code: 'M005',
    name: 'Egg, poultry, white, boiled',
    category: 'Egg & Poultry',
    waterG: 83.54,
    proteinG: 12.37,
    ashG: 0.81,
    fatG: 0.26,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 220,
    energyKcal: Math.round(220 / 4.184),
    commonAliases: ['boiled egg white']
  },

  // ==========================================
  // N. POULTRY (Page 18)
  // ==========================================
  {
    code: 'N003',
    name: 'Chicken, poultry, breast, skinless',
    category: 'Poultry & Meat',
    waterG: 67.15,
    proteinG: 21.81,
    ashG: 1.19,
    fatG: 9.00,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 704,
    energyKcal: Math.round(704 / 4.184),
    commonAliases: ['chicken breast', 'skinless chicken breast']
  },

  // ==========================================
  // S. FISH & SHELLFISH (Page 21)
  // ==========================================
  {
    code: 'S006',
    name: 'Rohu (Labeo rohita)',
    scientificName: 'Labeo rohita',
    category: 'Fish & Seafood',
    waterG: 76.34,
    proteinG: 19.71,
    ashG: 1.28,
    fatG: 2.39,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 428,
    energyKcal: Math.round(428 / 4.184),
    commonAliases: ['rohu fish', 'rohu']
  },
  {
    code: 'S008',
    name: 'Prawns, big (Macrobrachium rosenbergii)',
    category: 'Fish & Seafood',
    waterG: 77.43,
    proteinG: 19.24,
    ashG: 0.84,
    fatG: 0.52,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 380,
    energyKcal: Math.round(380 / 4.184),
    commonAliases: ['prawns', 'iraal', 'shrimp']
  },

  // ==========================================
  // I. FATS AND EDIBLE OILS (Page 15)
  // ==========================================
  {
    code: 'I001',
    name: 'Sunflower seed oil',
    category: 'Fats and Edible Oils',
    waterG: 0.00,
    proteinG: 0.00,
    ashG: 0.00,
    fatG: 100.00,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 3762,
    energyKcal: Math.round(3762 / 4.184),
    commonAliases: ['sunflower oil', 'cooking oil', 'oil', 'sunflower']
  },
  {
    code: 'I002',
    name: 'Groundnut oil (Peanut oil)',
    category: 'Fats and Edible Oils',
    waterG: 0.00,
    proteinG: 0.00,
    ashG: 0.00,
    fatG: 100.00,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 3762,
    energyKcal: Math.round(3762 / 4.184),
    commonAliases: ['groundnut oil', 'peanut oil', 'kadala ennai']
  },
  {
    code: 'I003',
    name: 'Mustard seed oil',
    category: 'Fats and Edible Oils',
    waterG: 0.00,
    proteinG: 0.00,
    ashG: 0.00,
    fatG: 100.00,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 3762,
    energyKcal: Math.round(3762 / 4.184),
    commonAliases: ['mustard oil', 'sarson ka tel', 'kadugu ennai']
  },
  {
    code: 'I004',
    name: 'Coconut oil',
    category: 'Fats and Edible Oils',
    waterG: 0.00,
    proteinG: 0.00,
    ashG: 0.00,
    fatG: 100.00,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 3762,
    energyKcal: Math.round(3762 / 4.184),
    commonAliases: ['coconut oil', 'thengai ennai', 'nariyal tel']
  },
  {
    code: 'I005',
    name: 'Sesame seed oil (Gingelly oil)',
    category: 'Fats and Edible Oils',
    waterG: 0.00,
    proteinG: 0.00,
    ashG: 0.00,
    fatG: 100.00,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 3762,
    energyKcal: Math.round(3762 / 4.184),
    commonAliases: ['sesame oil', 'gingelly oil', 'nallennai', 'til oil']
  },
  {
    code: 'I006',
    name: 'Ghee, cow (Clarified butter)',
    category: 'Fats and Edible Oils',
    waterG: 0.50,
    proteinG: 0.00,
    ashG: 0.00,
    fatG: 99.50,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 3740,
    energyKcal: Math.round(3740 / 4.184),
    commonAliases: ['ghee', 'cow ghee', 'nei', 'clarified butter']
  },
  {
    code: 'I007',
    name: 'Butter, table (salted/unsalted)',
    category: 'Fats and Edible Oils',
    waterG: 16.10,
    proteinG: 0.85,
    ashG: 1.45,
    fatG: 81.00,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.60,
    energyKj: 3054,
    energyKcal: Math.round(3054 / 4.184),
    commonAliases: ['butter', 'vennai', 'makhan']
  },
  {
    code: 'I008',
    name: 'Olive oil, virgin/refined',
    category: 'Fats and Edible Oils',
    waterG: 0.00,
    proteinG: 0.00,
    ashG: 0.00,
    fatG: 100.00,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 0.00,
    energyKj: 3762,
    energyKcal: Math.round(3762 / 4.184),
    commonAliases: ['olive oil', 'extra virgin olive oil']
  },

  // ==========================================
  // J. SUGARS AND SYRUPS (Page 16)
  // ==========================================
  {
    code: 'J001',
    name: 'Cane sugar (Refined white sugar)',
    category: 'Sugars',
    waterG: 0.20,
    proteinG: 0.00,
    ashG: 0.05,
    fatG: 0.00,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 99.75,
    energyKj: 1667,
    energyKcal: Math.round(1667 / 4.184),
    commonAliases: ['sugar', 'white sugar', 'sakkarai', 'cheeni']
  },
  {
    code: 'J002',
    name: 'Jaggery, cane (Gur)',
    category: 'Sugars',
    waterG: 9.00,
    proteinG: 0.40,
    ashG: 2.60,
    fatG: 0.10,
    fibreTotalG: 0.00,
    fibreInsolubleG: 0.00,
    fibreSolubleG: 0.00,
    carbsG: 85.00,
    energyKj: 1435,
    energyKcal: Math.round(1435 / 4.184),
    commonAliases: ['jaggery', 'gur', 'vellam', 'cane jaggery']
  },
  {
    code: 'J003',
    name: 'Honey, natural',
    category: 'Sugars',
    waterG: 19.30,
    proteinG: 0.30,
    ashG: 0.20,
    fatG: 0.00,
    fibreTotalG: 0.20,
    fibreInsolubleG: 0.10,
    fibreSolubleG: 0.10,
    carbsG: 79.50,
    energyKj: 1339,
    energyKcal: Math.round(1339 / 4.184),
    commonAliases: ['honey', 'then', 'madhu']
  }
];

// Map lookup by official Code
export const IFCT_TABLE1_MAP = new Map<string, IfctTable1Food>();
for (const food of IFCT_TABLE1_DATABASE) {
  IFCT_TABLE1_MAP.set(food.code.toUpperCase(), food);
}

/**
 * Find IFCT Table 1 food by code or query string
 */
export function findIfctTable1Food(query: string): IfctTable1Food | null {
  if (!query) return null;
  const q = query.trim().toUpperCase();
  
  // Exact code match (e.g. A015)
  if (IFCT_TABLE1_MAP.has(q)) {
    return IFCT_TABLE1_MAP.get(q)!;
  }

  // Name or Alias match
  const qLower = query.trim().toLowerCase();
  for (const food of IFCT_TABLE1_DATABASE) {
    if (food.name.toLowerCase().includes(qLower)) return food;
    if (food.commonAliases.some(alias => alias.toLowerCase() === qLower || qLower.includes(alias.toLowerCase()))) {
      return food;
    }
  }

  return null;
}

/**
 * EXACT ELSHA CALCULATION SYSTEM FORMULA:
 * Nutrient value = (IFCT value per 100 g × consumed weight in g) / 100
 * Conversion: kcal = kJ ÷ 4.184
 */
export interface ElshaCalculationBreakdown {
  food: IfctTable1Food;
  consumedWeightG: number;
  multiplier: number; // weight ÷ 100 (e.g. 30 ÷ 100 = 0.3)
  
  // Per 100g source reference
  per100g: {
    energyKj: number;
    proteinG: number;
    fatG: number;
    fibreTotalG: number;
    fibreInsolubleG: number;
    fibreSolubleG: number;
    carbsG: number;
    waterG: number;
    ashG: number;
  };

  // Step-by-step arithmetic equations matching clinical standards:
  steps: {
    energyKj: string; // e.g. "1491 × 30 ÷ 100 = 447.3 kJ"
    energyKcal: string; // e.g. "447.3 ÷ 4.184 = 106.9 kcal (≈ 107 kcal)"
    protein: string; // e.g. "7.94 × 30 ÷ 100 = 2.38 g"
    fat: string; // e.g. "0.52 × 30 ÷ 100 = 0.16 g"
    fibreTotal: string; // e.g. "2.81 × 30 ÷ 100 = 0.84 g"
    carbs: string; // e.g. "78.24 × 30 ÷ 100 = 23.47 g"
  };

  // Final rounded values for requested quantity
  values: {
    energyKj: number; // 447.3 kJ
    energyKcal: number; // 107 kcal
    proteinG: number; // 2.38 g
    fatG: number; // 0.16 g
    fibreTotalG: number; // 0.84 g
    carbsG: number; // 23.47 g
    waterG: number;
    ashG: number;
  };
}

/**
 * Compute the exact mathematical nutrient breakdown according to the user's formula
 */
export function computeElshaIfctNutrients(
  foodOrCode: string | IfctTable1Food,
  consumedWeightG: number
): ElshaCalculationBreakdown | null {
  const food = typeof foodOrCode === 'string' ? findIfctTable1Food(foodOrCode) : foodOrCode;
  if (!food) return null;

  const w = Math.max(0, consumedWeightG);
  const factor = w / 100; // e.g. 30 / 100 = 0.3

  // Energy in kJ for consumed weight
  const energyKjVal = Math.round(((food.energyKj * w) / 100) * 10) / 10;
  // Converted kcal = kJ ÷ 4.184
  const energyKcalVal = Math.round(energyKjVal / 4.184);

  // Exact nutrient formula: (value * w) / 100
  const proteinVal = Math.round(((food.proteinG * w) / 100) * 100) / 100;
  const fatVal = Math.round(((food.fatG * w) / 100) * 100) / 100;
  const fibreVal = Math.round(((food.fibreTotalG * w) / 100) * 100) / 100;
  const carbsVal = Math.round(((food.carbsG * w) / 100) * 100) / 100;
  const waterVal = Math.round(((food.waterG * w) / 100) * 100) / 100;
  const ashVal = Math.round(((food.ashG * w) / 100) * 100) / 100;

  return {
    food,
    consumedWeightG: w,
    multiplier: Math.round(factor * 1000) / 1000,
    per100g: {
      energyKj: food.energyKj,
      proteinG: food.proteinG,
      fatG: food.fatG,
      fibreTotalG: food.fibreTotalG,
      fibreInsolubleG: food.fibreInsolubleG || 0,
      fibreSolubleG: food.fibreSolubleG || 0,
      carbsG: food.carbsG,
      waterG: food.waterG,
      ashG: food.ashG,
    },
    steps: {
      energyKj: `${food.energyKj} × ${w} ÷ 100 = ${energyKjVal} kJ`,
      energyKcal: `${energyKjVal} ÷ 4.184 = ${(energyKjVal / 4.184).toFixed(1)} kcal (≈ ${energyKcalVal} kcal)`,
      protein: `${food.proteinG} × ${w} ÷ 100 = ${proteinVal} g`,
      fat: `${food.fatG} × ${w} ÷ 100 = ${fatVal} g`,
      fibreTotal: `${food.fibreTotalG} × ${w} ÷ 100 = ${fibreVal} g`,
      carbs: `${food.carbsG} × ${w} ÷ 100 = ${carbsVal} g`,
    },
    values: {
      energyKj: energyKjVal,
      energyKcal: energyKcalVal,
      proteinG: proteinVal,
      fatG: fatVal,
      fibreTotalG: fibreVal,
      carbsG: carbsVal,
      waterG: waterVal,
      ashG: ashVal,
    }
  };
}
