/**
 * ICMR-NIN Indian Food Composition Tables (IFCT 2017 / NVIF 2017)
 * Authoritative food composition database published by the National Institute of Nutrition (NIN),
 * Indian Council of Medical Research (ICMR), Hyderabad, India.
 * 
 * Strict Rule: All nutrient values are based exclusively on verified laboratory values per 100g edible portion.
 * Calculation formula for entered quantity:
 * Nutrient for entered quantity = IFCT nutrient value per 100 g × entered quantity (g/ml) ÷ 100
 */

export interface IfctFoodEntry {
  foodCode: string; // Official IFCT 2017 food code (e.g. A001, B002, C003)
  name: string; // Official descriptive name
  commonNames: string[]; // Aliases/vernacular names for matching
  scientificName?: string;
  category: 
    | 'Cereals & Millets'
    | 'Grain Legumes & Pulses'
    | 'Green Leafy Vegetables'
    | 'Other Vegetables'
    | 'Roots & Tubers'
    | 'Nuts & Oilseeds'
    | 'Condiments & Spices'
    | 'Fruits'
    | 'Milk & Milk Products'
    | 'Fats & Edible Oils'
    | 'Sugars'
    | 'Egg, Poultry & Fish'
    | 'Water & Plain Beverages';
  foodState: 'Raw' | 'Cooked / Boiled' | 'Steamed' | 'Roasted / Puffed' | 'Fermented' | 'Liquid';
  yieldWaterAbsorptionFactor?: number; // E.g. raw rice to cooked rice is ~2.7x
  
  // Standard IFCT 2017 values per 100g edible portion
  energyKj?: number; // Raw laboratory value in kJ
  energyKcal: number; // Converted using kcal = kJ ÷ 4.184
  proteinG: number;
  fatG: number;
  carbsG: number;
  fiberG: number;
  ironMg: number;
  calciumMg: number;
  sodiumMg: number;
  potassiumMg: number;
  zincMg: number;
  magnesiumMg: number;
  vitaminAMcg: number;
  vitaminCMg: number;
  thiamineB1Mg: number;
  riboflavinB2Mg: number;
  niacinB3Mg: number;
  folateMcg: number;
  waterG?: number;
}

export interface NutrientCalculationAuditStep {
  foodName: string;
  enteredQuantity: number;
  enteredUnit: string;
  ifctFoodCode: string;
  officialIfctName: string;
  foodState: string;
  category: string;
  per100gReference: {
    energyKcal: number;
    proteinG: number;
    fatG: number;
    carbsG: number;
    fiberG: number;
    ironMg: number;
    calciumMg: number;
    sodiumMg: number;
    potassiumMg: number;
    zincMg: number;
    magnesiumMg: number;
    vitaminAMcg: number;
    vitaminCMg: number;
    thiamineB1Mg: number;
    riboflavinB2Mg: number;
    niacinB3Mg: number;
    folateMcg: number;
  };
  calculationFormula: string; // Explanatory mathematical string
  calculatedNutrients: {
    energyKcal: number;
    proteinG: number;
    fatG: number;
    carbsG: number;
    fiberG: number;
    ironMg: number;
    calciumMg: number;
    sodiumMg: number;
    potassiumMg: number;
    zincMg: number;
    magnesiumMg: number;
    vitaminAMcg: number;
    vitaminCMg: number;
    thiamineB1Mg: number;
    riboflavinB2Mg: number;
    niacinB3Mg: number;
    folateMcg: number;
    fluidLiters: number;
  };
  isVerifiedIfct: boolean;
  auditExplanation: string;
  statusMessage: string;
}

// ------------------------------------------------------------------------------------------------
// MASTER VERIFIED IFCT 2017 / NVIF 2017 FOOD COMPOSITION REPOSITORY (Values strictly per 100g edible)
// ------------------------------------------------------------------------------------------------

export const IFCT_2017_DATABASE: IfctFoodEntry[] = [
  // --------------------------------------------------------------------
  // WATER & PLAIN BEVERAGES (Water Rule: STRICTLY 0 KCAL & 0 NUTRIENTS)
  // --------------------------------------------------------------------
  {
    foodCode: 'W000-WATER',
    name: 'Drinking Water, Plain / Boiled / Warm',
    commonNames: ['water', 'plain water', 'warm water', 'drinking water', 'boiled water', 'filtered water', 'room temp water', 'hot water'],
    category: 'Water & Plain Beverages',
    foodState: 'Liquid',
    energyKcal: 0,
    proteinG: 0,
    fatG: 0,
    carbsG: 0,
    fiberG: 0,
    ironMg: 0,
    calciumMg: 0,
    sodiumMg: 0,
    potassiumMg: 0,
    zincMg: 0,
    magnesiumMg: 0,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0,
    riboflavinB2Mg: 0,
    niacinB3Mg: 0,
    folateMcg: 0,
    waterG: 100,
  },

  // --------------------------------------------------------------------
  // CEREALS & MILLETS (RAW & COOKED STATES DISTINCT)
  // --------------------------------------------------------------------
  {
    foodCode: 'A015',
    name: 'Rice, raw, milled (Oryza sativa)',
    commonNames: ['raw rice', 'rice raw', 'white rice raw', 'arisi raw', 'chawal raw', 'idli rice raw', 'A015', 'A001-RAW'],
    scientificName: 'Oryza sativa',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKj: 1491,
    energyKcal: Math.round(1491 / 4.184), // 356 kcal per 100g (converted using kJ ÷ 4.184)
    proteinG: 7.94,
    fatG: 0.52,
    carbsG: 78.24,
    fiberG: 2.81,
    ironMg: 0.65,
    calciumMg: 7.49,
    sodiumMg: 4.88,
    potassiumMg: 112,
    zincMg: 1.21,
    magnesiumMg: 31.8,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.06,
    riboflavinB2Mg: 0.05,
    niacinB3Mg: 1.69,
    folateMcg: 10.7,
    waterG: 9.93,
  },
  {
    foodCode: 'A001-COOKED',
    name: 'Rice, white, cooked / boiled',
    commonNames: ['cooked rice', 'boiled rice', 'white rice cooked', 'steamed rice', 'rice cooked', 'chawal cooked', 'sadham'],
    scientificName: 'Oryza sativa',
    category: 'Cereals & Millets',
    foodState: 'Cooked / Boiled',
    yieldWaterAbsorptionFactor: 2.7,
    energyKcal: 130,
    proteinG: 2.5,
    fatG: 0.2,
    carbsG: 29.3,
    fiberG: 1.1,
    ironMg: 0.33,
    calciumMg: 4,
    sodiumMg: 2,
    potassiumMg: 41,
    zincMg: 0.5,
    magnesiumMg: 13,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.03,
    riboflavinB2Mg: 0.01,
    niacinB3Mg: 0.67,
    folateMcg: 6,
    waterG: 68.0,
  },
  {
    foodCode: 'A002-RAW',
    name: 'Wheat flour, whole grain, raw (Atta)',
    commonNames: ['wheat flour raw', 'whole wheat flour', 'atta raw', 'godhumai raw', 'gehun raw'],
    scientificName: 'Triticum aestivum',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKcal: 322,
    proteinG: 10.6,
    fatG: 1.5,
    carbsG: 64.9,
    fiberG: 11.2,
    ironMg: 3.9,
    calciumMg: 39,
    sodiumMg: 9,
    potassiumMg: 315,
    zincMg: 2.2,
    magnesiumMg: 115,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.45,
    riboflavinB2Mg: 0.17,
    niacinB3Mg: 3.1,
    folateMcg: 37,
    waterG: 12.2,
  },
  {
    foodCode: 'A002-COOKED',
    name: 'Phulka / Chapati, whole wheat, tawa roasted without oil',
    commonNames: ['phulka', 'chapati', 'roti', 'phulkas', 'chapatis', 'rotis', 'wheat roti', 'dry roti'],
    scientificName: 'Triticum aestivum',
    category: 'Cereals & Millets',
    foodState: 'Roasted / Puffed',
    energyKcal: 268,
    proteinG: 8.8,
    fatG: 1.3,
    carbsG: 54.1,
    fiberG: 9.3,
    ironMg: 3.25,
    calciumMg: 32,
    sodiumMg: 7.5,
    potassiumMg: 262,
    zincMg: 1.8,
    magnesiumMg: 96,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.38,
    riboflavinB2Mg: 0.14,
    niacinB3Mg: 2.6,
    folateMcg: 31,
    waterG: 26.5,
  },
  {
    foodCode: 'A003-RAW',
    name: 'Finger millet, raw (Ragi / Mandua)',
    commonNames: ['ragi raw', 'finger millet raw', 'mandua', 'kezhvaragu raw', 'ragi flour'],
    scientificName: 'Eleusine coracana',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKcal: 328,
    proteinG: 7.3,
    fatG: 1.3,
    carbsG: 72.0,
    fiberG: 11.5,
    ironMg: 3.9,
    calciumMg: 344,
    sodiumMg: 11,
    potassiumMg: 408,
    zincMg: 2.3,
    magnesiumMg: 137,
    vitaminAMcg: 6,
    vitaminCMg: 0,
    thiamineB1Mg: 0.42,
    riboflavinB2Mg: 0.19,
    niacinB3Mg: 1.1,
    folateMcg: 34,
    waterG: 13.1,
  },
  {
    foodCode: 'A004-RAW',
    name: 'Foxtail millet, raw (Thinai / Kangni)',
    commonNames: ['foxtail millet', 'thinai', 'kangni', 'navane', 'korra', 'foxtail millet raw'],
    scientificName: 'Setaria italica',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKcal: 331,
    proteinG: 12.3,
    fatG: 4.3,
    carbsG: 60.9,
    fiberG: 8.0,
    ironMg: 2.8,
    calciumMg: 31,
    sodiumMg: 5,
    potassiumMg: 250,
    zincMg: 2.4,
    magnesiumMg: 81,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.59,
    riboflavinB2Mg: 0.11,
    niacinB3Mg: 3.2,
    folateMcg: 15,
    waterG: 11.2,
  },
  {
    foodCode: 'A005-RAW',
    name: 'Barnyard millet, raw (Kuthiraivali / Sanwa)',
    commonNames: ['barnyard millet', 'kuthiraivali', 'sanwa', 'jhangora', 'oodalu', 'barnyard millet raw'],
    scientificName: 'Echinochloa frumentacea',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKcal: 307,
    proteinG: 6.2,
    fatG: 2.2,
    carbsG: 65.5,
    fiberG: 9.8,
    ironMg: 5.0,
    calciumMg: 20,
    sodiumMg: 6,
    potassiumMg: 270,
    zincMg: 3.0,
    magnesiumMg: 82,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.33,
    riboflavinB2Mg: 0.10,
    niacinB3Mg: 4.2,
    folateMcg: 18,
    waterG: 11.9,
  },
  {
    foodCode: 'A006-RAW',
    name: 'Little millet, raw (Samai / Kutki)',
    commonNames: ['little millet', 'samai', 'kutki', 'same', 'gajro', 'little millet raw'],
    scientificName: 'Panicum sumatrense',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKcal: 341,
    proteinG: 7.7,
    fatG: 4.7,
    carbsG: 67.0,
    fiberG: 7.6,
    ironMg: 1.3,
    calciumMg: 17,
    sodiumMg: 5,
    potassiumMg: 220,
    zincMg: 1.8,
    magnesiumMg: 78,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.30,
    riboflavinB2Mg: 0.09,
    niacinB3Mg: 3.2,
    folateMcg: 12,
    waterG: 11.5,
  },
  {
    foodCode: 'A007-RAW',
    name: 'Kodo millet, raw (Varagu / Kodra)',
    commonNames: ['kodo millet', 'varagu', 'kodra', 'harka', 'ariro', 'kodo millet raw'],
    scientificName: 'Paspalum scrobiculatum',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKcal: 309,
    proteinG: 8.3,
    fatG: 1.4,
    carbsG: 65.9,
    fiberG: 9.0,
    ironMg: 0.5,
    calciumMg: 27,
    sodiumMg: 4,
    potassiumMg: 140,
    zincMg: 1.6,
    magnesiumMg: 88,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.15,
    riboflavinB2Mg: 0.09,
    niacinB3Mg: 1.5,
    folateMcg: 23,
    waterG: 11.8,
  },
  {
    foodCode: 'A008-RAW',
    name: 'Pearl millet, raw (Bajra / Kambu)',
    commonNames: ['pearl millet', 'bajra', 'kambu', 'sajjalu', 'bajri', 'pearl millet raw'],
    scientificName: 'Pennisetum glaucum',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKcal: 348,
    proteinG: 11.6,
    fatG: 5.0,
    carbsG: 61.8,
    fiberG: 11.5,
    ironMg: 8.0,
    calciumMg: 42,
    sodiumMg: 10,
    potassiumMg: 390,
    zincMg: 3.1,
    magnesiumMg: 137,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.38,
    riboflavinB2Mg: 0.21,
    niacinB3Mg: 2.8,
    folateMcg: 45,
    waterG: 12.4,
  },
  {
    foodCode: 'A009-RAW',
    name: 'Sorghum, raw (Jowar / Cholam)',
    commonNames: ['sorghum', 'jowar', 'cholam', 'jonna', 'sorghum raw', 'jowar flour'],
    scientificName: 'Sorghum bicolor',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKcal: 334,
    proteinG: 10.0,
    fatG: 1.9,
    carbsG: 67.7,
    fiberG: 10.2,
    ironMg: 4.1,
    calciumMg: 25,
    sodiumMg: 7,
    potassiumMg: 274,
    zincMg: 2.0,
    magnesiumMg: 133,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.35,
    riboflavinB2Mg: 0.14,
    niacinB3Mg: 2.1,
    folateMcg: 20,
    waterG: 11.9,
  },
  {
    foodCode: 'A010-RAW',
    name: 'Oats, rolled / whole grain, raw (Avena sativa)',
    commonNames: ['oats', 'rolled oats', 'oat flakes', 'raw oats', 'oatmeal raw'],
    scientificName: 'Avena sativa',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKcal: 374,
    proteinG: 13.6,
    fatG: 7.0,
    carbsG: 62.8,
    fiberG: 10.6,
    ironMg: 4.7,
    calciumMg: 50,
    sodiumMg: 4,
    potassiumMg: 429,
    zincMg: 3.6,
    magnesiumMg: 144,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.50,
    riboflavinB2Mg: 0.13,
    niacinB3Mg: 1.1,
    folateMcg: 56,
    waterG: 10.3,
  },
  {
    foodCode: 'A010-COOKED',
    name: 'Oats porridge, cooked with plain water',
    commonNames: ['oats porridge', 'cooked oats', 'oatmeal cooked', 'oats cooked in water'],
    scientificName: 'Avena sativa',
    category: 'Cereals & Millets',
    foodState: 'Cooked / Boiled',
    yieldWaterAbsorptionFactor: 5.2,
    energyKcal: 71,
    proteinG: 2.5,
    fatG: 1.4,
    carbsG: 12.0,
    fiberG: 1.7,
    ironMg: 0.9,
    calciumMg: 10,
    sodiumMg: 2,
    potassiumMg: 82,
    zincMg: 0.7,
    magnesiumMg: 27,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.09,
    riboflavinB2Mg: 0.02,
    niacinB3Mg: 0.21,
    folateMcg: 11,
    waterG: 83.0,
  },
  {
    foodCode: 'A011-RAW',
    name: 'Semolina, wheat, raw (Rava / Suji)',
    commonNames: ['rava', 'suji', 'sooji', 'semolina', 'rava raw'],
    scientificName: 'Triticum durum',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKcal: 348,
    proteinG: 10.4,
    fatG: 0.8,
    carbsG: 72.8,
    fiberG: 3.9,
    ironMg: 1.3,
    calciumMg: 16,
    sodiumMg: 3,
    potassiumMg: 105,
    zincMg: 1.0,
    magnesiumMg: 34,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.28,
    riboflavinB2Mg: 0.08,
    niacinB3Mg: 1.8,
    folateMcg: 21,
    waterG: 12.1,
  },
  {
    foodCode: 'A012-RAW',
    name: 'Broken wheat / Dalia, raw',
    commonNames: ['dalia', 'broken wheat', 'daliya', 'godhumai rava'],
    scientificName: 'Triticum aestivum',
    category: 'Cereals & Millets',
    foodState: 'Raw',
    energyKcal: 342,
    proteinG: 11.2,
    fatG: 1.4,
    carbsG: 68.5,
    fiberG: 10.8,
    ironMg: 3.8,
    calciumMg: 34,
    sodiumMg: 8,
    potassiumMg: 290,
    zincMg: 2.1,
    magnesiumMg: 110,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.41,
    riboflavinB2Mg: 0.15,
    niacinB3Mg: 3.0,
    folateMcg: 35,
    waterG: 11.5,
  },

  // --------------------------------------------------------------------
  // GRAIN LEGUMES & PULSES (RAW & SPROUTED / COOKED)
  // --------------------------------------------------------------------
  {
    foodCode: 'B001-RAW',
    name: 'Black gram dal, split, raw (Urad dal / Ulutham Paruppu)',
    commonNames: ['urad dal', 'black gram dal', 'ulutham paruppu', 'urad dal raw', 'minapappu'],
    scientificName: 'Vigna mungo',
    category: 'Grain Legumes & Pulses',
    foodState: 'Raw',
    energyKcal: 347,
    proteinG: 24.0,
    fatG: 1.4,
    carbsG: 59.6,
    fiberG: 10.6,
    ironMg: 7.6,
    calciumMg: 154,
    sodiumMg: 19,
    potassiumMg: 983,
    zincMg: 3.0,
    magnesiumMg: 130,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.42,
    riboflavinB2Mg: 0.20,
    niacinB3Mg: 2.0,
    folateMcg: 144,
    waterG: 10.9,
  },
  {
    foodCode: 'B002-RAW',
    name: 'Green gram dal, split, raw (Moong dal / Pasi Paruppu)',
    commonNames: ['moong dal', 'green gram dal', 'pasi paruppu', 'moong dal raw', 'pesara pappu'],
    scientificName: 'Vigna radiata',
    category: 'Grain Legumes & Pulses',
    foodState: 'Raw',
    energyKcal: 334,
    proteinG: 24.0,
    fatG: 1.2,
    carbsG: 56.8,
    fiberG: 8.2,
    ironMg: 4.4,
    calciumMg: 75,
    sodiumMg: 14,
    potassiumMg: 843,
    zincMg: 2.8,
    magnesiumMg: 127,
    vitaminAMcg: 15,
    vitaminCMg: 0,
    thiamineB1Mg: 0.47,
    riboflavinB2Mg: 0.21,
    niacinB3Mg: 2.4,
    folateMcg: 140,
    waterG: 10.4,
  },
  {
    foodCode: 'B002-SPROUTED',
    name: 'Green gram whole, sprouted raw (Sprouted Moong / Pasi Payaru)',
    commonNames: ['sprouted moong', 'moong sprouts', 'sprouted green gram', 'pasi payaru sprouts', 'sprouts moong'],
    scientificName: 'Vigna radiata',
    category: 'Grain Legumes & Pulses',
    foodState: 'Raw',
    energyKcal: 128,
    proteinG: 9.2,
    fatG: 0.5,
    carbsG: 21.6,
    fiberG: 5.2,
    ironMg: 2.5,
    calciumMg: 45,
    sodiumMg: 8,
    potassiumMg: 320,
    zincMg: 1.1,
    magnesiumMg: 52,
    vitaminAMcg: 22,
    vitaminCMg: 16.5,
    thiamineB1Mg: 0.21,
    riboflavinB2Mg: 0.16,
    niacinB3Mg: 1.2,
    folateMcg: 65,
    waterG: 67.0,
  },
  {
    foodCode: 'B003-RAW',
    name: 'Red gram dal, raw (Toor dal / Thuvaram Paruppu)',
    commonNames: ['toor dal', 'arhar dal', 'thuvaram paruppu', 'red gram dal', 'kandi pappu', 'toor dal raw'],
    scientificName: 'Cajanus cajan',
    category: 'Grain Legumes & Pulses',
    foodState: 'Raw',
    energyKcal: 335,
    proteinG: 22.3,
    fatG: 1.7,
    carbsG: 57.6,
    fiberG: 9.1,
    ironMg: 5.1,
    calciumMg: 73,
    sodiumMg: 17,
    potassiumMg: 1104,
    zincMg: 2.7,
    magnesiumMg: 112,
    vitaminAMcg: 13,
    vitaminCMg: 0,
    thiamineB1Mg: 0.45,
    riboflavinB2Mg: 0.19,
    niacinB3Mg: 2.9,
    folateMcg: 103,
    waterG: 10.8,
  },
  {
    foodCode: 'B004-RAW',
    name: 'Bengal gram dal, split, raw (Chana dal / Kadalai Paruppu)',
    commonNames: ['chana dal', 'bengal gram dal', 'kadalai paruppu', 'senaga pappu', 'chana dal raw'],
    scientificName: 'Cicer arietinum',
    category: 'Grain Legumes & Pulses',
    foodState: 'Raw',
    energyKcal: 360,
    proteinG: 20.8,
    fatG: 5.6,
    carbsG: 56.6,
    fiberG: 15.3,
    ironMg: 5.3,
    calciumMg: 56,
    sodiumMg: 12,
    potassiumMg: 800,
    zincMg: 2.2,
    magnesiumMg: 130,
    vitaminAMcg: 12,
    vitaminCMg: 0,
    thiamineB1Mg: 0.48,
    riboflavinB2Mg: 0.21,
    niacinB3Mg: 2.4,
    folateMcg: 148,
    waterG: 10.7,
  },
  {
    foodCode: 'B005-RAW',
    name: 'Chickpeas whole, raw (Kabuli / Desi Chana / Kondai Kadalai)',
    commonNames: ['chickpeas raw', 'chana whole raw', 'chole raw', 'kondai kadalai raw', 'kabuli chana raw'],
    scientificName: 'Cicer arietinum',
    category: 'Grain Legumes & Pulses',
    foodState: 'Raw',
    energyKcal: 364,
    proteinG: 19.3,
    fatG: 6.0,
    carbsG: 60.6,
    fiberG: 17.4,
    ironMg: 6.2,
    calciumMg: 105,
    sodiumMg: 24,
    potassiumMg: 875,
    zincMg: 3.4,
    magnesiumMg: 115,
    vitaminAMcg: 15,
    vitaminCMg: 4.0,
    thiamineB1Mg: 0.40,
    riboflavinB2Mg: 0.18,
    niacinB3Mg: 1.5,
    folateMcg: 216,
    waterG: 9.9,
  },
  {
    foodCode: 'B005-COOKED',
    name: 'Chickpeas, boiled / cooked (Boiled Chana / Sundal base)',
    commonNames: ['boiled chickpeas', 'boiled chana', 'chickpeas cooked', 'chole cooked', 'boiled kondai kadalai'],
    scientificName: 'Cicer arietinum',
    category: 'Grain Legumes & Pulses',
    foodState: 'Cooked / Boiled',
    energyKcal: 164,
    proteinG: 8.9,
    fatG: 2.6,
    carbsG: 27.4,
    fiberG: 7.6,
    ironMg: 2.9,
    calciumMg: 49,
    sodiumMg: 11,
    potassiumMg: 291,
    zincMg: 1.5,
    magnesiumMg: 48,
    vitaminAMcg: 7,
    vitaminCMg: 1.3,
    thiamineB1Mg: 0.12,
    riboflavinB2Mg: 0.06,
    niacinB3Mg: 0.52,
    folateMcg: 63,
    waterG: 60.2,
  },
  {
    foodCode: 'B006-RAW',
    name: 'Kidney beans, raw (Rajma)',
    commonNames: ['rajma', 'kidney beans', 'rajma raw'],
    scientificName: 'Phaseolus vulgaris',
    category: 'Grain Legumes & Pulses',
    foodState: 'Raw',
    energyKcal: 333,
    proteinG: 22.9,
    fatG: 1.3,
    carbsG: 57.4,
    fiberG: 15.2,
    ironMg: 6.7,
    calciumMg: 138,
    sodiumMg: 24,
    potassiumMg: 1359,
    zincMg: 2.8,
    magnesiumMg: 140,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.52,
    riboflavinB2Mg: 0.18,
    niacinB3Mg: 2.1,
    folateMcg: 180,
    waterG: 12.0,
  },
  {
    foodCode: 'B007-RAW',
    name: 'Lentil, red, split, raw (Masoor dal)',
    commonNames: ['masoor dal', 'red lentil', 'masoor dal raw'],
    scientificName: 'Lens culinaris',
    category: 'Grain Legumes & Pulses',
    foodState: 'Raw',
    energyKcal: 343,
    proteinG: 25.1,
    fatG: 0.7,
    carbsG: 59.0,
    fiberG: 10.7,
    ironMg: 7.6,
    calciumMg: 69,
    sodiumMg: 15,
    potassiumMg: 780,
    zincMg: 3.2,
    magnesiumMg: 122,
    vitaminAMcg: 10,
    vitaminCMg: 0,
    thiamineB1Mg: 0.45,
    riboflavinB2Mg: 0.20,
    niacinB3Mg: 2.6,
    folateMcg: 125,
    waterG: 11.2,
  },
  {
    foodCode: 'B008-ROASTED',
    name: 'Roasted Bengal gram flour (Sattu / Pottukadalai)',
    commonNames: ['sattu', 'roasted chana', 'bhuna chana', 'pottukadalai', 'fried gram'],
    scientificName: 'Cicer arietinum',
    category: 'Grain Legumes & Pulses',
    foodState: 'Roasted / Puffed',
    energyKcal: 369,
    proteinG: 22.5,
    fatG: 5.2,
    carbsG: 58.1,
    fiberG: 16.8,
    ironMg: 9.5,
    calciumMg: 58,
    sodiumMg: 10,
    potassiumMg: 810,
    zincMg: 3.1,
    magnesiumMg: 142,
    vitaminAMcg: 11,
    vitaminCMg: 0,
    thiamineB1Mg: 0.38,
    riboflavinB2Mg: 0.16,
    niacinB3Mg: 2.1,
    folateMcg: 135,
    waterG: 7.2,
  },

  // --------------------------------------------------------------------
  // GREEN LEAFY VEGETABLES
  // --------------------------------------------------------------------
  {
    foodCode: 'C001-RAW',
    name: 'Spinach, raw (Palak / Pasalai Keerai)',
    commonNames: ['spinach', 'palak', 'pasalai keerai', 'raw spinach', 'spinach leaves'],
    scientificName: 'Spinacia oleracea',
    category: 'Green Leafy Vegetables',
    foodState: 'Raw',
    energyKcal: 26,
    proteinG: 2.0,
    fatG: 0.7,
    carbsG: 2.9,
    fiberG: 2.5,
    ironMg: 1.14,
    calciumMg: 73,
    sodiumMg: 58,
    potassiumMg: 340,
    zincMg: 0.53,
    magnesiumMg: 79,
    vitaminAMcg: 558,
    vitaminCMg: 28.1,
    thiamineB1Mg: 0.08,
    riboflavinB2Mg: 0.19,
    niacinB3Mg: 0.72,
    folateMcg: 123,
    waterG: 92.1,
  },
  {
    foodCode: 'C002-RAW',
    name: 'Fenugreek leaves, raw (Methi Keerai)',
    commonNames: ['methi leaves', 'fenugreek leaves', 'methi keerai', 'menthi kura'],
    scientificName: 'Trigonella foenum-graecum',
    category: 'Green Leafy Vegetables',
    foodState: 'Raw',
    energyKcal: 35,
    proteinG: 4.4,
    fatG: 0.9,
    carbsG: 6.0,
    fiberG: 4.9,
    ironMg: 1.9,
    calciumMg: 395,
    sodiumMg: 51,
    potassiumMg: 250,
    zincMg: 0.8,
    magnesiumMg: 67,
    vitaminAMcg: 420,
    vitaminCMg: 52.0,
    thiamineB1Mg: 0.05,
    riboflavinB2Mg: 0.31,
    niacinB3Mg: 0.8,
    folateMcg: 84,
    waterG: 86.1,
  },
  {
    foodCode: 'C003-RAW',
    name: 'Drumstick leaves, raw (Moringa / Murungai Keerai)',
    commonNames: ['moringa', 'moringa leaves', 'drumstick leaves', 'murungai keerai', 'munagaku'],
    scientificName: 'Moringa oleifera',
    category: 'Green Leafy Vegetables',
    foodState: 'Raw',
    energyKcal: 92,
    proteinG: 6.7,
    fatG: 1.7,
    carbsG: 12.5,
    fiberG: 6.8,
    ironMg: 0.85,
    calciumMg: 440,
    sodiumMg: 9,
    potassiumMg: 259,
    zincMg: 0.6,
    magnesiumMg: 42,
    vitaminAMcg: 750,
    vitaminCMg: 220.0,
    thiamineB1Mg: 0.26,
    riboflavinB2Mg: 0.66,
    niacinB3Mg: 0.82,
    folateMcg: 40,
    waterG: 75.9,
  },
  {
    foodCode: 'C004-RAW',
    name: 'Coriander leaves, raw (Koththamalli)',
    commonNames: ['coriander leaves', 'cilantro', 'koththamalli', 'hara dhaniya', 'kothimeera'],
    scientificName: 'Coriandrum sativum',
    category: 'Green Leafy Vegetables',
    foodState: 'Raw',
    energyKcal: 31,
    proteinG: 3.3,
    fatG: 0.6,
    carbsG: 3.7,
    fiberG: 4.2,
    ironMg: 1.42,
    calciumMg: 184,
    sodiumMg: 58,
    potassiumMg: 446,
    zincMg: 0.5,
    magnesiumMg: 31,
    vitaminAMcg: 590,
    vitaminCMg: 135.0,
    thiamineB1Mg: 0.05,
    riboflavinB2Mg: 0.15,
    niacinB3Mg: 0.8,
    folateMcg: 89,
    waterG: 87.9,
  },
  {
    foodCode: 'C005-RAW',
    name: 'Curry leaves, raw (Kariveppilai / Kadi Patta)',
    commonNames: ['curry leaves', 'kariveppilai', 'kadi patta', 'karivepaku'],
    scientificName: 'Murraya koenigii',
    category: 'Green Leafy Vegetables',
    foodState: 'Raw',
    energyKcal: 108,
    proteinG: 6.1,
    fatG: 1.0,
    carbsG: 18.7,
    fiberG: 6.4,
    ironMg: 0.93,
    calciumMg: 830,
    sodiumMg: 28,
    potassiumMg: 604,
    zincMg: 0.3,
    magnesiumMg: 44,
    vitaminAMcg: 320,
    vitaminCMg: 4.0,
    thiamineB1Mg: 0.08,
    riboflavinB2Mg: 0.21,
    niacinB3Mg: 2.3,
    folateMcg: 93,
    waterG: 63.8,
  },
  {
    foodCode: 'C006-RAW',
    name: 'Mint leaves, fresh raw (Pudina)',
    commonNames: ['mint', 'mint leaves', 'pudina'],
    scientificName: 'Mentha spicata',
    category: 'Green Leafy Vegetables',
    foodState: 'Raw',
    energyKcal: 37,
    proteinG: 4.8,
    fatG: 0.6,
    carbsG: 5.8,
    fiberG: 6.8,
    ironMg: 15.6,
    calciumMg: 200,
    sodiumMg: 31,
    potassiumMg: 458,
    zincMg: 0.9,
    magnesiumMg: 60,
    vitaminAMcg: 162,
    vitaminCMg: 27.0,
    thiamineB1Mg: 0.05,
    riboflavinB2Mg: 0.26,
    niacinB3Mg: 1.0,
    folateMcg: 114,
    waterG: 84.9,
  },

  // --------------------------------------------------------------------
  // OTHER VEGETABLES
  // --------------------------------------------------------------------
  {
    foodCode: 'D001-RAW',
    name: 'Cucumber, raw with skin (Vellarikkai / Kheera)',
    commonNames: ['cucumber', 'kheera', 'vellarikkai', 'dosakaya'],
    scientificName: 'Cucumis sativus',
    category: 'Other Vegetables',
    foodState: 'Raw',
    energyKcal: 15,
    proteinG: 0.6,
    fatG: 0.1,
    carbsG: 2.5,
    fiberG: 0.7,
    ironMg: 0.3,
    calciumMg: 14,
    sodiumMg: 2,
    potassiumMg: 147,
    zincMg: 0.2,
    magnesiumMg: 13,
    vitaminAMcg: 5,
    vitaminCMg: 2.8,
    thiamineB1Mg: 0.03,
    riboflavinB2Mg: 0.03,
    niacinB3Mg: 0.1,
    folateMcg: 7,
    waterG: 96.0,
  },
  {
    foodCode: 'D002-RAW',
    name: 'Tomato, ripe, raw (Thakkali / Tamatar)',
    commonNames: ['tomato', 'tamatar', 'thakkali', 'tomatoes'],
    scientificName: 'Solanum lycopersicum',
    category: 'Other Vegetables',
    foodState: 'Raw',
    energyKcal: 20,
    proteinG: 0.9,
    fatG: 0.2,
    carbsG: 3.6,
    fiberG: 1.2,
    ironMg: 0.4,
    calciumMg: 13,
    sodiumMg: 5,
    potassiumMg: 237,
    zincMg: 0.17,
    magnesiumMg: 11,
    vitaminAMcg: 42,
    vitaminCMg: 27.0,
    thiamineB1Mg: 0.04,
    riboflavinB2Mg: 0.02,
    niacinB3Mg: 0.6,
    folateMcg: 15,
    waterG: 94.0,
  },
  {
    foodCode: 'D003-RAW',
    name: 'Bitter gourd, raw (Karela / Pavakkai)',
    commonNames: ['bitter gourd', 'karela', 'pavakkai', 'kakarakaya'],
    scientificName: 'Momordica charantia',
    category: 'Other Vegetables',
    foodState: 'Raw',
    energyKcal: 25,
    proteinG: 1.6,
    fatG: 0.2,
    carbsG: 4.2,
    fiberG: 2.8,
    ironMg: 0.61,
    calciumMg: 20,
    sodiumMg: 6,
    potassiumMg: 319,
    zincMg: 0.8,
    magnesiumMg: 16,
    vitaminAMcg: 24,
    vitaminCMg: 88.0,
    thiamineB1Mg: 0.07,
    riboflavinB2Mg: 0.09,
    niacinB3Mg: 0.5,
    folateMcg: 72,
    waterG: 92.4,
  },
  {
    foodCode: 'D004-RAW',
    name: 'Bottle gourd, raw (Lauki / Sorakkai)',
    commonNames: ['bottle gourd', 'lauki', 'sorakkai', 'anapakaya', 'ghiya'],
    scientificName: 'Lagenaria siceraria',
    category: 'Other Vegetables',
    foodState: 'Raw',
    energyKcal: 12,
    proteinG: 0.5,
    fatG: 0.1,
    carbsG: 2.2,
    fiberG: 1.2,
    ironMg: 0.43,
    calciumMg: 20,
    sodiumMg: 2,
    potassiumMg: 87,
    zincMg: 0.15,
    magnesiumMg: 11,
    vitaminAMcg: 4,
    vitaminCMg: 11.0,
    thiamineB1Mg: 0.03,
    riboflavinB2Mg: 0.02,
    niacinB3Mg: 0.3,
    folateMcg: 6,
    waterG: 96.1,
  },
  {
    foodCode: 'D005-RAW',
    name: 'Ridge gourd, raw (Turai / Peerkangai)',
    commonNames: ['ridge gourd', 'turai', 'peerkangai', 'beerakaya', 'torai'],
    scientificName: 'Luffa acutangula',
    category: 'Other Vegetables',
    foodState: 'Raw',
    energyKcal: 16,
    proteinG: 0.5,
    fatG: 0.1,
    carbsG: 3.4,
    fiberG: 1.5,
    ironMg: 0.4,
    calciumMg: 18,
    sodiumMg: 3,
    potassiumMg: 160,
    zincMg: 0.2,
    magnesiumMg: 14,
    vitaminAMcg: 18,
    vitaminCMg: 5.4,
    thiamineB1Mg: 0.03,
    riboflavinB2Mg: 0.01,
    niacinB3Mg: 0.2,
    folateMcg: 8,
    waterG: 95.3,
  },
  {
    foodCode: 'D006-RAW',
    name: "Lady's finger / Okra, raw (Bhindi / Vendakkai)",
    commonNames: ['okra', 'bhindi', 'vendakkai', 'bhendi', 'ladys finger', "lady's finger"],
    scientificName: 'Abelmoschus esculentus',
    category: 'Other Vegetables',
    foodState: 'Raw',
    energyKcal: 33,
    proteinG: 1.9,
    fatG: 0.2,
    carbsG: 6.4,
    fiberG: 3.2,
    ironMg: 0.4,
    calciumMg: 66,
    sodiumMg: 7,
    potassiumMg: 103,
    zincMg: 0.43,
    magnesiumMg: 53,
    vitaminAMcg: 36,
    vitaminCMg: 13.0,
    thiamineB1Mg: 0.07,
    riboflavinB2Mg: 0.06,
    niacinB3Mg: 1.0,
    folateMcg: 88,
    waterG: 89.6,
  },
  {
    foodCode: 'D007-RAW',
    name: 'Cabbage, raw (Muttaikose / Patta Gobhi)',
    commonNames: ['cabbage', 'muttaikose', 'patta gobhi', 'cabbage raw'],
    scientificName: 'Brassica oleracea var. capitata',
    category: 'Other Vegetables',
    foodState: 'Raw',
    energyKcal: 27,
    proteinG: 1.3,
    fatG: 0.1,
    carbsG: 4.6,
    fiberG: 2.5,
    ironMg: 0.47,
    calciumMg: 39,
    sodiumMg: 18,
    potassiumMg: 170,
    zincMg: 0.18,
    magnesiumMg: 12,
    vitaminAMcg: 5,
    vitaminCMg: 36.6,
    thiamineB1Mg: 0.06,
    riboflavinB2Mg: 0.04,
    niacinB3Mg: 0.2,
    folateMcg: 43,
    waterG: 91.9,
  },
  {
    foodCode: 'D008-RAW',
    name: 'French beans, raw (Beans)',
    commonNames: ['french beans', 'green beans', 'beans', 'string beans'],
    scientificName: 'Phaseolus vulgaris',
    category: 'Other Vegetables',
    foodState: 'Raw',
    energyKcal: 26,
    proteinG: 1.7,
    fatG: 0.1,
    carbsG: 4.5,
    fiberG: 3.4,
    ironMg: 0.61,
    calciumMg: 50,
    sodiumMg: 6,
    potassiumMg: 209,
    zincMg: 0.24,
    magnesiumMg: 25,
    vitaminAMcg: 35,
    vitaminCMg: 11.0,
    thiamineB1Mg: 0.08,
    riboflavinB2Mg: 0.09,
    niacinB3Mg: 0.6,
    folateMcg: 33,
    waterG: 90.3,
  },
  {
    foodCode: 'D009-RAW',
    name: 'Drumstick pods, raw (Murungakkai / Sehjan)',
    commonNames: ['drumstick', 'murungakkai', 'sehjan', 'drumstick pod'],
    scientificName: 'Moringa oleifera',
    category: 'Other Vegetables',
    foodState: 'Raw',
    energyKcal: 26,
    proteinG: 2.5,
    fatG: 0.1,
    carbsG: 3.7,
    fiberG: 4.8,
    ironMg: 0.36,
    calciumMg: 30,
    sodiumMg: 9,
    potassiumMg: 259,
    zincMg: 0.45,
    magnesiumMg: 45,
    vitaminAMcg: 4,
    vitaminCMg: 120.0,
    thiamineB1Mg: 0.05,
    riboflavinB2Mg: 0.07,
    niacinB3Mg: 0.2,
    folateMcg: 44,
    waterG: 88.2,
  },

  // --------------------------------------------------------------------
  // ROOTS & TUBERS
  // --------------------------------------------------------------------
  {
    foodCode: 'E001-RAW',
    name: 'Carrot, orange, raw (Gajar)',
    commonNames: ['carrot', 'gajar', 'carrots', 'orange carrot'],
    scientificName: 'Daucus carota',
    category: 'Roots & Tubers',
    foodState: 'Raw',
    energyKcal: 41,
    proteinG: 0.9,
    fatG: 0.2,
    carbsG: 8.8,
    fiberG: 2.8,
    ironMg: 0.3,
    calciumMg: 33,
    sodiumMg: 69,
    potassiumMg: 320,
    zincMg: 0.24,
    magnesiumMg: 12,
    vitaminAMcg: 835,
    vitaminCMg: 5.9,
    thiamineB1Mg: 0.06,
    riboflavinB2Mg: 0.05,
    niacinB3Mg: 0.98,
    folateMcg: 19,
    waterG: 88.3,
  },
  {
    foodCode: 'E002-RAW',
    name: 'Beetroot, raw (Chukandar)',
    commonNames: ['beetroot', 'beet', 'chukandar'],
    scientificName: 'Beta vulgaris',
    category: 'Roots & Tubers',
    foodState: 'Raw',
    energyKcal: 43,
    proteinG: 1.6,
    fatG: 0.2,
    carbsG: 8.8,
    fiberG: 2.8,
    ironMg: 0.8,
    calciumMg: 16,
    sodiumMg: 78,
    potassiumMg: 325,
    zincMg: 0.35,
    magnesiumMg: 23,
    vitaminAMcg: 2,
    vitaminCMg: 4.9,
    thiamineB1Mg: 0.03,
    riboflavinB2Mg: 0.04,
    niacinB3Mg: 0.33,
    folateMcg: 109,
    waterG: 87.6,
  },
  {
    foodCode: 'E003-RAW',
    name: 'Radish, white, raw (Mullangi / Mooli)',
    commonNames: ['radish', 'white radish', 'mooli', 'mullangi'],
    scientificName: 'Raphanus sativus',
    category: 'Roots & Tubers',
    foodState: 'Raw',
    energyKcal: 16,
    proteinG: 0.7,
    fatG: 0.1,
    carbsG: 3.4,
    fiberG: 1.6,
    ironMg: 0.4,
    calciumMg: 35,
    sodiumMg: 39,
    potassiumMg: 233,
    zincMg: 0.28,
    magnesiumMg: 10,
    vitaminAMcg: 0,
    vitaminCMg: 14.8,
    thiamineB1Mg: 0.06,
    riboflavinB2Mg: 0.02,
    niacinB3Mg: 0.5,
    folateMcg: 25,
    waterG: 94.4,
  },
  {
    foodCode: 'E004-RAW',
    name: 'Onion, red, raw (Vengayam / Pyaz)',
    commonNames: ['onion', 'pyaz', 'vengayam', 'shallots', 'red onion'],
    scientificName: 'Allium cepa',
    category: 'Roots & Tubers',
    foodState: 'Raw',
    energyKcal: 40,
    proteinG: 1.1,
    fatG: 0.1,
    carbsG: 8.9,
    fiberG: 1.7,
    ironMg: 0.21,
    calciumMg: 23,
    sodiumMg: 4,
    potassiumMg: 146,
    zincMg: 0.17,
    magnesiumMg: 10,
    vitaminAMcg: 0,
    vitaminCMg: 7.4,
    thiamineB1Mg: 0.04,
    riboflavinB2Mg: 0.02,
    niacinB3Mg: 0.12,
    folateMcg: 19,
    waterG: 89.1,
  },

  // --------------------------------------------------------------------
  // NUTS & OILSEEDS
  // --------------------------------------------------------------------
  {
    foodCode: 'F001-RAW',
    name: 'Almonds, raw with skin (Badam)',
    commonNames: ['almonds', 'almond', 'badam', 'soaked almonds'],
    scientificName: 'Prunus dulcis',
    category: 'Nuts & Oilseeds',
    foodState: 'Raw',
    energyKcal: 579,
    proteinG: 21.2,
    fatG: 49.9,
    carbsG: 21.6,
    fiberG: 12.5,
    ironMg: 3.71,
    calciumMg: 264,
    sodiumMg: 1,
    potassiumMg: 733,
    zincMg: 3.12,
    magnesiumMg: 270,
    vitaminAMcg: 1,
    vitaminCMg: 0,
    thiamineB1Mg: 0.21,
    riboflavinB2Mg: 1.14,
    niacinB3Mg: 3.6,
    folateMcg: 44,
    waterG: 4.7,
  },
  {
    foodCode: 'F002-RAW',
    name: 'Walnuts, raw (Akhrot)',
    commonNames: ['walnuts', 'walnut', 'akhrot'],
    scientificName: 'Juglans regia',
    category: 'Nuts & Oilseeds',
    foodState: 'Raw',
    energyKcal: 654,
    proteinG: 15.2,
    fatG: 65.2,
    carbsG: 13.7,
    fiberG: 6.7,
    ironMg: 2.91,
    calciumMg: 98,
    sodiumMg: 2,
    potassiumMg: 441,
    zincMg: 3.09,
    magnesiumMg: 158,
    vitaminAMcg: 2,
    vitaminCMg: 1.3,
    thiamineB1Mg: 0.34,
    riboflavinB2Mg: 0.15,
    niacinB3Mg: 1.12,
    folateMcg: 98,
    waterG: 4.1,
  },
  {
    foodCode: 'F003-RAW',
    name: 'Flaxseeds, raw (Alsi)',
    commonNames: ['flaxseeds', 'flax seeds', 'alsi', 'linseeds'],
    scientificName: 'Linum usitatissimum',
    category: 'Nuts & Oilseeds',
    foodState: 'Raw',
    energyKcal: 534,
    proteinG: 18.3,
    fatG: 42.2,
    carbsG: 28.9,
    fiberG: 27.3,
    ironMg: 5.73,
    calciumMg: 255,
    sodiumMg: 30,
    potassiumMg: 813,
    zincMg: 4.34,
    magnesiumMg: 392,
    vitaminAMcg: 0,
    vitaminCMg: 0.6,
    thiamineB1Mg: 1.64,
    riboflavinB2Mg: 0.16,
    niacinB3Mg: 3.08,
    folateMcg: 87,
    waterG: 6.9,
  },
  {
    foodCode: 'F004-RAW',
    name: 'Chia seeds, raw',
    commonNames: ['chia seeds', 'chia seed', 'chia'],
    scientificName: 'Salvia hispanica',
    category: 'Nuts & Oilseeds',
    foodState: 'Raw',
    energyKcal: 486,
    proteinG: 16.5,
    fatG: 30.7,
    carbsG: 42.1,
    fiberG: 34.4,
    ironMg: 7.72,
    calciumMg: 631,
    sodiumMg: 16,
    potassiumMg: 407,
    zincMg: 4.58,
    magnesiumMg: 335,
    vitaminAMcg: 5,
    vitaminCMg: 1.6,
    thiamineB1Mg: 0.62,
    riboflavinB2Mg: 0.17,
    niacinB3Mg: 8.83,
    folateMcg: 49,
    waterG: 5.8,
  },
  {
    foodCode: 'F005-RAW',
    name: 'Pumpkin seeds, raw (Kaddu ke beej)',
    commonNames: ['pumpkin seeds', 'pepitas', 'kaddu beej'],
    scientificName: 'Cucurbita pepo',
    category: 'Nuts & Oilseeds',
    foodState: 'Raw',
    energyKcal: 559,
    proteinG: 30.2,
    fatG: 49.1,
    carbsG: 10.7,
    fiberG: 6.0,
    ironMg: 8.82,
    calciumMg: 55,
    sodiumMg: 7,
    potassiumMg: 809,
    zincMg: 7.81,
    magnesiumMg: 592,
    vitaminAMcg: 1,
    vitaminCMg: 1.9,
    thiamineB1Mg: 0.27,
    riboflavinB2Mg: 0.15,
    niacinB3Mg: 4.99,
    folateMcg: 58,
    waterG: 5.2,
  },
  {
    foodCode: 'F006-RAW',
    name: 'Sesame seeds, white, raw (Til / Ellu)',
    commonNames: ['sesame seeds', 'til', 'ellu', 'gingelly seeds'],
    scientificName: 'Sesamum indicum',
    category: 'Nuts & Oilseeds',
    foodState: 'Raw',
    energyKcal: 573,
    proteinG: 17.7,
    fatG: 49.7,
    carbsG: 23.4,
    fiberG: 11.8,
    ironMg: 14.55,
    calciumMg: 975,
    sodiumMg: 11,
    potassiumMg: 468,
    zincMg: 7.75,
    magnesiumMg: 351,
    vitaminAMcg: 1,
    vitaminCMg: 0,
    thiamineB1Mg: 0.79,
    riboflavinB2Mg: 0.25,
    niacinB3Mg: 4.52,
    folateMcg: 97,
    waterG: 4.7,
  },
  {
    foodCode: 'F007-RAW',
    name: 'Coconut, fresh kernel, raw (Thengai / Nariyal)',
    commonNames: ['coconut', 'fresh coconut', 'grated coconut', 'thengai', 'nariyal'],
    scientificName: 'Cocos nucifera',
    category: 'Nuts & Oilseeds',
    foodState: 'Raw',
    energyKcal: 354,
    proteinG: 3.3,
    fatG: 33.5,
    carbsG: 15.2,
    fiberG: 9.0,
    ironMg: 2.43,
    calciumMg: 14,
    sodiumMg: 20,
    potassiumMg: 356,
    zincMg: 1.1,
    magnesiumMg: 32,
    vitaminAMcg: 0,
    vitaminCMg: 3.3,
    thiamineB1Mg: 0.07,
    riboflavinB2Mg: 0.02,
    niacinB3Mg: 0.54,
    folateMcg: 26,
    waterG: 47.0,
  },

  // --------------------------------------------------------------------
  // CONDIMENTS & SPICES
  // --------------------------------------------------------------------
  {
    foodCode: 'G001-RAW',
    name: 'Fenugreek seeds, dry, raw (Methi / Vendhayam)',
    commonNames: ['fenugreek seeds', 'methi seeds', 'vendhayam', 'methi dana', 'menthulu'],
    scientificName: 'Trigonella foenum-graecum',
    category: 'Condiments & Spices',
    foodState: 'Raw',
    energyKcal: 323,
    proteinG: 26.2,
    fatG: 5.8,
    carbsG: 44.1,
    fiberG: 24.6,
    ironMg: 33.8,
    calciumMg: 178,
    sodiumMg: 67,
    potassiumMg: 770,
    zincMg: 6.7,
    magnesiumMg: 191,
    vitaminAMcg: 0,
    vitaminCMg: 3.0,
    thiamineB1Mg: 0.32,
    riboflavinB2Mg: 0.36,
    niacinB3Mg: 1.6,
    folateMcg: 57,
    waterG: 8.8,
  },
  {
    foodCode: 'G002-RAW',
    name: 'Cumin seeds, raw (Jeera / Seeragam)',
    commonNames: ['cumin', 'jeera', 'seeragam', 'cumin seeds', 'jeerakam'],
    scientificName: 'Cuminum cyminum',
    category: 'Condiments & Spices',
    foodState: 'Raw',
    energyKcal: 375,
    proteinG: 17.8,
    fatG: 22.3,
    carbsG: 44.2,
    fiberG: 10.5,
    ironMg: 66.4,
    calciumMg: 931,
    sodiumMg: 168,
    potassiumMg: 1788,
    zincMg: 4.8,
    magnesiumMg: 366,
    vitaminAMcg: 64,
    vitaminCMg: 7.7,
    thiamineB1Mg: 0.63,
    riboflavinB2Mg: 0.33,
    niacinB3Mg: 4.6,
    folateMcg: 10,
    waterG: 8.1,
  },
  {
    foodCode: 'G003-RAW',
    name: 'Mustard seeds, raw (Rai / Kadugu)',
    commonNames: ['mustard seeds', 'mustard', 'rai', 'kadugu', 'avalu'],
    scientificName: 'Brassica nigra',
    category: 'Condiments & Spices',
    foodState: 'Raw',
    energyKcal: 508,
    proteinG: 26.1,
    fatG: 36.2,
    carbsG: 28.1,
    fiberG: 12.2,
    ironMg: 7.9,
    calciumMg: 490,
    sodiumMg: 13,
    potassiumMg: 738,
    zincMg: 6.1,
    magnesiumMg: 370,
    vitaminAMcg: 2,
    vitaminCMg: 7.1,
    thiamineB1Mg: 0.82,
    riboflavinB2Mg: 0.26,
    niacinB3Mg: 4.7,
    folateMcg: 162,
    waterG: 6.5,
  },
  {
    foodCode: 'G004-RAW',
    name: 'Turmeric powder, pure (Haldi / Manjal)',
    commonNames: ['turmeric', 'haldi', 'manjal', 'turmeric powder'],
    scientificName: 'Curcuma longa',
    category: 'Condiments & Spices',
    foodState: 'Raw',
    energyKcal: 312,
    proteinG: 7.8,
    fatG: 9.9,
    carbsG: 64.9,
    fiberG: 21.1,
    ironMg: 41.4,
    calciumMg: 182,
    sodiumMg: 38,
    potassiumMg: 2525,
    zincMg: 4.5,
    magnesiumMg: 193,
    vitaminAMcg: 0,
    vitaminCMg: 25.9,
    thiamineB1Mg: 0.15,
    riboflavinB2Mg: 0.23,
    niacinB3Mg: 5.1,
    folateMcg: 39,
    waterG: 11.4,
  },
  {
    foodCode: 'G005-RAW',
    name: 'Black pepper, raw (Kali Mirch / Milagu)',
    commonNames: ['black pepper', 'pepper', 'milagu', 'kali mirch'],
    scientificName: 'Piper nigrum',
    category: 'Condiments & Spices',
    foodState: 'Raw',
    energyKcal: 251,
    proteinG: 10.4,
    fatG: 3.3,
    carbsG: 64.0,
    fiberG: 25.3,
    ironMg: 9.7,
    calciumMg: 443,
    sodiumMg: 20,
    potassiumMg: 1329,
    zincMg: 1.3,
    magnesiumMg: 171,
    vitaminAMcg: 15,
    vitaminCMg: 0,
    thiamineB1Mg: 0.11,
    riboflavinB2Mg: 0.18,
    niacinB3Mg: 1.1,
    folateMcg: 17,
    waterG: 12.5,
  },
  {
    foodCode: 'G006-RAW',
    name: 'Ginger, fresh raw (Inji / Adrak)',
    commonNames: ['ginger', 'adrak', 'inji', 'allam', 'fresh ginger'],
    scientificName: 'Zingiber officinale',
    category: 'Condiments & Spices',
    foodState: 'Raw',
    energyKcal: 80,
    proteinG: 1.8,
    fatG: 0.7,
    carbsG: 17.8,
    fiberG: 2.0,
    ironMg: 0.6,
    calciumMg: 16,
    sodiumMg: 13,
    potassiumMg: 415,
    zincMg: 0.34,
    magnesiumMg: 43,
    vitaminAMcg: 0,
    vitaminCMg: 5.0,
    thiamineB1Mg: 0.02,
    riboflavinB2Mg: 0.03,
    niacinB3Mg: 0.75,
    folateMcg: 11,
    waterG: 78.9,
  },
  {
    foodCode: 'G007-RAW',
    name: 'Garlic, raw (Poondu / Lahsun)',
    commonNames: ['garlic', 'lahsun', 'poondu', 'vellulli', 'raw garlic'],
    scientificName: 'Allium sativum',
    category: 'Condiments & Spices',
    foodState: 'Raw',
    energyKcal: 149,
    proteinG: 6.4,
    fatG: 0.5,
    carbsG: 33.1,
    fiberG: 2.1,
    ironMg: 1.7,
    calciumMg: 181,
    sodiumMg: 17,
    potassiumMg: 401,
    zincMg: 1.16,
    magnesiumMg: 25,
    vitaminAMcg: 0,
    vitaminCMg: 31.2,
    thiamineB1Mg: 0.20,
    riboflavinB2Mg: 0.11,
    niacinB3Mg: 0.70,
    folateMcg: 3,
    waterG: 58.6,
  },
  {
    foodCode: 'G008-RAW',
    name: 'Cinnamon bark, pure (Dalchini / Pattai)',
    commonNames: ['cinnamon', 'dalchini', 'pattai', 'ceylon cinnamon'],
    scientificName: 'Cinnamomum verum',
    category: 'Condiments & Spices',
    foodState: 'Raw',
    energyKcal: 247,
    proteinG: 4.0,
    fatG: 1.2,
    carbsG: 80.6,
    fiberG: 53.1,
    ironMg: 8.3,
    calciumMg: 1002,
    sodiumMg: 10,
    potassiumMg: 431,
    zincMg: 1.83,
    magnesiumMg: 60,
    vitaminAMcg: 15,
    vitaminCMg: 3.8,
    thiamineB1Mg: 0.02,
    riboflavinB2Mg: 0.04,
    niacinB3Mg: 1.3,
    folateMcg: 6,
    waterG: 10.6,
  },

  // --------------------------------------------------------------------
  // FRUITS
  // --------------------------------------------------------------------
  {
    foodCode: 'H001-RAW',
    name: 'Guava, whole with skin, raw (Koyyapazham / Amrood)',
    commonNames: ['guava', 'amrood', 'koyya', 'koyyapazham', 'fresh guava'],
    scientificName: 'Psidium guajava',
    category: 'Fruits',
    foodState: 'Raw',
    energyKcal: 68,
    proteinG: 2.6,
    fatG: 0.9,
    carbsG: 14.3,
    fiberG: 5.4,
    ironMg: 0.26,
    calciumMg: 18,
    sodiumMg: 2,
    potassiumMg: 417,
    zincMg: 0.23,
    magnesiumMg: 22,
    vitaminAMcg: 31,
    vitaminCMg: 228.3,
    thiamineB1Mg: 0.07,
    riboflavinB2Mg: 0.04,
    niacinB3Mg: 1.08,
    folateMcg: 49,
    waterG: 80.8,
  },
  {
    foodCode: 'H002-RAW',
    name: 'Indian Gooseberry, raw (Amla / Nellikai)',
    commonNames: ['amla', 'nellikai', 'indian gooseberry', 'usirikaya'],
    scientificName: 'Phyllanthus emblica',
    category: 'Fruits',
    foodState: 'Raw',
    energyKcal: 44,
    proteinG: 0.5,
    fatG: 0.1,
    carbsG: 10.1,
    fiberG: 3.4,
    ironMg: 1.2,
    calciumMg: 25,
    sodiumMg: 1,
    potassiumMg: 225,
    zincMg: 0.12,
    magnesiumMg: 10,
    vitaminAMcg: 9,
    vitaminCMg: 600.0,
    thiamineB1Mg: 0.03,
    riboflavinB2Mg: 0.01,
    niacinB3Mg: 0.2,
    folateMcg: 8,
    waterG: 85.3,
  },
  {
    foodCode: 'H003-RAW',
    name: 'Papaya, ripe, raw (Pappali / Papita)',
    commonNames: ['papaya', 'papita', 'pappali', 'ripe papaya'],
    scientificName: 'Carica papaya',
    category: 'Fruits',
    foodState: 'Raw',
    energyKcal: 43,
    proteinG: 0.5,
    fatG: 0.3,
    carbsG: 10.8,
    fiberG: 1.7,
    ironMg: 0.25,
    calciumMg: 20,
    sodiumMg: 8,
    potassiumMg: 182,
    zincMg: 0.08,
    magnesiumMg: 21,
    vitaminAMcg: 47,
    vitaminCMg: 62.0,
    thiamineB1Mg: 0.03,
    riboflavinB2Mg: 0.03,
    niacinB3Mg: 0.36,
    folateMcg: 38,
    waterG: 88.1,
  },
  {
    foodCode: 'H004-RAW',
    name: 'Pomegranate, raw arils (Madulai / Anar)',
    commonNames: ['pomegranate', 'anar', 'madulai', 'danimma'],
    scientificName: 'Punica granatum',
    category: 'Fruits',
    foodState: 'Raw',
    energyKcal: 83,
    proteinG: 1.7,
    fatG: 1.2,
    carbsG: 18.7,
    fiberG: 4.0,
    ironMg: 0.30,
    calciumMg: 10,
    sodiumMg: 3,
    potassiumMg: 236,
    zincMg: 0.35,
    magnesiumMg: 12,
    vitaminAMcg: 0,
    vitaminCMg: 10.2,
    thiamineB1Mg: 0.07,
    riboflavinB2Mg: 0.05,
    niacinB3Mg: 0.29,
    folateMcg: 38,
    waterG: 77.9,
  },
  {
    foodCode: 'H005-RAW',
    name: 'Apple, with skin, raw (Seb)',
    commonNames: ['apple', 'seb', 'apples', 'green apple'],
    scientificName: 'Malus domestica',
    category: 'Fruits',
    foodState: 'Raw',
    energyKcal: 52,
    proteinG: 0.3,
    fatG: 0.2,
    carbsG: 13.8,
    fiberG: 2.4,
    ironMg: 0.12,
    calciumMg: 6,
    sodiumMg: 1,
    potassiumMg: 107,
    zincMg: 0.04,
    magnesiumMg: 5,
    vitaminAMcg: 3,
    vitaminCMg: 4.6,
    thiamineB1Mg: 0.02,
    riboflavinB2Mg: 0.03,
    niacinB3Mg: 0.09,
    folateMcg: 3,
    waterG: 85.6,
  },
  {
    foodCode: 'H006-RAW',
    name: 'Banana, ripe, raw (Vazhaipazham / Kela)',
    commonNames: ['banana', 'kela', 'vazhaipazham', 'arati pandu'],
    scientificName: 'Musa acuminata',
    category: 'Fruits',
    foodState: 'Raw',
    energyKcal: 89,
    proteinG: 1.1,
    fatG: 0.3,
    carbsG: 22.8,
    fiberG: 2.6,
    ironMg: 0.26,
    calciumMg: 5,
    sodiumMg: 1,
    potassiumMg: 358,
    zincMg: 0.15,
    magnesiumMg: 27,
    vitaminAMcg: 4,
    vitaminCMg: 8.7,
    thiamineB1Mg: 0.03,
    riboflavinB2Mg: 0.07,
    niacinB3Mg: 0.67,
    folateMcg: 20,
    waterG: 74.9,
  },

  // --------------------------------------------------------------------
  // MILK & MILK PRODUCTS
  // --------------------------------------------------------------------
  {
    foodCode: 'I001-LIQ',
    name: 'Cow Milk, toned (3% fat)',
    commonNames: ['cow milk', 'milk', 'toned milk', 'pasum paal', 'doodh'],
    category: 'Milk & Milk Products',
    foodState: 'Liquid',
    energyKcal: 58,
    proteinG: 3.2,
    fatG: 3.0,
    carbsG: 4.7,
    fiberG: 0,
    ironMg: 0.10,
    calciumMg: 120,
    sodiumMg: 50,
    potassiumMg: 140,
    zincMg: 0.38,
    magnesiumMg: 12,
    vitaminAMcg: 32,
    vitaminCMg: 1.0,
    thiamineB1Mg: 0.05,
    riboflavinB2Mg: 0.19,
    niacinB3Mg: 0.10,
    folateMcg: 5,
    waterG: 88.0,
  },
  {
    foodCode: 'I002-LIQ',
    name: 'Cow Milk, skimmed (0.5% fat)',
    commonNames: ['skimmed milk', 'low fat milk', 'skim milk', 'fat free milk'],
    category: 'Milk & Milk Products',
    foodState: 'Liquid',
    energyKcal: 35,
    proteinG: 3.4,
    fatG: 0.5,
    carbsG: 4.9,
    fiberG: 0,
    ironMg: 0.08,
    calciumMg: 125,
    sodiumMg: 52,
    potassiumMg: 150,
    zincMg: 0.40,
    magnesiumMg: 13,
    vitaminAMcg: 2,
    vitaminCMg: 1.0,
    thiamineB1Mg: 0.05,
    riboflavinB2Mg: 0.20,
    niacinB3Mg: 0.10,
    folateMcg: 5,
    waterG: 90.5,
  },
  {
    foodCode: 'I003-FERM',
    name: 'Curd / Yogurt, whole cow milk (Thayir / Dahi)',
    commonNames: ['curd', 'dahi', 'thayir', 'yogurt', 'plain curd', 'perugu'],
    category: 'Milk & Milk Products',
    foodState: 'Fermented',
    energyKcal: 60,
    proteinG: 3.1,
    fatG: 3.0,
    carbsG: 4.4,
    fiberG: 0,
    ironMg: 0.10,
    calciumMg: 120,
    sodiumMg: 45,
    potassiumMg: 140,
    zincMg: 0.40,
    magnesiumMg: 12,
    vitaminAMcg: 30,
    vitaminCMg: 1.0,
    thiamineB1Mg: 0.05,
    riboflavinB2Mg: 0.16,
    niacinB3Mg: 0.10,
    folateMcg: 18,
    waterG: 88.0,
  },
  {
    foodCode: 'I004-LIQ',
    name: 'Buttermilk, plain diluted (Neer Mor / Chaas)',
    commonNames: ['buttermilk', 'neer mor', 'chaas', 'majjiga', 'diluted curd'],
    category: 'Milk & Milk Products',
    foodState: 'Liquid',
    energyKcal: 20,
    proteinG: 1.2,
    fatG: 0.8,
    carbsG: 1.8,
    fiberG: 0,
    ironMg: 0.04,
    calciumMg: 45,
    sodiumMg: 25,
    potassiumMg: 65,
    zincMg: 0.15,
    magnesiumMg: 5,
    vitaminAMcg: 10,
    vitaminCMg: 0.5,
    thiamineB1Mg: 0.02,
    riboflavinB2Mg: 0.06,
    niacinB3Mg: 0.04,
    folateMcg: 7,
    waterG: 95.8,
  },
  {
    foodCode: 'I005-SOLID',
    name: 'Paneer, cow milk (Cottage cheese)',
    commonNames: ['paneer', 'cottage cheese', 'paneer raw', 'cow paneer'],
    category: 'Milk & Milk Products',
    foodState: 'Raw',
    energyKcal: 265,
    proteinG: 18.3,
    fatG: 20.8,
    carbsG: 1.2,
    fiberG: 0,
    ironMg: 0.4,
    calciumMg: 480,
    sodiumMg: 22,
    potassiumMg: 120,
    zincMg: 2.1,
    magnesiumMg: 18,
    vitaminAMcg: 140,
    vitaminCMg: 0,
    thiamineB1Mg: 0.06,
    riboflavinB2Mg: 0.28,
    niacinB3Mg: 0.15,
    folateMcg: 22,
    waterG: 54.0,
  },

  // --------------------------------------------------------------------
  // EGG, POULTRY & FISH
  // --------------------------------------------------------------------
  {
    foodCode: 'I006-RAW',
    name: 'Egg white, hen, raw',
    commonNames: ['egg white', 'egg whites', 'boiled egg white', 'muttai venkaru'],
    category: 'Egg, Poultry & Fish',
    foodState: 'Raw',
    energyKcal: 52,
    proteinG: 10.9,
    fatG: 0.2,
    carbsG: 0.7,
    fiberG: 0,
    ironMg: 0.08,
    calciumMg: 7,
    sodiumMg: 166,
    potassiumMg: 163,
    zincMg: 0.03,
    magnesiumMg: 11,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0.01,
    riboflavinB2Mg: 0.44,
    niacinB3Mg: 0.11,
    folateMcg: 4,
    waterG: 87.6,
  },
  {
    foodCode: 'I007-RAW',
    name: 'Fish, Mackerel, raw (Ayala / Bangda)',
    commonNames: ['mackerel', 'ayala', 'bangda', 'fish fillet', 'fish'],
    scientificName: 'Rastrelliger kanagurta',
    category: 'Egg, Poultry & Fish',
    foodState: 'Raw',
    energyKcal: 189,
    proteinG: 19.3,
    fatG: 11.9,
    carbsG: 0,
    fiberG: 0,
    ironMg: 1.4,
    calciumMg: 24,
    sodiumMg: 90,
    potassiumMg: 314,
    zincMg: 0.78,
    magnesiumMg: 28,
    vitaminAMcg: 45,
    vitaminCMg: 0.4,
    thiamineB1Mg: 0.14,
    riboflavinB2Mg: 0.31,
    niacinB3Mg: 8.2,
    folateMcg: 15,
    waterG: 67.5,
  },

  // --------------------------------------------------------------------
  // FATS & EDIBLE OILS
  // --------------------------------------------------------------------
  {
    foodCode: 'J001-FAT',
    name: 'Gingelly oil / Sesame oil, pure',
    commonNames: ['sesame oil', 'gingelly oil', 'nallennai', 'til oil'],
    category: 'Fats & Edible Oils',
    foodState: 'Liquid',
    energyKcal: 900,
    proteinG: 0,
    fatG: 100.0,
    carbsG: 0,
    fiberG: 0,
    ironMg: 0,
    calciumMg: 0,
    sodiumMg: 0,
    potassiumMg: 0,
    zincMg: 0,
    magnesiumMg: 0,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0,
    riboflavinB2Mg: 0,
    niacinB3Mg: 0,
    folateMcg: 0,
    waterG: 0,
  },
  {
    foodCode: 'J002-FAT',
    name: 'Mustard oil, pure',
    commonNames: ['mustard oil', 'sarson tel'],
    category: 'Fats & Edible Oils',
    foodState: 'Liquid',
    energyKcal: 900,
    proteinG: 0,
    fatG: 100.0,
    carbsG: 0,
    fiberG: 0,
    ironMg: 0,
    calciumMg: 0,
    sodiumMg: 0,
    potassiumMg: 0,
    zincMg: 0,
    magnesiumMg: 0,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0,
    riboflavinB2Mg: 0,
    niacinB3Mg: 0,
    folateMcg: 0,
    waterG: 0,
  },
  {
    foodCode: 'J003-FAT',
    name: 'Desi Cow Ghee, clarified butter',
    commonNames: ['ghee', 'cow ghee', 'desi ghee', 'nei'],
    category: 'Fats & Edible Oils',
    foodState: 'Liquid',
    energyKcal: 897,
    proteinG: 0,
    fatG: 99.5,
    carbsG: 0,
    fiberG: 0,
    ironMg: 0,
    calciumMg: 0,
    sodiumMg: 0,
    potassiumMg: 0,
    zincMg: 0,
    magnesiumMg: 0,
    vitaminAMcg: 600,
    vitaminCMg: 0,
    thiamineB1Mg: 0,
    riboflavinB2Mg: 0,
    niacinB3Mg: 0,
    folateMcg: 0,
    waterG: 0.5,
  },
  {
    foodCode: 'J004-FAT',
    name: 'Groundnut oil / Peanut oil, pure',
    commonNames: ['groundnut oil', 'peanut oil', 'kadala ennai', 'sing tel'],
    category: 'Fats & Edible Oils',
    foodState: 'Liquid',
    energyKcal: 900,
    proteinG: 0,
    fatG: 100.0,
    carbsG: 0,
    fiberG: 0,
    ironMg: 0,
    calciumMg: 0,
    sodiumMg: 0,
    potassiumMg: 0,
    zincMg: 0,
    magnesiumMg: 0,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0,
    riboflavinB2Mg: 0,
    niacinB3Mg: 0,
    folateMcg: 0,
    waterG: 0,
  },

  // --------------------------------------------------------------------
  // SUGARS & CONDIMENTS
  // --------------------------------------------------------------------
  {
    foodCode: 'K001-SALT',
    name: 'Table Salt, Iodized (Sodium Chloride)',
    commonNames: ['salt', 'table salt', 'uppu', 'namak', 'rock salt'],
    category: 'Condiments & Spices',
    foodState: 'Raw',
    energyKcal: 0,
    proteinG: 0,
    fatG: 0,
    carbsG: 0,
    fiberG: 0,
    ironMg: 0,
    calciumMg: 0,
    sodiumMg: 38758, // Standard chemical value for NaCl: ~38.8g sodium per 100g
    potassiumMg: 0,
    zincMg: 0,
    magnesiumMg: 0,
    vitaminAMcg: 0,
    vitaminCMg: 0,
    thiamineB1Mg: 0,
    riboflavinB2Mg: 0,
    niacinB3Mg: 0,
    folateMcg: 0,
    waterG: 0.2,
  },
];

// Index map for O(1) code lookup
const IFCT_CODE_MAP = new Map<string, IfctFoodEntry>();
for (const entry of IFCT_2017_DATABASE) {
  IFCT_CODE_MAP.set(entry.foodCode.toUpperCase(), entry);
}

/**
 * Get verified IFCT entry by official food code
 */
export function getIfctEntryByCode(code: string): IfctFoodEntry | null {
  if (!code) return null;
  return IFCT_CODE_MAP.get(code.trim().toUpperCase()) || null;
}

/**
 * Normalizes search text by trimming, lowercasing, and removing punctuation
 */
function normalizeQuery(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();
}

/**
 * Find verified IFCT 2017 food entry from query text
 * Matches against commonNames, name, category, and foodState
 */
export function findIfctFood(
  query: string,
  preferredState?: 'Raw' | 'Cooked / Boiled' | 'Steamed' | 'Roasted / Puffed' | 'Fermented' | 'Liquid'
): IfctFoodEntry | null {
  if (!query) return null;
  const q = normalizeQuery(query);
  if (!q) return null;

  // 1. Check direct water rule FIRST:
  // "Water", "warm water", "plain water", "filtered water", "room temp water"
  const isPlainWater =
    q === 'water' ||
    q === 'warm water' ||
    q === 'plain water' ||
    q === 'drinking water' ||
    q === 'boiled water' ||
    q === 'filtered water' ||
    q === 'room temp water' ||
    q.startsWith('water throughout') ||
    q.startsWith('plain filtered') ||
    (q.includes('water') && !q.includes('coconut') && !q.includes('seed') && !q.includes('methi') && !q.includes('rice'));

  if (isPlainWater) {
    return getIfctEntryByCode('W000-WATER');
  }

  // 2. Exact code match
  const directCode = getIfctEntryByCode(query.trim());
  if (directCode) return directCode;

  // 3. Exact common name or alias match
  let bestCandidate: IfctFoodEntry | null = null;
  let bestMatchScore = 0;

  for (const item of IFCT_2017_DATABASE) {
    // Check aliases
    for (const alias of item.commonNames) {
      const a = normalizeQuery(alias);
      if (q === a) {
        // Exact full string match
        let score = 100;
        if (preferredState && item.foodState === preferredState) score += 20;
        if (score > bestMatchScore) {
          bestMatchScore = score;
          bestCandidate = item;
        }
      } else if (q.includes(a) || a.includes(q)) {
        // Substring match
        let score = 50 + a.length;
        if (preferredState && item.foodState === preferredState) score += 20;
        if (score > bestMatchScore) {
          bestMatchScore = score;
          bestCandidate = item;
        }
      }
    }

    // Check official name
    const normName = normalizeQuery(item.name);
    if (normName.includes(q) || q.includes(normName)) {
      let score = 40 + normName.length;
      if (preferredState && item.foodState === preferredState) score += 20;
      if (score > bestMatchScore) {
        bestMatchScore = score;
        bestCandidate = item;
      }
    }
  }

  return bestCandidate;
}

/**
 * Energy conversion from kJ to kcal per ICMR-NIN IFCT standard:
 * kcal = kJ ÷ 4.184
 */
export function convertKjToKcal(energyKj: number): number {
  return Math.round((energyKj / 4.184) * 10) / 10;
}

/**
 * Mathematical Calculation Rule mandated by ICMR-NIN:
 * Nutrient for entered quantity = IFCT nutrient value per 100 g × entered quantity (g/ml) ÷ 100
 */
export function calculateIfctNutrient(valuePer100g: number, quantityGramsOrMl: number): number {
  if (valuePer100g === 0 || quantityGramsOrMl === 0) return 0;
  const raw = (valuePer100g * quantityGramsOrMl) / 100;
  // Round sensibly based on precision (macros to 2 decimals)
  return Math.round(raw * 100) / 100;
}

/**
 * Calculates nutrients from a food and produces an auditable, traceable calculation step
 */
export function calculateFoodNutrientsWithAudit(
  foodQuery: string,
  quantity: number,
  unit: string = 'g',
  stateOverride?: 'Raw' | 'Cooked / Boiled' | 'Steamed' | 'Roasted / Puffed' | 'Fermented' | 'Liquid'
): NutrientCalculationAuditStep {
  // Normalize quantity in grams or ml
  let effectiveGrams = quantity;
  const u = unit.toLowerCase().trim();
  if (u === 'kg') effectiveGrams = quantity * 1000;
  else if (u === 'l' || u === 'liter' || u === 'litres' || u === 'litre') effectiveGrams = quantity * 1000;

  const ifctEntry = findIfctFood(foodQuery, stateOverride);

  if (!ifctEntry) {
    // Strictly follow rule: "If a food is not available in the verified ICMR-NIN database, show 'Verified nutrient data unavailable' instead of inventing a value."
    return {
      foodName: foodQuery,
      enteredQuantity: quantity,
      enteredUnit: unit,
      ifctFoodCode: 'UNAVAILABLE',
      officialIfctName: 'Verified nutrient data unavailable in IFCT 2017',
      foodState: 'Unknown',
      category: 'Unverified',
      per100gReference: {
        energyKcal: 0,
        proteinG: 0,
        fatG: 0,
        carbsG: 0,
        fiberG: 0,
        ironMg: 0,
        calciumMg: 0,
        sodiumMg: 0,
        potassiumMg: 0,
        zincMg: 0,
        magnesiumMg: 0,
        vitaminAMcg: 0,
        vitaminCMg: 0,
        thiamineB1Mg: 0,
        riboflavinB2Mg: 0,
        niacinB3Mg: 0,
        folateMcg: 0,
      },
      calculationFormula: 'No verified laboratory database entry found in IFCT 2017.',
      calculatedNutrients: {
        energyKcal: 0,
        proteinG: 0,
        fatG: 0,
        carbsG: 0,
        fiberG: 0,
        ironMg: 0,
        calciumMg: 0,
        sodiumMg: 0,
        potassiumMg: 0,
        zincMg: 0,
        magnesiumMg: 0,
        vitaminAMcg: 0,
        vitaminCMg: 0,
        thiamineB1Mg: 0,
        riboflavinB2Mg: 0,
        niacinB3Mg: 0,
        folateMcg: 0,
        fluidLiters: 0,
      },
      isVerifiedIfct: false,
      auditExplanation: 'Verified nutrient data unavailable. Per ICMR-NIN guidelines, values must not be estimated or guessed.',
      statusMessage: 'Verified nutrient data unavailable',
    };
  }

  // Exact mathematical calculation per ICMR-NIN formula: Value/100g * Quantity / 100
  const energyKcal = calculateIfctNutrient(ifctEntry.energyKcal, effectiveGrams);
  const proteinG = calculateIfctNutrient(ifctEntry.proteinG, effectiveGrams);
  const fatG = calculateIfctNutrient(ifctEntry.fatG, effectiveGrams);
  const carbsG = calculateIfctNutrient(ifctEntry.carbsG, effectiveGrams);
  const fiberG = calculateIfctNutrient(ifctEntry.fiberG, effectiveGrams);
  const ironMg = calculateIfctNutrient(ifctEntry.ironMg, effectiveGrams);
  const calciumMg = calculateIfctNutrient(ifctEntry.calciumMg, effectiveGrams);
  const sodiumMg = calculateIfctNutrient(ifctEntry.sodiumMg, effectiveGrams);
  const potassiumMg = calculateIfctNutrient(ifctEntry.potassiumMg, effectiveGrams);
  const zincMg = calculateIfctNutrient(ifctEntry.zincMg, effectiveGrams);
  const magnesiumMg = calculateIfctNutrient(ifctEntry.magnesiumMg, effectiveGrams);
  const vitaminAMcg = calculateIfctNutrient(ifctEntry.vitaminAMcg, effectiveGrams);
  const vitaminCMg = calculateIfctNutrient(ifctEntry.vitaminCMg, effectiveGrams);
  const thiamineB1Mg = calculateIfctNutrient(ifctEntry.thiamineB1Mg, effectiveGrams);
  const riboflavinB2Mg = calculateIfctNutrient(ifctEntry.riboflavinB2Mg, effectiveGrams);
  const niacinB3Mg = calculateIfctNutrient(ifctEntry.niacinB3Mg, effectiveGrams);
  const folateMcg = calculateIfctNutrient(ifctEntry.folateMcg, effectiveGrams);

  const fluidLiters =
    ifctEntry.foodCode === 'W000-WATER' || ifctEntry.category === 'Water & Plain Beverages'
      ? effectiveGrams / 1000
      : ifctEntry.foodState === 'Liquid'
      ? (effectiveGrams * ((ifctEntry.waterG || 90) / 100)) / 1000
      : 0;

  // Construct clear arithmetic proof formula string
  const energyKjCalc = ifctEntry.energyKj ? Math.round(((ifctEntry.energyKj * effectiveGrams) / 100) * 10) / 10 : undefined;
  const energyFormulaStr = ifctEntry.energyKj
    ? `Energy = ${ifctEntry.energyKj} kJ × ${effectiveGrams} ÷ 100 = ${energyKjCalc} kJ ÷ 4.184 ≈ ${energyKcal} kcal`
    : `Energy = ${ifctEntry.energyKcal} kcal/100g × ${effectiveGrams}g ÷ 100 = ${energyKcal} kcal`;

  const calculationFormula =
    `${ifctEntry.name} (${ifctEntry.foodState}): ` +
    `${energyFormulaStr} | ` +
    `Protein = ${ifctEntry.proteinG}g × ${effectiveGrams} ÷ 100 = ${proteinG}g | ` +
    `Carbs = ${ifctEntry.carbsG}g × ${effectiveGrams} ÷ 100 = ${carbsG}g | ` +
    `Fat = ${ifctEntry.fatG}g × ${effectiveGrams} ÷ 100 = ${fatG}g | ` +
    `Fiber = ${ifctEntry.fiberG}g × ${effectiveGrams} ÷ 100 = ${fiberG}g | ` +
    `Iron = ${ifctEntry.ironMg}mg × ${effectiveGrams} ÷ 100 = ${ironMg}mg`;

  return {
    foodName: foodQuery,
    enteredQuantity: quantity,
    enteredUnit: unit,
    ifctFoodCode: ifctEntry.foodCode,
    officialIfctName: ifctEntry.name,
    foodState: ifctEntry.foodState,
    category: ifctEntry.category,
    per100gReference: {
      energyKcal: ifctEntry.energyKcal,
      proteinG: ifctEntry.proteinG,
      fatG: ifctEntry.fatG,
      carbsG: ifctEntry.carbsG,
      fiberG: ifctEntry.fiberG,
      ironMg: ifctEntry.ironMg,
      calciumMg: ifctEntry.calciumMg,
      sodiumMg: ifctEntry.sodiumMg,
      potassiumMg: ifctEntry.potassiumMg,
      zincMg: ifctEntry.zincMg,
      magnesiumMg: ifctEntry.magnesiumMg,
      vitaminAMcg: ifctEntry.vitaminAMcg,
      vitaminCMg: ifctEntry.vitaminCMg,
      thiamineB1Mg: ifctEntry.thiamineB1Mg,
      riboflavinB2Mg: ifctEntry.riboflavinB2Mg,
      niacinB3Mg: ifctEntry.niacinB3Mg,
      folateMcg: ifctEntry.folateMcg,
    },
    calculationFormula,
    calculatedNutrients: {
      energyKcal,
      proteinG,
      fatG,
      carbsG,
      fiberG,
      ironMg,
      calciumMg,
      sodiumMg,
      potassiumMg,
      zincMg,
      magnesiumMg,
      vitaminAMcg,
      vitaminCMg,
      thiamineB1Mg,
      riboflavinB2Mg,
      niacinB3Mg,
      folateMcg,
      fluidLiters: Math.round(fluidLiters * 100) / 100,
    },
    isVerifiedIfct: true,
    auditExplanation: `Certified ICMR-NIN IFCT 2017 entry [Code: ${ifctEntry.foodCode}]. Calculated via strict formula: Value/100g × ${effectiveGrams}g ÷ 100.`,
    statusMessage: `Verified ICMR-NIN IFCT 2017 [${ifctEntry.foodCode}]`,
  };
}
