import { NutrientBreakdown, Sex, ActivityLevel } from '../types';

/**
 * ICMR-NIN (National Institute of Nutrition) RDA 2024 & 2020 Guidelines
 * Reference standards for Indian adults
 */

export interface NutrientRdaTarget {
  name: string;
  unit: string;
  defaultTarget: number;
  minSafe?: number;
  maxSafe?: number;
  calculateForPatient?: (weightKg: number, sex: Sex, tdee: number) => number;
  category: 'Macronutrient' | 'Mineral' | 'Vitamin' | 'Hydration';
  clinicalRisk: string;
  clinicalExcessRisk?: string;
  correctiveFoods: string[];
}

/**
 * Standard adult nutritional benchmarks based on ICMR-NIN recommendations
 */
export const ICMR_NUTRIENT_BENCHMARKS: Record<string, NutrientRdaTarget> = {
  calories: {
    name: 'Total Energy',
    unit: 'kcal',
    defaultTarget: 1850,
    category: 'Macronutrient',
    calculateForPatient: (_weight, _sex, tdee) => (tdee > 0 ? tdee : 1850),
    clinicalRisk: 'Energy restriction causing chronic fatigue, impaired recovery, and lean mass loss.',
    clinicalExcessRisk: 'Chronic hypercaloric intake accelerating visceral adiposity and insulin resistance.',
    correctiveFoods: ['Soaked almonds', 'Ragi mudde', 'Pumpkin seeds', 'Brown rice', 'Barnyard millet'],
  },
  protein: {
    name: 'Total Protein',
    unit: 'g',
    defaultTarget: 60,
    category: 'Macronutrient',
    calculateForPatient: (weightKg) => (weightKg > 0 ? Math.round(weightKg * 1.0) : 60),
    clinicalRisk: 'Sarcopenia, blunted postprandial satiety, impaired glycemic regulation, and delayed tissue repair.',
    clinicalExcessRisk: 'Elevated blood urea nitrogen (BUN) in susceptible renal populations.',
    correctiveFoods: ['Sprouted green moong', 'Sattu flour', 'A2 Paneer / Tofu', 'Egg whites', 'Steamed edamame'],
  },
  carbs: {
    name: 'Carbohydrates',
    unit: 'g',
    defaultTarget: 220,
    category: 'Macronutrient',
    calculateForPatient: (_w, _s, tdee) => Math.round(((tdee || 1850) * 0.55) / 4),
    clinicalRisk: 'Ketosis, irritability, reduced thyroid conversion (T4 to T3), and impaired glycogen stores.',
    clinicalExcessRisk: 'Postprandial glycemic excursions, hyperinsulinemia, and hepatic lipogenesis.',
    correctiveFoods: ['Foxtail millet', 'Kodo millet', 'Whole oats', 'Quinoa', 'Sweet potato with skin'],
  },
  fat: {
    name: 'Total Fats',
    unit: 'g',
    defaultTarget: 45,
    category: 'Macronutrient',
    calculateForPatient: (_w, _s, tdee) => Math.round(((tdee || 1850) * 0.25) / 9),
    clinicalRisk: 'Deficiency of fat-soluble vitamins (A, D, E, K), hormonal disruption, dry skin, and joint pain.',
    clinicalExcessRisk: 'Elevated LDL-C, endothelial inflammation, and delayed gastric emptying.',
    correctiveFoods: ['Cold-pressed sesame oil', 'A2 Desi Cow Ghee', 'Flaxseed oil', 'Avocado', 'Walnuts'],
  },
  fiber: {
    name: 'Dietary Fiber',
    unit: 'g',
    defaultTarget: 35,
    category: 'Macronutrient',
    clinicalRisk: 'Rapid glycemic spikes, impaired SCFA (butyrate) synthesis, dysbiosis, and chronic constipation.',
    clinicalExcessRisk: 'Transient abdominal distension if fluid intake is insufficient.',
    correctiveFoods: ['Psyllium husk (Isabgol)', 'Flaxseeds', 'Methi (fenugreek) leaves', 'Raw guava with seeds', 'Amaranth greens'],
  },
  calcium: {
    name: 'Elemental Calcium',
    unit: 'mg',
    defaultTarget: 1000,
    category: 'Mineral',
    clinicalRisk: 'Bone demineralization (osteopenia), nocturnal leg cramps, muscle fasciculations, and arterial stiffness.',
    correctiveFoods: ['Finger millet (Ragi)', 'White sesame seeds (Til)', 'Curd / Yogurt', 'Moringa (drumstick) leaves'],
  },
  iron: {
    name: 'Elemental Iron',
    unit: 'mg',
    defaultTarget: 19,
    category: 'Mineral',
    calculateForPatient: (_w, sex) => (sex === 'Female' ? 29 : 19),
    clinicalRisk: 'Microcytic hypochromic anemia, cognitive brain fog, cold extremities, and reduced cellular oxygenation.',
    correctiveFoods: ['Garden cress seeds (Aliv / Halim)', 'Black soaked raisins', 'Beetroot & amla juice', 'Spinach (Palak)'],
  },
  zinc: {
    name: 'Elemental Zinc',
    unit: 'mg',
    defaultTarget: 17,
    category: 'Mineral',
    clinicalRisk: 'Impaired insulin crystallization in beta cells, blunted taste (dysgeusia), and weakened humoral immunity.',
    correctiveFoods: ['Pumpkin seeds', 'Watermelon seeds', 'Lentils & chickpeas', 'Cashews'],
  },
  magnesium: {
    name: 'Elemental Magnesium',
    unit: 'mg',
    defaultTarget: 380,
    category: 'Mineral',
    clinicalRisk: 'Insulin receptor tyrosine kinase desensitization, vascular spasms, elevated cortisol, and restless legs.',
    correctiveFoods: ['Pumpkin seeds', 'Raw cacao nibs', 'Almonds', 'Amaranth leaves', 'Chia seeds'],
  },
  sodium: {
    name: 'Sodium',
    unit: 'mg',
    defaultTarget: 2000,
    maxSafe: 2000,
    category: 'Mineral',
    clinicalRisk: 'Hyponatremia only in prolonged endurance sweating or severe fluid restriction.',
    clinicalExcessRisk: 'Fluid retention, systemic endothelial shear stress, and elevated systolic blood pressure.',
    correctiveFoods: ['Rock salt / Pink Himalayan salt in moderation', 'Unsalted roasted seeds'],
  },
  potassium: {
    name: 'Potassium',
    unit: 'mg',
    defaultTarget: 3500,
    category: 'Mineral',
    clinicalRisk: 'Altered Na:K balance leading to elevated systolic pressure, cardiac arrhythmias, and muscle weakness.',
    correctiveFoods: ['Fresh tender coconut water', 'Raw banana stem juice', 'Spinach', 'Muskmelon', 'Sweet potato'],
  },
  vitaminA: {
    name: 'Vitamin A',
    unit: 'mcg',
    defaultTarget: 1000,
    category: 'Vitamin',
    clinicalRisk: 'Impaired epithelial integrity, dry eyes (xerophthalmia), follicular hyperkeratosis, and lowered mucosal immunity.',
    correctiveFoods: ['Carrots', 'Moringa leaves', 'Ripe papaya', 'Sweet potato', 'Spinach'],
  },
  vitaminC: {
    name: 'Vitamin C',
    unit: 'mg',
    defaultTarget: 80,
    category: 'Vitamin',
    clinicalRisk: 'Capillary fragility, impaired collagen cross-linking, diminished non-heme iron absorption, and oxidative stress.',
    correctiveFoods: ['Indian gooseberry (Amla)', 'Guava', 'Lemon juice', 'Raw bell peppers', 'Sprouted moong'],
  },
  vitaminD: {
    name: 'Vitamin D3',
    unit: 'IU',
    defaultTarget: 800,
    category: 'Vitamin',
    clinicalRisk: 'Impaired pancreatic beta-cell insulin secretion, generalized myalgia, osteomalacia, and seasonal fatigue.',
    correctiveFoods: ['Sun-exposed wild mushrooms', 'Fortified dairy / plant milk', 'Egg yolk', 'Safe midday sunlight exposure'],
  },
  folate: {
    name: 'Dietary Folate',
    unit: 'mcg',
    defaultTarget: 300,
    category: 'Vitamin',
    clinicalRisk: 'Elevated homocysteine (cardiovascular risk factor), megaloblastic anemia, and impaired DNA methylation.',
    correctiveFoods: ['Steamed asparagus', 'Sprouted lentils', 'Spinach', 'Beetroot', 'Citrus fruits'],
  },
  vitaminB12: {
    name: 'Vitamin B12 (Cobalamin)',
    unit: 'mcg',
    defaultTarget: 2.5,
    category: 'Vitamin',
    clinicalRisk: 'Diabetic peripheral neuropathy, glove-and-stocking paresthesia, macrocytic anemia, and elevated homocysteine.',
    correctiveFoods: ['Fortified nutritional yeast', 'Cultured Greek yogurt', 'Desi cow milk / A2 paneer', 'Eggs / B12 repletion'],
  },
  fluid: {
    name: 'Fluid / Water Intake',
    unit: 'L',
    defaultTarget: 2.8,
    category: 'Hydration',
    calculateForPatient: (weightKg) => (weightKg > 0 ? parseFloat((weightKg * 0.035).toFixed(1)) : 2.8),
    clinicalRisk: 'Reduced glomerular filtration, hemoconcentration, constipation, and false hunger signals.',
    clinicalExcessRisk: 'Dilutional hyponatremia if consumed rapidly without electrolytes.',
    correctiveFoods: ['Jeera (cumin) water', 'Buttermilk with curry leaves & ginger', 'Infused mint & cucumber water', 'Plain warm water'],
  },
};

/**
 * Standard household measure to gram/ml multipliers
 */
export const PORTION_CONVERSIONS: Record<string, number> = {
  g: 1,
  gram: 1,
  grams: 1,
  gm: 1,
  ml: 1,
  l: 1000,
  liter: 1000,
  litres: 1000,
  litre: 1000,
  cup: 200,
  cups: 200,
  katori: 150,
  bowl: 180,
  bowls: 180,
  glass: 250,
  glasses: 250,
  tbsp: 15,
  tablespoon: 15,
  tsp: 5,
  teaspoon: 5,
  nos: 1,
  piece: 1,
  pieces: 1,
  slice: 30,
  slices: 30,
  roti: 35,
  rotis: 35,
  phulka: 35,
  phulkas: 35,
  chapati: 40,
  chapatis: 40,
  idli: 50,
  idlis: 50,
  dosa: 80,
  dosas: 80,
  nuts: 2,
};

/**
 * Food item composition reference database (per standard serving/portion or per 100g)
 * Contains nutritional profiles for typical Indian 24-hr recall meals and foods.
 */
export interface FoodReferenceItem {
  id: string;
  names: string[]; // Aliases/keywords to match in recall logs
  defaultServingGrams: number;
  nutrientsPer100g: NutrientBreakdown & { fluidLiters?: number };
}

export const FOOD_NUTRIENT_DICTIONARY: FoodReferenceItem[] = [
  {
    id: 'food-ragi-idli',
    names: ['ragi idli', 'finger millet idli', 'ragi idlis'],
    defaultServingGrams: 150, // approx 3 idlis (50g each)
    nutrientsPer100g: {
      calories: 145,
      carbs: 28.5,
      protein: 4.8,
      fat: 1.2,
      fiber: 4.2,
      calcium: 120,
      iron: 2.1,
      zinc: 1.1,
      magnesium: 48,
      sodium: 180,
      potassium: 195,
      vitaminA: 15,
      vitaminC: 0,
      vitaminD: 0,
      folate: 12,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-plain-idli',
    names: ['idli', 'idlis', 'rice idli', 'steamed idli'],
    defaultServingGrams: 150,
    nutrientsPer100g: {
      calories: 132,
      carbs: 28.0,
      protein: 3.9,
      fat: 0.4,
      fiber: 1.4,
      calcium: 18,
      iron: 0.9,
      zinc: 0.7,
      magnesium: 22,
      sodium: 190,
      potassium: 85,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      folate: 9,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-sambar',
    names: ['sambar', 'vegetable sambar', 'drumstick sambar'],
    defaultServingGrams: 150, // 1 katori
    nutrientsPer100g: {
      calories: 68,
      carbs: 9.8,
      protein: 3.2,
      fat: 1.8,
      fiber: 2.8,
      calcium: 38,
      iron: 1.2,
      zinc: 0.8,
      magnesium: 28,
      sodium: 280,
      potassium: 210,
      vitaminA: 95,
      vitaminC: 8.5,
      vitaminD: 0,
      folate: 24,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-mint-chutney',
    names: ['mint chutney', 'pudina chutney', 'coriander chutney', 'green chutney'],
    defaultServingGrams: 30, // 2 tbsp
    nutrientsPer100g: {
      calories: 72,
      carbs: 6.4,
      protein: 2.8,
      fat: 3.8,
      fiber: 3.1,
      calcium: 95,
      iron: 3.2,
      zinc: 0.9,
      magnesium: 35,
      sodium: 240,
      potassium: 260,
      vitaminA: 320,
      vitaminC: 22.0,
      vitaminD: 0,
      folate: 45,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-guava',
    names: ['guava', 'amrood', 'fresh guava', 'guava slices'],
    defaultServingGrams: 100, // 1 medium fruit
    nutrientsPer100g: {
      calories: 68,
      carbs: 14.3,
      protein: 2.6,
      fat: 1.0,
      fiber: 5.4,
      calcium: 18,
      iron: 0.4,
      zinc: 0.3,
      magnesium: 22,
      sodium: 2,
      potassium: 417,
      vitaminA: 31,
      vitaminC: 228.0,
      vitaminD: 0,
      folate: 49,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-foxtail-millet-cooked',
    names: ['foxtail millet', 'thinai', 'cooked foxtail millet'],
    defaultServingGrams: 180, // 1 cup cooked
    nutrientsPer100g: {
      calories: 125,
      carbs: 24.2,
      protein: 4.1,
      fat: 1.4,
      fiber: 3.2,
      calcium: 12,
      iron: 1.2,
      zinc: 1.0,
      magnesium: 34,
      sodium: 4,
      potassium: 95,
      vitaminA: 10,
      vitaminC: 0,
      vitaminD: 0,
      folate: 8,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-palak-dal',
    names: ['palak dal', 'spinach dal', 'dal with spinach', 'dal palak'],
    defaultServingGrams: 150,
    nutrientsPer100g: {
      calories: 88,
      carbs: 11.2,
      protein: 5.4,
      fat: 2.2,
      fiber: 3.8,
      calcium: 68,
      iron: 2.8,
      zinc: 1.2,
      magnesium: 42,
      sodium: 210,
      potassium: 290,
      vitaminA: 380,
      vitaminC: 9.2,
      vitaminD: 0,
      folate: 52,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-cucumber-tomato-salad',
    names: ['cucumber tomato salad', 'salad', 'green salad', 'kachumber'],
    defaultServingGrams: 100,
    nutrientsPer100g: {
      calories: 22,
      carbs: 4.2,
      protein: 1.1,
      fat: 0.3,
      fiber: 1.8,
      calcium: 16,
      iron: 0.6,
      zinc: 0.3,
      magnesium: 15,
      sodium: 12,
      potassium: 190,
      vitaminA: 85,
      vitaminC: 14.5,
      vitaminD: 0,
      folate: 18,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-curd',
    names: ['curd', 'yogurt', 'dahi', 'low fat curd', 'plain curd'],
    defaultServingGrams: 150,
    nutrientsPer100g: {
      calories: 62,
      carbs: 4.8,
      protein: 4.2,
      fat: 3.1,
      fiber: 0,
      calcium: 145,
      iron: 0.1,
      zinc: 0.6,
      magnesium: 14,
      sodium: 48,
      potassium: 155,
      vitaminA: 38,
      vitaminC: 1.0,
      vitaminD: 0.1,
      folate: 8,
      vitaminB12: 0.45,
    },
  },
  {
    id: 'food-sprouted-moong-sundal',
    names: ['sprouted green gram sundal', 'moong sundal', 'sprouted moong', 'sprouts sundal', 'roasted sprouted green gram'],
    defaultServingGrams: 80,
    nutrientsPer100g: {
      calories: 128,
      carbs: 19.5,
      protein: 8.2,
      fat: 2.1,
      fiber: 5.6,
      calcium: 44,
      iron: 2.9,
      zinc: 1.4,
      magnesium: 54,
      sodium: 120,
      potassium: 340,
      vitaminA: 42,
      vitaminC: 18.2,
      vitaminD: 0,
      folate: 65,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-green-tea',
    names: ['green tea', 'herbal tea', 'black tea'],
    defaultServingGrams: 150,
    nutrientsPer100g: {
      calories: 2,
      carbs: 0.3,
      protein: 0.2,
      fat: 0,
      fiber: 0,
      calcium: 2,
      iron: 0.05,
      zinc: 0.02,
      magnesium: 3,
      sodium: 1,
      potassium: 25,
      vitaminA: 0,
      vitaminC: 0.5,
      vitaminD: 0,
      folate: 2,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-multigrain-phulka',
    names: ['multigrain phulka', 'phulka', 'roti', 'chapati', 'wheat methi phulka', 'rotis'],
    defaultServingGrams: 70, // 2 rotis
    nutrientsPer100g: {
      calories: 245,
      carbs: 48.0,
      protein: 8.9,
      fat: 2.4,
      fiber: 7.2,
      calcium: 48,
      iron: 3.1,
      zinc: 1.8,
      magnesium: 62,
      sodium: 95,
      potassium: 220,
      vitaminA: 35,
      vitaminC: 0,
      vitaminD: 0,
      folate: 28,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-ridge-gourd-curry',
    names: ['ridge gourd curry', 'peerkangai', 'turai curry', 'bottle gourd curry'],
    defaultServingGrams: 150,
    nutrientsPer100g: {
      calories: 46,
      carbs: 6.2,
      protein: 1.4,
      fat: 1.8,
      fiber: 2.6,
      calcium: 32,
      iron: 1.1,
      zinc: 0.5,
      magnesium: 24,
      sodium: 190,
      potassium: 160,
      vitaminA: 48,
      vitaminC: 7.4,
      vitaminD: 0,
      folate: 22,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-turmeric-milk',
    names: ['turmeric milk', 'golden milk', 'warm turmeric low-fat milk', 'milk with nutmeg', 'low-fat milk'],
    defaultServingGrams: 150,
    nutrientsPer100g: {
      calories: 58,
      carbs: 5.0,
      protein: 3.4,
      fat: 1.8,
      fiber: 0.2,
      calcium: 122,
      iron: 0.3,
      zinc: 0.4,
      magnesium: 16,
      sodium: 52,
      potassium: 162,
      vitaminA: 42,
      vitaminC: 1.2,
      vitaminD: 0.4,
      folate: 6,
      vitaminB12: 0.4,
    },
  },
  {
    id: 'food-soaked-almonds',
    names: ['almonds', 'soaked almonds', 'badam'],
    defaultServingGrams: 10, // ~5 nuts
    nutrientsPer100g: {
      calories: 579,
      carbs: 21.6,
      protein: 21.2,
      fat: 49.9,
      fiber: 12.5,
      calcium: 269,
      iron: 3.7,
      zinc: 3.1,
      magnesium: 270,
      sodium: 1,
      potassium: 733,
      vitaminA: 1,
      vitaminC: 0,
      vitaminD: 0,
      folate: 44,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-methi-water',
    names: ['methi water', 'methi seed soaked water', 'fenugreek water'],
    defaultServingGrams: 250,
    nutrientsPer100g: {
      calories: 12,
      carbs: 1.8,
      protein: 0.8,
      fat: 0.2,
      fiber: 1.4,
      calcium: 24,
      iron: 1.1,
      zinc: 0.3,
      magnesium: 18,
      sodium: 4,
      potassium: 42,
      vitaminA: 6,
      vitaminC: 1.2,
      vitaminD: 0,
      folate: 14,
      vitaminB12: 0,
    },
  },
  {
    id: 'food-water',
    names: ['water', 'plain filtered room temp', 'filtered water', 'drinking water'],
    defaultServingGrams: 1000,
    nutrientsPer100g: {
      calories: 0,
      carbs: 0,
      protein: 0,
      fat: 0,
      fiber: 0,
      calcium: 3,
      iron: 0,
      zinc: 0,
      magnesium: 2,
      sodium: 2,
      potassium: 1,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
      folate: 0,
      vitaminB12: 0,
      fluidLiters: 0.1,
    },
  },
  {
    id: 'food-paneer',
    names: ['paneer', 'cottage cheese', 'a2 paneer'],
    defaultServingGrams: 60,
    nutrientsPer100g: {
      calories: 265,
      carbs: 3.2,
      protein: 18.3,
      fat: 20.8,
      fiber: 0,
      calcium: 480,
      iron: 0.4,
      zinc: 2.1,
      magnesium: 28,
      sodium: 42,
      potassium: 95,
      vitaminA: 82,
      vitaminC: 0,
      vitaminD: 0.3,
      folate: 18,
      vitaminB12: 0.8,
    },
  },
  {
    id: 'food-egg-boiled',
    names: ['egg', 'boiled egg', 'eggs', 'egg white'],
    defaultServingGrams: 50, // 1 large egg
    nutrientsPer100g: {
      calories: 143,
      carbs: 0.7,
      protein: 12.6,
      fat: 9.5,
      fiber: 0,
      calcium: 56,
      iron: 1.8,
      zinc: 1.3,
      magnesium: 12,
      sodium: 142,
      potassium: 138,
      vitaminA: 160,
      vitaminC: 0,
      vitaminD: 2.0,
      folate: 47,
      vitaminB12: 1.1,
    },
  },
];

/**
 * Nutrient Deficit Classification Thresholds
 */
export const NUTRIENT_GAP_THRESHOLDS = {
  criticalDeficitPercent: 70, // < 70% adequacy
  moderateDeficitPercent: 90, // 70% - 89% adequacy
  optimalMaxPercent: 115,     // 90% - 115% adequacy
  excessPercent: 115,         // > 115% (for sodium/calories > 110%)
};

/**
 * Macro Energy Distribution Targets (% of Total Calories)
 */
export const MACRO_DISTRIBUTION_TARGETS = {
  carbs: { min: 50, max: 60, target: 55 },
  protein: { min: 15, max: 20, target: 18 },
  fat: { min: 20, max: 30, target: 25 },
};
